### DISCUSSION TITLE
Why doesn't overhead.podFixed resources seem to work in Kata VM?

### DISCUSSION THREAD

**Discussion by shenxianghong** [kata-containers/kata-containers#2537] [General]
overhead.podFixed:
```shell
$ kubectl get pod huayun-kata -o jsonpath='{.spec.overhead}'
map[cpu:5 memory:1000Mi]
```

pod limit: 
```yaml
resources:
    limits:
        cpu: "1"
        memory: 2000Mi
```
     

in Kata VM:
```shell
$ cat /proc/cpuinfo  | grep processor | wc -l
2
```
```shell
free -m
              total        used        free      shared  buff/cache   available
Mem:           4042          50        3961          28          30        3923
Swap:             0           0           0
```
    
part of my Kata configuration file:
```toml
default_maxvcpus = 0
default_vcpus = 1
default_memory = 2048
sandbox_cgroup_only=true
```

My understanding is that 5 cpus are set in the overhead, plus 1 cpu in the pod limit and 1 cpu in the kata configuration file. I should see 7 cpus in the kata vm. 
But it seems that the resources in Kata VM is not affected by overhead. 
So why? Did i misunderstanding something?
