### ISSUE TITLE
kata-qemu-tdx mount volume is very slow and grows non-linearly

### ISSUE THREAD

**Issue by JakubLedworowski** [kata-containers/kata-containers#10322]
# Description of problem

1. Prepare Intel platform with TDX enabled and kubernetes cluster
2. Install nydus-snapshotter v0.13.14 to the cluster
3. Install kata-containers with kata-qemu and kata-qemu-tdx runtime classes v3.8.0
4. Prepare the following directories and files on worker node:

  ```
  mkdir -p /tmp && cd /tmp
  dd if=/dev/zero of=big-file-128M.img bs=128M count=1
  dd if=/dev/zero of=big-file-256M.img bs=128M count=2
  dd if=/dev/zero of=big-file-384M.img bs=128M count=3
  dd if=/dev/zero of=big-file-512M.img bs=128M count=4
  dd if=/dev/zero of=big-file-640M.img bs=128M count=5
  ```

5. Prepare the following pod definitions as `dummy-issue.yaml`:

  ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-issue-128m
      annotations:
        io.katacontainers.config.runtime.create_container_timeout: "120"
    spec:
      runtimeClassName: kata-qemu-tdx
      containers:
        - name: dummy
          image: storytel/alpine-bash-curl:latest
          imagePullPolicy: Always
          command: [ "/bin/sh","-c" ]
          args:
            - |
              while :; do echo '.'; sleep 5 ; done
          resources:
            limits:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /data
              name: big-file
      volumes:
        - name: big-file
          hostPath:
            path: /tmp/big-file-128M.img
            type: File
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-issue-256m
      annotations:
        io.katacontainers.config.runtime.create_container_timeout: "120"
    spec:
      runtimeClassName: kata-qemu-tdx
      containers:
        - name: dummy
          image: storytel/alpine-bash-curl:latest
          imagePullPolicy: Always
          command: [ "/bin/sh","-c" ]
          args:
            - |
              while :; do echo '.'; sleep 5 ; done
          resources:
            limits:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /data
              name: big-file
      volumes:
        - name: big-file
          hostPath:
            path: /tmp/big-file-256M.img
            type: File
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-issue-384m
      annotations:
        io.katacontainers.config.runtime.create_container_timeout: "120"
    spec:
      runtimeClassName: kata-qemu-tdx
      containers:
        - name: dummy
          image: storytel/alpine-bash-curl:latest
          imagePullPolicy: Always
          command: [ "/bin/sh","-c" ]
          args:
            - |
              while :; do echo '.'; sleep 5 ; done
          resources:
            limits:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /data
              name: big-file
      volumes:
        - name: big-file
          hostPath:
            path: /tmp/big-file-384M.img
            type: File
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-issue-512m
      annotations:
        io.katacontainers.config.runtime.create_container_timeout: "120"
    spec:
      runtimeClassName: kata-qemu-tdx
      containers:
        - name: dummy
          image: storytel/alpine-bash-curl:latest
          imagePullPolicy: Always
          command: [ "/bin/sh","-c" ]
          args:
            - |
              while :; do echo '.'; sleep 5 ; done
          resources:
            limits:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /data
              name: big-file
      volumes:
        - name: big-file
          hostPath:
            path: /tmp/big-file-512M.img
            type: File
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-issue-640m
      annotations:
        io.katacontainers.config.runtime.create_container_timeout: "120"
    spec:
      runtimeClassName: kata-qemu-tdx
      containers:
        - name: dummy
          image: storytel/alpine-bash-curl:latest
          imagePullPolicy: Always
          command: [ "/bin/sh","-c" ]
          args:
            - |
              while :; do echo '.'; sleep 5 ; done
          resources:
            limits:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /data
              name: big-file
      volumes:
        - name: big-file
          hostPath:
            path: /tmp/big-file-640M.img
            type: File
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-issue-vm-only-128m
      annotations:
        io.katacontainers.config.runtime.create_container_timeout: "120"
    spec:
      runtimeClassName: kata-qemu
      containers:
        - name: dummy
          image: storytel/alpine-bash-curl:latest
          imagePullPolicy: Always
          command: [ "/bin/sh","-c" ]
          args:
            - |
              while :; do echo '.'; sleep 5 ; done
          resources:
            limits:
              memory: "2Gi"
          volumeMounts:
            - mountPath: /data
              name: big-file
      volumes:
        - name: big-file
          hostPath:
            path: /tmp/big-file-128M.img
            type: File
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: dummy-issue
      annotations:
        io.katacontainers.config.runtime.create_container_timeout: "120"
    spec:
      runtimeClassName: kata-qemu-tdx
      containers:
        - name: dummy
          image: storytel/alpine-bash-curl:latest
          imagePullPolicy: Always
          command: [ "/bin/sh","-c" ]
          args:
            - |
              while :; do echo '.'; sleep 5 ; done
          resources:
            limits:
              memory: "2Gi"
  ```

6. Deploy:

    `kubectl apply -f dummy-issue.yaml`

8. Get elapsed time from `PodScheduled` to `Ready`:

    ```
    for pod in dummy-issue-128m dummy-issue-256m dummy-issue-384m dummy-issue-512m dummy-issue-640m; do kubectl get pod $pod -o jsonpath='{.status.conditions[?(@.type=="PodScheduled")].lastTransitionTime}{"\n"}{.status.conditions[?(@.type=="Ready")].lastTransitionTime}' | xargs -n 2 bash -c 'echo "Elapsed time for pod '$pod': $(( $(date -d $1 +%s) - $(date -d $0 +%s) )) seconds"'; done
    ```

    Result:
    
    ```
    Elapsed time for pod dummy-issue-128m: 35 seconds
    Elapsed time for pod dummy-issue-256m: 53 seconds
    Elapsed time for pod dummy-issue-384m: 75 seconds
    Elapsed time for pod dummy-issue-512m: 97 seconds
    Elapsed time for pod dummy-issue-640m: 121 seconds
    ```

9. To calculate absolute time for volume mount without time for starting up the TDX-protected VM (TD) you need to subtract the elapsed time for `dummy-issue` pod which has no volume mounted:

    ```
    for pod in dummy-issue; do kubectl get pod $pod -o jsonpath='{.status.conditions[?(@.type=="PodScheduled")].lastTransitionTime}{"\n"}{.status.conditions[?(@.type=="Ready")].lastTransitionTime}' | xargs -n 2 bash -c 'echo "Elapsed time for pod '$pod': $(( $(date -d $1 +%s) - $(date -d $0 +%s) )) seconds"'; done
    ```

    Result: `Elapsed time for pod dummy-issue: 16 seconds`

10. With these data you can calculate the ratio of the time taken for volume mount by using this formula:

    `(Time taken to start pod dummy-issue-X - Time taken to start pod dummy-issue) / (Time taken to start pod dummy-issue-128m - Time taken to start pod dummy-issue)`

# Expected result

1. Firstly, the time taken to mount volume should be way faster. For comparison, the mount of 128m data (`dummy-issue-vm-only-128m`) to non-TDX VM (`kata-qemu`) takes only 4 seconds including kata VM startup, which you can check by running: 

    ```
    for pod in dummy-issue-vm-only-128m; do kubectl get pod $pod -o jsonpath='{.status.conditions[?(@.type=="PodScheduled")].lastTransitionTime}{"\n"}{.status.conditions[?(@.type=="Ready")].lastTransitionTime}' | xargs -n 2 bash -c 'echo "Elapsed time for pod '$pod': $(( $(date -d $1 +%s) - $(date -d $0 +%s) )) seconds"'; done
    ```

    Result: `Elapsed time for pod dummy-issue-vm-only-128m: 4 seconds`

2. Secondly, the elapsed time for mounting volume for pods dummy-issue-128m->dummy-issue-640m should increase linearly with ratio 1,2,3,4,5.

# Actual result

The elapsed time for mounting volume increases non-linearly with ratios:
1, 1.95, 3.1, 4.26, 5.53

See the below graphics with excel calculations:

![image](https://github.com/user-attachments/assets/9ccaa077-df59-4914-8d27-977801eb86c2)

# Further information

Behavior (slowness) is the same when mounting with PersistenceVolume with `volumeMode: Filesystem`.
It works fast (instantly) only with PersistenceVolume with `volumeMode: Block` which is not usable in some cases, because the application needs to know how to operate a raw block device.

Kata-deploy image: quay.io/fidencio/kata-containers:3.8.0-with-ita-v0.0.1
Image comes from this branch: https://github.com/fidencio/kata-containers/tree/intel/3.8.0-with-ita
Commit: [b4811d0c](https://github.com/fidencio/kata-containers/commit/b4811d0c0d62a7093ce869fda2c16909d784406b)
Tested host OS: Ubuntu 24.04
Kernel: 6.8.0
