### ISSUE TITLE
How to enable encrypted storage for k8s kata containers?

### ISSUE THREAD

**Issue by qzheng527** [kata-containers/kata-containers#10344]
Sometimes there is requirement to save sensitive data for k8s kata containers. Is there any suggested way to do that?
I found a [PR](https://github.com/kata-containers/kata-containers/pull/9999) which is for coco trusted image storage. But is there any general way to enable encrypted storage for k8s kata containers? Not only image storage, but any specified path.
I also tried to mount a luks encrypted file to k8s kata container by general k8s volume mount way. But when I tried below command in container it gave error message.
```
root@:~# cryptsetup open /mnt/enc_storage.img enc_storage
Cannot initialize device-mapper. Is dm_mod kernel module loaded?
Cannot use device enc_storage, name is invalid or still in use.
```
I tried again by following the [doc](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md#example---using-annotations) to load extra modules **dm_mod; dm_crypt; dm_verity** but still same error.
Here is my test yaml.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: php-apache-kata-qemu
  annotations:
    io.katacontainers.config.agent.kernel_modules: "dm_mod; dm_crypt; dm_verity"
  name: php-apache-kata-qemu
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache-kata-qemu
  template:
    metadata:
      labels:
        run: php-apache-kata-qemu
    spec:
      runtimeClassName: kata
      containers:
      - image: ubuntu:24.04
        imagePullPolicy: Always
        name: ubuntu-test
        command: ["/bin/sh", "-c"]
        args:
          - sleep 6000
        volumeMounts:
        - name: luks-storage
          mountPath: /mnt
      volumes:
      - name: luks-storage
        hostPath:
          path: $HOME/work/test/luks_storage
```
