### ISSUE TITLE
Unable to run kata using hugepages: qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory" name

### ISSUE THREAD

**Issue by dborquez** [kata-containers/kata-containers#10341]
I enabled hugepages feature in QEMU as follows:

`enable_hugepages = true`

Then I tried to launch a container:

`ctr run -t --runtime io.containerd.kata.v2 public.ecr.aws/ubuntu/ubuntu:latest test-hp bash`

however the container halted at boot.

 The journal log for the hanged container is listed below:

> Sep 23 03:01:22 ubuntu2204 kata[1779636]: time="2024-09-23T03:01:22.533334533-07:00" level=error msg="qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory" name=containerd-shim-v2 pid=1779636 qemuPid=1779646 sandbox=test-ubuntu1 source=virtcontainers/hypervisor subsystem=qemu
> Sep 23 03:01:22 ubuntu2204 containerd[1779312]: time="2024-09-23T03:01:22.533334533-07:00" level=error msg="qemu-system-x86_64: unable to map backing store for guest RAM: Cannot allocate memory" name=containerd-shim-v2 pid=1779636 qemuPid=1779646 sandbox=test-ubuntu1 source=virtcontainers/hypervisor subsystem=qemu
> 

Here it is the environment that I am using:

<details>
<summary>Show <tt>kata-collect-data.sh</tt> details</summary>
<p>

# Meta details

Running `kata-collect-data.sh` version `3.6.0 (commit b7051890af22f80a9f9d8bb9b48b2e3e2a9fee52)` at `2024-09-23.02:08:13.121873511-0700`.

---

<details>
<summary>Runtime</summary>
<p>

Runtime is `/usr/local/bin/kata-runtime`.

# `kata-env`

<details>
<summary><tt>/usr/local/bin/kata-runtime kata-env</tt></summary>
<p>

```toml
[Kernel]
  Path = "/opt/kata/share/kata-containers/vmlinux-6.1.62-134"
  Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none agent.log=debug"

[Meta]
  Version = "1.0.27"

[Image]
  Path = "/opt/kata/share/kata-containers/kata-ubuntu-latest.image"

[Initrd]
  Path = ""

[Hypervisor]
  MachineType = "q35"
  Version = "QEMU emulator version 8.2.4 (kata-static)\nCopyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers"
  Path = "/opt/kata/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  SharedFS = "virtio-9p"
  VirtioFSDaemon = "/opt/kata/libexec/virtiofsd"
  SocketPath = ""
  Msize9p = 8192
  MemorySlots = 10
  HotPlugVFIO = "no-port"
  ColdPlugVFIO = "no-port"
  PCIeRootPort = 0
  PCIeSwitchPort = 0
  Debug = true
  [Hypervisor.SecurityInfo]
    Rootless = false
    DisableSeccomp = false
    GuestHookPath = ""
    EnableAnnotations = ["enable_iommu", "virtio_fs_extra_args", "kernel_params"]
    ConfidentialGuest = false

[Runtime]
  Path = "/opt/kata/bin/kata-runtime"
  GuestSeLinuxLabel = ""
  Debug = true
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  SandboxCgroupOnly = false
  [Runtime.Config]
    Path = "/opt/kata/share/defaults/kata-containers/configuration-qemu-debug.toml"
  [Runtime.Version]
    OCI = "1.1.0+dev"
    [Runtime.Version.Version]
      Semver = "3.6.0"
      Commit = "b7051890af22f80a9f9d8bb9b48b2e3e2a9fee52"
      Major = 3
      Minor = 6
      Patch = 0

[Host]
  AvailableGuestProtections = ["tdx"]
  Kernel = "6.8.0-1008-intel"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "24.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Genuine Intel(R) 0000"
    CPUs = 256
  [Host.Memory]
    Total = 1056248340
    Free = 1032997020
    Available = 1030996004

[Agent]
  Debug = true
  Trace = false
```
