### ISSUE TITLE
kata-agent in vm can't access container image contents on NixOS

### ISSUE THREAD

**Issue by gerolf-vent** [kata-containers/kata-containers#10358]
# Description of problem

The kata-agent can't find the contents of the container image (kata-containers via cri-o on NixOS).

# Expected result

Pod is running and containers are reacheable.

# Actual result

K8s reports "Error: context deadline exceeded" for the pod.

# Further information

The kata-agent inside the vm can't find the `nginx` executeable of my test deployment (Log message: `create container process error the file nginx was not found`). 

Inside the vm the mount point `/run/kata-containers/shared/containers/9405c9c342a5fd404035450099b04165deb632bb2e631db25f6b02d50d0781de/rootfs` doesn't exist (i don't know how kata works internally, but should that be the nginx container image contents?). The other mount point `/run/kata-containers/shared/containers/7d194c9a016551bd712dcccead521f18dab44e21e62a0ee87cdaca87a2947d0a/rootfs` contains the contents of the pause container image and exists.

<details>
<summary>Output of <tt>mount</tt> inside the vm (via <tt>kata-runtime exec 7d194c9a016551bd712dcccead521f18dab44e21e62a0ee87cdaca87a2947d0a</tt>):</summary>
<p>

```
/dev/pmem0p1 on / type ext4 (ro,relatime,errors=remount-ro,data=ordered,dax=always)
devtmpfs on /dev type devtmpfs (rw,relatime,size=1011284k,nr_inodes=252821,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=202756k,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
nsfs on /run/sandbox-ns/ipc type nsfs (rw)
nsfs on /run/sandbox-ns/uts type nsfs (rw)
kataShared on /run/kata-containers/shared/containers type virtiofs (rw,relatime)
shm on /run/kata-containers/sandbox/shm type tmpfs (rw,relatime)
tmpfs on /etc/resolv.conf type tmpfs (rw,nosuid,nodev,size=202756k,mode=755)
none on /run/kata-containers/shared/containers/7d194c9a016551bd712dcccead521f18dab44e21e62a0ee87cdaca87a2947d0a/rootfs type virtiofs (rw,relatime)
none on /run/kata-containers/7d194c9a016551bd712dcccead521f18dab44e21e62a0ee87cdaca87a2947d0a/rootfs type virtiofs (rw,relatime)
none on /run/kata-containers/shared/containers/9405c9c342a5fd404035450099b04165deb632bb2e631db25f6b02d50d0781de/rootfs type virtiofs (rw,relatime)
```

</p>
</details>

Also on the host the kata runtime reports many `no loop device` errors. I checked the mount-source paths and they exist (but maybe it's a race condition at pod startup time, where they don't exist yet).

I've tested other backends (qemu, firecracker and rust runtime) with the same results.

### NixOS configuration
<details>
<summary>configuration.nix</summary>
<p>

```nix
{ config, lib, pkgs, ... }:

let
  pkgKataContainers = pkgs.callPackage ./kata-containers.nix { inherit pkgs; };
  kataConfig = pkgs.runCommand "" {
    pkgPath = pkgKataContainers;
    buildInputs = with pkgs; [ makeWrapper ];
  } ''
    cp ${./kata-configuration.toml} $out
    substituteAllInPlace $out  # This replaces @pkgPath@ with the real kata-containers package path
  '';
in {
  virtualisation.cri-o = {
    enable = true;
    extraPackages = with pkgs; [ crun kmod ];
    runtime = "crun";
    logLevel = "debug";
    settings = {
      crio = {
        network.plugin_dirs = [ "/opt/cni/bin" ];
        runtime.runtimes.kata = {
          runtime_path = "${pkgKataContainers}/bin/containerd-shim-kata-v2";
          runtime_config_path = "${kataConfig}";
          runtime_type = "vm";
          runtime_root = "/run/vc";
          privileged_without_host_devices = true;
        };
      };
    };
  };
}
```

</p>
</details>
<details>
<summary>kata-containers.nix</summary>
<p>

```nix
{ pkgs ? import <nixpkgs> {}, ... }:

let
  release = {
    version = "3.9.0";
    url = "https://github.com/kata-containers/kata-containers/releases/download/3.9.0/kata-static-3.9.0-amd64.tar.xz";
    hash = "c39cfa1aeb2bad2ffc1ebca22f0c1da39482148b950430d3be5e41946b95163a";
  };
in pkgs.stdenv.mkDerivation rec {
  pname = "kata-containers";
  version = release.version;

  src = builtins.fetchurl {
    url = release.url;
    sha256 = release.hash;
  };
  sourceRoot = "./opt/kata";

  nativeBuildInputs = with pkgs; [
    autoPatchelfHook  # This will replace the dynamic dependencies in binaries with their corresponding ones in the nix-store
  ];

  # Runtime dependencies
  buildInputs = with pkgs; [ 
    libseccomp
  ];

  # Replace the /opt/kata path in every non-binary file with our nix-store path (e.g. for configuration files)
  postPatch = ''
    for file in $(grep -rIl /opt/kata .); do
      substituteInPlace "$file" --replace-quiet "/opt/kata" "$out"
    done
  '';

  # Copy everything to our nix-store path
  installPhase = ''
    mkdir -p $out
    cp -r * $out
  '';

  meta = {
    homepage = "https://github.com/kata-containers/kata-containers";
    license = licenses.asl20;
    platforms = [ "x86_64-linux" ];
  };
}
```
</p>
</details>
<details>
<summary>kata-configuration.toml</summary>
<p>

```toml
[hypervisor.clh]
path = "@pkgPath@/bin/cloud-hypervisor"
kernel = "@pkgPath@/share/kata-containers/vmlinux.container"
image = "@pkgPath@/share/kata-containers/kata-containers.img"
rootfs_type="ext4"
disable_selinux=false
disable_guest_selinux=true
enable_annotations = ["enable_iommu", "virtio_fs_extra_args", "kernel_params"]
valid_hypervisor_paths = ["@pkgPath@/bin/cloud-hypervisor"]
kernel_params = " "
default_vcpus = 1
default_maxvcpus = 0
default_memory = 2048
default_maxmemory = 0
shared_fs = "virtio-fs"
virtio_fs_daemon = "@pkgPath@/libexec/virtiofsd"
valid_virtio_fs_daemon_paths = ["@pkgPath@/libexec/virtiofsd"]
virtio_fs_cache_size = 0
virtio_fs_queue_size = 1024
virtio_fs_extra_args = ["--thread-pool-size=1", "--announce-submounts"]
virtio_fs_cache = "auto"
block_device_driver = "virtio-blk"
enable_debug = true

[agent.kata]
enable_debug = true
debug_console_enabled = true
dial_timeout = 45

[runtime]
enable_debug = true
internetworking_model="tcfilter"
disable_guest_seccomp=true
sandbox_cgroup_only=true
static_sandbox_resource_mgmt=true
sandbox_bind_mounts=[]
vfio_mode="guest-kernel"
disable_guest_empty_dir=false
experimental=[]
create_container_timeout = 60
dan_conf = "/run/kata-containers/dans"
```

</p>
</details>

### Test-Deployment in K8s
<details>
<summary>runtime-class.yaml</summary>
<p>

```yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata
handler: kata
```

</p>
</details>
<details>
<summary>deployment-test.yaml</summary>
<p>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      runtimeClassName: kata
      nodeSelector:
        kubernetes.io/hostname: cwn1
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

</p>
</details>

### Output of `kata-collect-data.sh`
See [kata.log](https://github.com/user-attachments/files/17166970/kata.log) (it was too large for the Issue).
