### ISSUE TITLE
Remove KBS image pinning

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#10379]
Similar to https://github.com/confidential-containers/cloud-api-adaptor/issues/2076 - for trustee we have the following entries in verisons.yaml
```
  coco-trustee:
    description: "Provides attestation and secret delivery components"
    url: "https://github.com/confidential-containers/trustee"
    version: "v0.10.1"
    image: "ghcr.io/confidential-containers/key-broker-service"
    image_tag: "built-in-as-v0.10.1"
    toolchain: "1.74.0"
```
and our logic in https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/confidential_kbs.sh is to get clone the repo based on the `url` and `version`, but then use kustomize to edit the image based on `image` and `image_tag`. This embeds the assumption that the kustomize is compatbile with the image, which might not be true, so we could remove this and rely on trustee to manage their image for compatibility.

This does require trustee to ensure that their image is updated and kept in sync in https://github.com/confidential-containers/trustee/commits/main/kbs/config/kubernetes/base/kustomization.yaml, particularly on release boundaries. @Xynnn007 - do you think this is a fair ask of the community community - that https://github.com/confidential-containers/trustee/commits/main/kbs/config/kubernetes/base/kustomization.yaml image content is pinned and updated when significant features/releases are added?
