### ISSUE TITLE
Exploring a more graceful solution to use Sealed Secret as volume

### ISSUE THREAD

**Issue by ChengyuZhu6** [kata-containers/kata-containers#10398]
## Description:
Our current implementation (https://github.com/kata-containers/kata-containers/pull/10363) of Sealed Secrets as volume works, but we’ve noticed a limitation that may affect usability in certain scenarios. Specifically, there is no straightforward way for the kata-agent to determine whether a mount is related to a sealed secret.

To address this, we have two options:

1. Volume name with the prefix `sealed-secret`.
    - Pros: The secret can be mounted in any location the user desires.
    - Cons: This requires code changes to the shim, which would need to detect the `sealed-secret` prefix and add a `/sealed` prefix to the mount destination, marking it as a Sealed Secret mount.
    - Example:
```yaml
volumeMounts:
        - name: sealed-secret-volume
          mountPath: "/run/unsealed-secret"
volumes:
    - name: sealed-secret-volume
      secret:
        secretName: secret
```
 
2. Mount path with the prefix “/sealed”:
    - Pros: No changes are needed in the shim.
    There are two ways to handle the mount path:
        1. [**_Current Implementation_**] Secret in a specific location starting with `/sealed` (e.g. `/sealed/run/unsealed-secret`)  
                - Pros: Aligns with the value of `mountPath`.
                - Cons: May not be ideal for existing workloads expecting secrets in a location that doesn’t start with /sealed.
        2. Secret in a specific location stripping "/sealed" prefix (e.g. `/run/unsealed-secret`)
               - Pros: This approach can be more suitable for existing workloads.
               - Cons: Potential discrepancy between the actual path (`/run/unsealed-secret`) and the mount path (`/sealed/run/unsealed-secret`) set in the deployment.
     - Example:
```yaml
volumeMounts:
        - name: secret-volume
          mountPath: "/sealed/run/unsealed-secret"
volumes:
    - name: secret-volume
      secret:
        secretName: secret
```

Details in the previous discussion https://github.com/kata-containers/kata-containers/pull/10363#discussion_r1781263808_, Thanks for the comments from @fitzthum and @stevenhorsman.

Welcome any thoughts or suggestions on it. Please share your ideas here.
