### ISSUE TITLE
Large container image deploy failed for kata-qemu-tdx runtime

### ISSUE THREAD

**Issue by qzheng527** [kata-containers/kata-containers#10567]
# Get your issue reviewed faster
I tried CoCo (kata-qemu-tdx) in My TDX server.
It worked for small size container images, such as busybox, nginx.
But it failed for apache/spark:3.5.3 or mysql:8.4 whose size was bigger than 100MB. 
Here was my test yaml.
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cc-test
  name: cc-test
  annotations:
    io.containerd.cri.runtime-handler: kata-qemu-tdx
spec:
  containers:
  - image: <test containre image>
    name: cc-test
    imagePullPolicy: Always
    command:
    - sh
    - "-c"
    - |
        sleep 10000
    resources:
      limits:
        cpu: "4"
        memory: 16Gi
  runtimeClassName: kata-qemu-tdx
```

# Description of problem

For mysql:8.4, it failed with log as below.
![image](https://github.com/user-attachments/assets/659de0bb-c6f1-4685-94af-d532487194fc)

But for spark, it failed with different reason.
![image](https://github.com/user-attachments/assets/d781d57c-37ba-4cc1-bed7-830527d0f43c)

I checked the guest CVM by kata-runtime , the memory size was 16GB.

# Expected result

It should work for any size of container images.

# Further information
I installed the CoCo (Kata) through CoCo operator.
I also tried CoCo trusted ephemeral storage way, failed again, raised in CoCo [issue](https://github.com/confidential-containers/confidential-containers/issues/265) 

My environment:
HW: Intel TDX
host OS: Ubuntu 24.04
K8S version: 1.31
Kata: 3.10.1
CoCo Operator: v0.10.0

# Kata Containers survey

Please consider taking the survey to help us help you: https://openinfrafoundation.formstack.com/forms/kata_containers_user_survey
