### ISSUE TITLE
runtime: Python recursion error in kata-qemu + nydus-snapshotter while importing ml_dtypes library

### ISSUE THREAD

**Issue by JakubLedworowski** [kata-containers/kata-containers#10571]
# Description of problem

1. Prepare Intel platform with TDX enabled and kubernetes cluster
3. Install kata-containers with kata-qemu-tdx runtime classes v3.11.0
4. Prepare the following pod definitions as `python-simple.yaml`:

  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: python-ml-dtypes-td-small-base
  spec:
    runtimeClassName: kata-qemu-tdx
    containers:
      - name: python-container
        imagePullPolicy: Always
        image: quay.io/jakub_ledworowski/python-test:small-base
        command: ["/bin/sh", "-c", "python -c 'import ml_dtypes' && tail -f /dev/null"]
    restartPolicy: Never
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    name: python-ml-dtypes-td-small-base-langchain
  spec:
    runtimeClassName: kata-qemu-tdx
    containers:
      - name: python-container
        imagePullPolicy: Always
        image: quay.io/jakub_ledworowski/python-test:small-base-langchain
        command: ["/bin/sh", "-c", "python -c 'import ml_dtypes' && tail -f /dev/null"]
    restartPolicy: Never
  ```

4. Deploy:

    `kubectl apply -f python-simple.yaml`

# Expected result

Both pods are started.

# Actual result

First pod `python-ml-dtypes-td-small-base` starts but the second one fails to start due to recursion error:

```text
Error: File "/home/user/.local/lib/python3.11/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype arg1 = dtype(arg1).type ^^^^^^^^^^^ 
File "/home/user/.local/lib/python3.11/site-packages/numpy/core/_dtype.py", line 46, in repr arg_str = _construction_repr(dtype, include_align=False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/home/user/.local/lib/python3.11/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr return _scalar_str(dtype, short=short) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/home/user/.local/lib/python3.11/site-packages/numpy/core/_dtype.py", line 104, in _scalar_str byteorder = _byte_order_str(dtype) ^^^^^^^^^^^^^^^^^^^^^^ 
File "/home/user/.local/lib/python3.11/site-packages/numpy/core/_dtype.py", line 163, in _byte_order_str swapped = np.dtype(int).newbyteorder('S') ^^^^^^^^^^^^^ 
RecursionError: maximum recursion depth exceeded while calling a Python object
```

# Further information

## How to build the image

Here is the Dockerfile used to build both images (I already added some debugging tools to the base image):

```Dockerfile
FROM python:3.11-slim AS small-base

RUN apt-get update && apt-get install -y gdb strace valgrind lsof htop curl wget dstat iftop sysstat && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash user

USER user
ENV PATH="$PATH:/home/user/.local/bin"
ENV PYTHONPATH="/home/user"

RUN pip install ml-dtypes

WORKDIR /home/user


FROM small-base AS small-base-langchain

RUN pip install --no-cache-dir langchain==0.3.6

WORKDIR /home/user
```

Commands to build:

```bash
docker build -t python-test:small-base -f Dockerfile . --target small-base
docker build -t python-test:small-base-langchain -f Dockerfile . --target small-base-langchain
```

## Parameters

Tested host OS: Ubuntu 24.04
Kernel: 6.8.0-1010-intel
Kata runtime installed with CoCo: v0.10.0
Kata runtime: 3.11.0

## Tested scenarios

`kata-qemu-tdx` / `kata-qemu-coco-dev` - fails
`kata-qemu-tdx` / `kata-qemu-coco-dev` with resources increased to 8 cpu / 24 GiB memory - fails
`kata-qemu` - works
[Standalone TD](https://github.com/canonical/tdx?tab=readme-ov-file#6-boot-td) - works

**Comment by fidencio** [comment]
> * Install kata-containers with kata-qemu-tdx runtime classes v3.9.0

Can you please give it a try on the latest 3.11.0 release and tell us whether the problem still happens?
Kata Containers does not provide any kind of support on previous releases, thus it's a must to always (try to, at least) have the problem reproduced with the latest one.

**Comment by JakubLedworowski** [comment]
> > * Install kata-containers with kata-qemu-tdx runtime classes v3.9.0
> 
> Can you please give it a try on the latest 3.11.0 release and tell us whether the problem still happens? Kata Containers does not provide any kind of support on previous releases, thus it's a must to always (try to, at least) have the problem reproduced with the latest one.

Tested with 3.11.0 and unfortunately it still fails.
I updated the issue description with this version.

**Comment by fidencio** [comment]
Okay, can you also check whether you face the same issue with the ` kata-qemu-coco-dev`  runtimeclass?

We need to understand that the closest equivalent of the kata-qemu-$tee is **not** `kata-qemu` , but rather ` kata-qemu-coco-dev`, and from there we can start narrowing down what can be causing the issue.

**Comment by JakubLedworowski** [comment]
kata-qemu-coco-dev - fails

**Comment by fidencio** [comment]
> kata-qemu-coco-dev - fails

It makes me think it's related to the amount of memory you've allocated to your VM, then.

**Comment by JakubLedworowski** [comment]
Even with increasing the resources to this big value does not help and the error is the same both for `kata-qemu-tdx` and `kata-qemu-coco-dev`:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: python-ml-dtypes-td-small-base
  annotations:
    io.katacontainers.config.runtime.create_container_timeout: "360"
spec:
  runtimeClassName: kata-qemu-tdx
  containers:
    - name: python-container
      imagePullPolicy: Always
      image: quay.io/jakub_ledworowski/python-test:small-base
      command: ["/bin/sh", "-c", "python -c 'import ml_dtypes' && tail -f /dev/null"]
      resources:
        limits:
          cpu: "8"
          memory: 24Gi
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: python-ml-dtypes-td-small-base-langchain
  annotations:
    io.katacontainers.config.runtime.create_container_timeout: "360"
spec:
  runtimeClassName: kata-qemu-tdx
  containers:
    - name: python-container
      imagePullPolicy: Always
      image: quay.io/jakub_ledworowski/python-test:small-base-langchain
      command: ["/bin/sh", "-c", "python -c 'import ml_dtypes' && tail -f /dev/null"]
      resources:
        limits:
          cpu: "8"
          memory: 24Gi
  restartPolicy: Never
---
```
