### ISSUE TITLE
Unstable test result for trusted storage on s390x

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/kata-containers#10651]
# Description of problem

Since a k8s cluster creation method was switched from k3s to kubeadm, a test `Test we can pull an image inside the guest using trusted storage` for `run-k8s-tests-on-zvsi / run-k8s-tests (nydus, qemu-coco-dev, kubeadm)` hasn't been yielding consistent results. It fails approximately 2 out of 10 times with the following error:

```
# Error from server: error when creating "/tmp/bats-run-230OvB/file/0/trusted-storage.yaml.in.8KY": etcdserver: request timed out
```

or 

```
# Error from server (InternalError): error when creating "/tmp/bats-run-ijwqhm/file/0/trusted-storage.yaml.in.WHU": Internal error occurred: resource quota evaluation timed out
```

This issue needs to be investigated and resolved to stabilize the test, so the workflow can be reinstated as a required job.

**Comment by BbolroC** [comment]
Increased the etcd timeout in kubeadm.conf:

```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    etcd-timeout: "15s"
```
Let's see how the CI will go for next 10 days.

**Comment by BbolroC** [comment]
A kubeadm cluster uses etcd while a k3s cluster uses SQLite, which is well configured for a light loaded condition. In this regard, the timeout could be caused by insufficient resources assignment for a etcd pod. The current default assignment is as follows:

```yaml
spec:
  containers:
  - name: etcd
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
```
I've doubled the request. Let's see what will happen for the next 10 days.
