### ISSUE TITLE
Some container image errors occurred with kata-qemu-tdx runtime

### ISSUE THREAD

**Issue by zzylydx** [kata-containers/kata-containers#10657]
### Description of the issue

I have installed CoCo v0.11.0 in my TDX server. But when I run it with `kata-qemu-tdx` runtimeClass several times, and then run it with `kata-qemu` runtimeClass and got this error：

```bash
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  13s                default-scheduler  Successfully assigned default/nginx to coco
  Normal   Pulled     12s (x2 over 12s)  kubelet            Container image "docker.m.daocloud.io/bitnami/nginx:1.22.0" already present on machine
  Warning  Failed     12s (x2 over 12s)  kubelet            Error: failed to create containerd container: error unpacking image: failed to extract layer sha256:877c59cba30815073ef56303b1b951f0e3e656a4c6170091e66bf53a1973c0c8: failed to get reader from content store: content digest sha256:1d8866550bdd02551d6874e99aa828dd95b7434c6a25168765d46251cc230469: not found
```

My `.yaml` looks like this:

* `kata-qemu-tdx`

  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: nginx
    name: nginx
    annotations:
      io.containerd.cri.runtime-handler: kata-qemu-tdx
  spec:
    containers:
    - image: docker.m.daocloud.io/bitnami/nginx:1.22.0
      imagePullPolicy: Always
      name: nginx
    dnsPolicy: ClusterFirst
    runtimeClassName: kata-qemu-tdx 
  ```
* `kata-qemu`

  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: nginx
    name: nginx
    annotations:
      io.containerd.cri.runtime-handler: kata-qemu
  spec:
    containers:
    - image: docker.m.daocloud.io/bitnami/nginx:1.22.0
      name: nginx
      securityContext:
         privileged: true
    dnsPolicy: ClusterFirst
    runtimeClassName: kata-qemu
  ```

Then, we used the same image as the private image library to start the `kata-qemu-tdx`pod,

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  annotations:
    io.containerd.cri.runtime-handler: kata-qemu-tdx
spec:
  containers:
  - image: xx.xx.x.xx:5000/docker.monlor.com/bitnami/nginx:1.22.0 
    imagePullPolicy: Always
    name: nginx
  dnsPolicy: ClusterFirst
  runtimeClassName: kata-qemu-tdx 
```

but the following problems occurred:

```yaml
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  34s                default-scheduler  Successfully assigned default/nginx to coco
  Normal   Pulled     29s                kubelet            Successfully pulled image "xx.xx.x.xx:5000/docker.monlor.com/bitnami/nginx:1.22.0" in 16ms (16ms including waiting). Image size: 39261805 bytes.
  Normal   Pulled     27s                kubelet            Successfully pulled image "xx.xx.x.xx:5000/docker.monlor.com/bitnami/nginx:1.22.0" in 17ms (17ms including waiting). Image size: 39261805 bytes.
  Normal   Pulling    10s (x3 over 29s)  kubelet            Pulling image "xx.xx.x.xx:5000/docker.monlor.com/bitnami/nginx:1.22.0"
  Normal   Created    10s (x3 over 29s)  kubelet            Created container nginx
  Warning  Failed     10s (x3 over 28s)  kubelet            Error: failed to create containerd task: failed to create shim task: failed to pull manifest error sending request for url (https://xx.xx.x.xx:5000/v2/docker.monlor.com/bitnami/nginx/manifests/1.22.0)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>: unknown
  Normal   Pulled   10s               kubelet  Successfully pulled image "xx.xx.x.xx:5000/docker.monlor.com/bitnami/nginx:1.22.0" in 13ms (13ms including waiting). Image size: 39261805 bytes.
  Warning  BackOff  9s (x3 over 26s)  kubelet  Back-off restarting failed container nginx in pod nginx_default(f8009e74-a6d1-4ff2-bdb1-f9e37d6748c3)
```

Then we used the original image to start the `kata-qemu-tdx` pod again, and an error occurred:

```yaml
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  15m                default-scheduler  Successfully assigned default/nginx to coco
  Normal   Pulled     15m                kubelet            Successfully pulled image "docker.m.daocloud.io/bitnami/nginx:1.22.0" in 161ms (161ms including waiting). Image size: 39261805 bytes.
  Normal   Pulled     15m                kubelet            Successfully pulled image "docker.m.daocloud.io/bitnami/nginx:1.22.0" in 152ms (152ms including waiting). Image size: 39261805 bytes.
  Normal   Pulled     15m                kubelet            Successfully pulled image "docker.m.daocloud.io/bitnami/nginx:1.22.0" in 128ms (128ms including waiting). Image size: 39261805 bytes.
  Warning  Failed     14m (x4 over 15m)  kubelet            Error: failed to create containerd task: failed to create shim task: failed to pull manifest error sending request for url (https://10.50.1.95:5000/v2/docker.monlor.com/bitnami/nginx/manifests/1.22.0)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>: unknown
  Normal   Pulled   14m                 kubelet  Successfully pulled image "docker.m.daocloud.io/bitnami/nginx:1.22.0" in 117ms (117ms including waiting). Image size: 39261805 bytes.
  Normal   Pulling  14m (x5 over 15m)   kubelet  Pulling image "docker.m.daocloud.io/bitnami/nginx:1.22.0"
  Normal   Created  14m (x5 over 15m)   kubelet  Created container nginx
  Normal   Pulled   14m                 kubelet  Successfully pulled image "docker.m.daocloud.io/bitnami/nginx:1.22.0" in 119ms (119ms including waiting). Image size: 39261805 bytes.
  Warning  BackOff  20s (x71 over 15m)  kubelet  Back-off restarting failed container nginx in pod nginx_default(43d6e259-b43f-4c21-aa40-4969c14c980a)
```

At the same time, when using coco, there are always errors about container images. For example, after reinstalling coco, the following error will appear when starting `kata-qemu-tdx` pod:

```bash
kubelet  Error: failed to create containerd container: error unpacking image: failed to extract layer sha256:xxx: not found
```

Is there any best practice guidance for `kata-qemu-tdx` runtimeClass container images? Or what are the reasons for these problems?

Thanks.

### More information

I have installed kata through the CoCo operator (v0.11.0).
HW: `Intel TDX`

OS: `Ubuntu 24.04`

containerd: `1.7.22`

k8s: `v1.30.6`

kernel: `6.8.0-1013-intel`
