### ISSUE TITLE
CoCo pod insufficient disk space with kata-qemu-tdx runtime

### ISSUE THREAD

**Issue by zzylydx** [kata-containers/kata-containers#10679]
### Description of the issue

I have installed CoCo v0.11.0 in my TDX server.

When testing a large data volume task with `kata-qemu-tdx` runtimeClass, I found that the disk space in the coco pod was very small, causing the task to report an exception. How can I increase the disk space in the coco pod?

* sample yml：

  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: nginx
    name: nginx
    annotations:
      io.containerd.cri.runtime-handler: kata-qemu-tdx
  spec:
    containers:
    - image: docker.m.daocloud.io/bitnami/nginx:1.22.0
      imagePullPolicy: Always
      name: nginx
    dnsPolicy: ClusterFirst
    runtimeClassName: kata-qemu-tdx 
  ```
* disk space:

  ```shell
  I have no name!@nginx:/app$ df -hl
  Filesystem      Size  Used Avail Use% Mounted on
  overlay         928M  109M  820M  12% /
  tmpfs            64M     0   64M   0% /dev
  tmpfs           928M     0  928M   0% /sys/fs/cgroup
  tmpfs           928M  109M  820M  12% /tmp
  shm             928M     0  928M   0% /dev/shm
  ```

### More information

I have installed kata through the CoCo operator (v0.11.0).
HW: `Intel TDX`

OS: `Ubuntu 24.04`

containerd: `1.7.22`

k8s: `v1.30.6`

kernel: `6.8.0-1013-intel`
