### ISSUE TITLE
Writing to an emptyDir causes virtiofsd to crash when using kernel 6.12.8

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#10706]
While trying to bump the kernel to 6.12.8, I've spend some time trying to narrow down a regression that has been haunting us for some time, and can be seen also in the 6.6.x update temptatives.

reproducer:
```
apiVersion: v1
kind: Pod
metadata:
  name: sharevol
spec:
  runtimeClassName: kata-qemu
  restartPolicy: Never
  securityContext:
    runAsUser: 1001
    fsGroup: 123
  containers:
  - name: mounttest-container
    image: quay.io/fidencio/agnhost:debug
    volumeMounts:
      - name: emptydir-volume
        mountPath: /test-volume
  volumes:
  - name: emptydir-volume
    emptyDir: {}
```

steps to reproduce:
1. Exec into the created pod
2. Do a `touch /test-volume/foo`

This works without any issue with the current 6.1.x kernel, but has been preventing us to bump to a newer kernel since then.

Notes:
* I've tested with the latest virtiofsd, and that doesn't avoid the issue to happen
* strace'ing virtiofsd shows it coredumps

cc @gkurz, and please, loop in whoever you think that would be able to help on this one.
