### ISSUE TITLE
Cannot port forward with kubectl

### ISSUE THREAD

**Issue by eden881** [kata-containers/kata-containers#10843]
I have kata running on a raspberry pi with k3s.
Everything is going smooth so far - I've used the containerd version that ships with k3s and it works with kata with no problems.

I'm trying to forward a port through kubectl like it normally would:
```
$ kubectl port-forward deploy/nginx-deployment 1234:80
```
```
Forwarding from 127.0.0.1:1234 -> 80
Forwarding from [::1]:1234 -> 80
```

But when I attempt to make the connection, it fails as if the port is closed:
```
E0206 11:31:22.570388   11312 portforward.go:424] "Unhandled Error" err="an error occurred forwarding 1234 -> 80: error forwarding port 80 to pod dbcecb0eb2f43956132f93fb18f382f3223568ddb13da9a0e5291b80b02fe854, uid : failed to execute portforward in network namespace \"/var/run/netns/cni-b3e3bd90-330d-4e65-f96b-71f54a723088\": failed to connect to localhost:80 inside namespace \"dbcecb0eb2f43956132f93fb18f382f3223568ddb13da9a0e5291b80b02fe854\", IPv4: dial tcp4 127.0.0.1:80: connect: connection refused IPv6 dial tcp6 [::1]:80: connect: connection refused "
error: lost connection to pod
```

I'm not sure what the issue is. `exec`ing into the container works.
This is my deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      runtimeClassName: kata
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
```
