### ISSUE TITLE
ci: Improve performance testing

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#10875]
We currently have the metrics tests (although they are not running at time of writing) which does some level of regression testing, but isn't use case driven. On the AC meeting 2025-02-06 we had a discussion about an improved version and came up with some ideas for a new improved performance testing capability.

### Outcomes
 There are some outcomes we want from it:
- The ability to detect serious performance regression on PRs/nightly tests
- The ability to collect some benchmarks for particular use-cases e.g. pod start-up time (what else?)

### Use cases
?

### Requirements
- In order to have reliable results for regression testing we need a dedicated bare-metal runner. The current runner is Equinix based, but that is going away at some point?
- As we can't give concrete benchmarks as they are quite specific to user environments, rather than trying to publish our own benchmarks, should we instead focus on creating a good user experience with a set of scripts/tests such that user can easily gather their own performance figures?

**Comment by RuoqingHe** [comment]
Since Kata-Containers is based on virtualization, so the `hypervisor` we have chosen will in a way affect the outcome of our test, and `runtime` too (and different kernel as well).

Is this performance test will be based on top of something like a matrix (a gha matrix) like:

```yaml
matrix:
    hypervisor:
        - cloud-hypervisor
        - dragonball
        - firecracker
        - qemu
        - stratovirt
        ...
    runtime:
        - runtime
        - runtime-rs
    ...
```
