### ISSUE TITLE
Unexpected Attestation Behavior with Sealed Secrets for IBM SE

### ISSUE THREAD

**Issue by BbolroC** [kata-containers/kata-containers#11011]
# Description of problem

### Manifest file
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-cc
  annotations:
    io.katacontainers.config.hypervisor.kernel_params: agent.guest_components_procs=confidential-data-hub agent.aa_kbc_params=cc_kbc::http://172.23.236.42:31433
spec:
  runtimeClassName: kata
  containers:
    - name: busybox
      image: quay.io/prometheus/busybox:latest
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          env
          echo "PROTECTED_SECRET = $PROTECTED_SECRET"
          echo "UNPROTECTED_SECRET = $UNPROTECTED_SECRET"
          sleep 1000
      # Expose secret data Containers through environment.
      env:
        - name: PROTECTED_SECRET
          valueFrom:
            secretKeyRef:
              name: sealed-secret
              key: secret
        - name: UNPROTECTED_SECRET
          valueFrom:
            secretKeyRef:
              name: not-sealed-secret
              key: secret
  nodeName: a314lp42
```

### Test result

- Pod state: running
- Pod log:
```
root@a314lp42:~# kubectl logs -f -n kata-containers-k8s-tests secret-test-pod-cc
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.96.0.1:443
HOSTNAME=secret-test-pod-cc
SHLVL=1
HOME=/root
PROTECTED_SECRET=unsealed_secret
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
UNPROTECTED_SECRET=not_sealed_secret
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_SERVICE_HOST=10.96.0.1
PWD=/
PROTECTED_SECRET = unsealed_secret
UNPROTECTED_SECRET = not_sealed_secret
```

- KBS log
```
[2025-03-11T17:22:50Z INFO  actix_web::middleware::logger] 10.244.0.1 "POST /kbs/v0/auth HTTP/1.1" 200 2366 "-" "attestation-agent-kbs-client/0.1.0" 0.001469
[2025-03-11T17:22:50Z WARN  verifier::se] IBM SE verifier does not support verify report data hash, will ignore the input `report_data`.
[2025-03-11T17:22:50Z INFO  verifier::se::ibmse] IBM SE verify API called.
[2025-03-11T17:22:50Z INFO  attestation_service] Se Verifier/endorsement check passed.
[2025-03-11T17:22:50Z INFO  actix_web::middleware::logger] 10.244.0.1 "POST /kbs/v0/attest HTTP/1.1" 200 4970 "-" "attestation-agent-kbs-client/0.1.0" 0.029971
[2025-03-11T17:22:50Z INFO  actix_web::middleware::logger] 10.244.0.1 "GET /kbs/v0/resource/default/sealed-secret/test HTTP/1.1" 200 509 "-" "attestation-agent-kbs-client/0.1.0" 0.001420
```

### Manifest file

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-cc
  annotations:
    io.katacontainers.config.hypervisor.kernel_params: agent.guest_components_procs=confidential-data-hub agent.aa_kbc_params=cc_kbc::http://172.23.236.42:31433
spec:
  runtimeClassName: kata
  containers:
    - name: busybox
      image: quay.io/prometheus/busybox:latest
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          unseal_data=$(cat /sealed/secret-value/secret)
          not_sealed_data=$(cat /sealed/not-sealed-secret-value/secret)
          echo "PROTECTED_SECRET = $unseal_data"
          echo "UNPROTECTED_SECRET = $not_sealed_data"
          sleep 1000
      volumeMounts:
        - name: sealed-secret-volume
          mountPath: "/sealed/secret-value"
        - name: not-sealed-secret-volume
          mountPath: "/sealed/not-sealed-secret-value"
  volumes:
    - name: sealed-secret-volume
      secret:
        secretName: sealed-secret
    - name: not-sealed-secret-volume
      secret:
        secretName: not-sealed-secret
  nodeName: a314lp42
```

### Test result

- Pod state: running
- Pod log
```
root@a314lp42:~# kubectl logs -f -n kata-containers-k8s-tests secret-test-pod-cc
PROTECTED_SECRET = sealed.fakejwsheader.eyJ2ZXJzaW9uIjoiMC4xLjAiLCJ0eXBlIjoidmF1bHQiLCJuYW1lIjoia2JzOi8vL2RlZmF1bHQvc2VhbGVkLXNlY3JldC90ZXN0IiwicHJvdmlkZXIiOiJrYnMiLCJwcm92aWRlcl9zZXR0aW5ncyI6e30sImFubm90YXRpb25zIjp7fX0.fakesignature
UNPROTECTED_SECRET = not_sealed_secre
```

- No KBS log

### Manifest file

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-cc
  annotations:
    io.katacontainers.config.hypervisor.kernel_params: agent.guest_components_procs=confidential-data-hub agent.aa_kbc_params=cc_kbc::http://172.23.236.42:31433
spec:
  runtimeClassName: kata
  containers:
    - name: busybox
      image: quay.io/prometheus/busybox:latest
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          unseal_data=$(cat /sealed/secret-value/secret)
          not_sealed_data=$(cat /sealed/not-sealed-secret-value/secret)
          echo "PROTECTED_SECRET from file = $unseal_data"
          echo "UNPROTECTED_SECRET from file = $not_sealed_data"
          echo "PROTECTED_SECRET from env = $PROTECTED_SECRET"
          echo "UNPROTECTED_SECRET from env = $UNPROTECTED_SECRET"
          sleep 1000
      volumeMounts:
        - name: sealed-secret-volume
          mountPath: "/sealed/secret-value"
        - name: not-sealed-secret-volume
          mountPath: "/sealed/not-sealed-secret-value"
      env:
        - name: PROTECTED_SECRET
          valueFrom:
            secretKeyRef:
              name: sealed-secret
              key: secret
        - name: UNPROTECTED_SECRET
          valueFrom:
            secretKeyRef:
              name: not-sealed-secret
              key: secret
  volumes:
    - name: sealed-secret-volume
      secret:
        secretName: sealed-secret
    - name: not-sealed-secret-volume
      secret:
        secretName: not-sealed-secret
  nodeName: a314lp42
```

### Test result

- Pod state: running
- Pod log
```
root@a314lp42:~# kubectl logs -f -n kata-containers-k8s-tests secret-test-pod-cc
PROTECTED_SECRET from file = sealed.fakejwsheader.eyJ2ZXJzaW9uIjoiMC4xLjAiLCJ0eXBlIjoidmF1bHQiLCJuYW1lIjoia2JzOi8vL2RlZmF1bHQvc2VhbGVkLXNlY3JldC90ZXN0IiwicHJvdmlkZXIiOiJrYnMiLCJwcm92aWRlcl9zZXR0aW5ncyI6e30sImFubm90YXRpb25zIjp7fX0.fakesignature
UNPROTECTED_SECRET from file = not_sealed_secret
PROTECTED_SECRET from env = unsealed_secret
UNPROTECTED_SECRET from env = not_sealed_secret
```

- KBS log
```
[2025-03-11T17:42:16Z INFO  actix_web::middleware::logger] 10.244.0.1 "POST /kbs/v0/auth HTTP/1.1" 200 2366 "-" "attestation-agent-kbs-client/0.1.0" 0.001617
[2025-03-11T17:42:16Z WARN  verifier::se] IBM SE verifier does not support verify report data hash, will ignore the input `report_data`.
[2025-03-11T17:42:16Z INFO  verifier::se::ibmse] IBM SE verify API called.
[2025-03-11T17:42:16Z INFO  attestation_service] Se Verifier/endorsement check passed.
[2025-03-11T17:42:16Z INFO  actix_web::middleware::logger] 10.244.0.1 "POST /kbs/v0/attest HTTP/1.1" 200 4970 "-" "attestation-agent-kbs-client/0.1.0" 0.030025
[2025-03-11T17:42:16Z INFO  actix_web::middleware::logger] 10.244.0.1 "GET /kbs/v0/resource/default/sealed-secret/test HTTP/1.1" 200 509 "-" "attestation-agent-kbs-client/0.1.0" 0.001382
```

# Expected result

The case 2 should go through the attestation (i.e. KBS should print out a similar attestation log messages). The pod log should look like:

```
root@a314lp42:~# kubectl logs -f -n kata-containers-k8s-tests secret-test-pod-cc
PROTECTED_SECRET = unsealed_secret
UNPROTECTED_SECRET = not_sealed_secre
```

I was surprised a pod is running without attestation. (is it bypassed or something? 🤔 ) Interestingly, it looks like the attestation is only triggered only if a `env` section is specified.
