### ISSUE TITLE
Container fails to start when when filesystem object already exists in specific cases

### ISSUE THREAD

**Issue by solidDoWant** [kata-containers/kata-containers#11349]
# Description of problem

When running in Kubernetes, containers will fail to start under specific circumstances. When a container image contains a filesystem object of one type (say a link), and there is a volume mounted with a filesystem object of a **different type** (say a directory) at the same path, the container will fail to start. The exact error varies depending on the filesystem object type in the mounted volume.

Here is a k8s deployment to reproduce the issue:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kata-repro-issue
spec:
  selector:
    matchLabels:
      app: kata-repro-issue
  template:
    metadata:
      labels:
        app: kata-repro-issue
    spec:
      runtimeClassName: kata
      volumes:
        - name: tzdata-volume
          emptyDir: {}
      initContainers:
        - name: populate-tzdata-volume
          image: ubuntu:24.04
          env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
          command:
            - sh
            - -c
            - apt-get update && apt-get install -y tzdata
          volumeMounts: &volume_mounts
            - name: tzdata-volume
              mountPath: /etc/localtime
            - name: tzdata-volume
              mountPath: /usr/share/zoneinfo
      containers:
        - name: kata-repro-issue
          # This is just the ubuntu:24.04 image with `apt-get update && apt-get install -y tzdata` run in it.
          image: ghcr.io/soliddowant/kata-repro-issue:latest
          command:
            - sleep
            - "9999"
          volumeMounts: *volume_mounts
```

This will cause the container to fail to start with `Error: failed to create containerd task: failed to create shim task: ENOTDIR: Not a directory`. In this case, the filesystem object type in the container is a symlink, and the mount is a directory.

Relevant kubelet log entries:
```
10.3.1.2: {"ts":1748642728271.8877,"caller":"internal/log.go:32","msg":"StartContainer from runtime service failed","containerID":"c882e9443e91eaeec1b0b965bf27153378b67b49bab50ca78e4efa6ad177cbb3","err":"rpc error: code = Internal desc = failed to create containerd task: failed to create shim task: ENOTDIR: Not a directory"}
10.3.1.2: {"ts":1748642728271.982,"logger":"UnhandledError","caller":"kuberuntime/kuberuntime_manager.go:1341","msg":"Unhandled Error","err":"container &Container{Name:kata-repro-issue,Image:ghcr.io/soliddowant/kata-repro-issue:latest,Command:[sleep 9999],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:tzdata-volume,ReadOnly:false,MountPath:/etc/localtime,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:tzdata-volume,ReadOnly:false,MountPath:/usr/share/zoneinfo,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},VolumeMount{Name:kube-api-access-blxlr,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,RecursiveReadOnly:nil,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod kata-repro-issue-5574b947ff-9kgg4_media(f13465e5-7085-4e04-927c-aa0027601013): RunContainerError: failed to create containerd task: failed to create shim task: ENOTDIR: Not a directory"}
10.3.1.2: {"ts":1748642728273.1113,"caller":"kubelet/pod_workers.go:1301","msg":"Error syncing pod, skipping","pod":{"name":"kata-repro-issue-5574b947ff-9kgg4","namespace":"media"},"podUID":"f13465e5-7085-4e04-927c-aa0027601013","err":"failed to \"StartContainer\" for \"kata-repro-issue\" with RunContainerError: \"failed to create containerd task: failed to create shim task: ENOTDIR: Not a directory\"","errCauses":[{"error":"failed to \"StartContainer\" for \"kata-repro-issue\" with RunContainerError: \"failed to create containerd task: failed to create shim task: ENOTDIR: Not a directory\""}]}
10.3.1.2: {"ts":1748642728499.7656,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"09e1d5bb74871bce2fa37f14f578d767aab4592260c11d0c2b5237da7cfdbaea"}
10.3.1.2: {"ts":1748642728500.1096,"caller":"topologymanager/scope.go:117","msg":"RemoveContainer","v":0,"containerID":"c882e9443e91eaeec1b0b965bf27153378b67b49bab50ca78e4efa6ad177cbb3"}
```

CRI logs:

```
10.3.1.2: {"level":"info","msg":"Container d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507: CDI devices from CRI Config.CDIDevices: []","time":"2025-05-30T22:09:35.964980994Z"}
10.3.1.2: {"level":"info","msg":"CreateContainer within sandbox \"00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61\" for \u0026ContainerMetadata{Name:kata-repro-issue,Attempt:5,} returns container id \"d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507\"","time":"2025-05-30T22:09:35.979133057Z"}
10.3.1.2: {"level":"info","msg":"StartContainer for \"d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507\"","time":"2025-05-30T22:09:35.980220201Z"}
10.3.1.2: {"address":"unix:///run/containerd/s/34a78d03de32cc84e0d046e3b1de38652cc3f6c455f19c8b1140cf85ae504bbb","level":"info","msg":"connecting to shim d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507","protocol":"ttrpc","time":"2025-05-30T22:09:35.982550496Z","version":2}
10.3.1.2: time="2025-05-30T22:09:36.304682464Z" level=error msg="container create failed" container=d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507 error="rpc error: code = Internal desc = ENOTDIR: Not a directory" name=containerd-shim-v2 pid=152537 sandbox=00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61 source=virtcontainers subsystem=container
10.3.1.2: time="2025-05-30T22:09:36.304720253Z" level=warning msg="Could not umount" container=d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507 error="no such file or directory" host-path=/run/kata-containers/shared/sandboxes/00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61/mounts/d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507-90a7bda045660ccf-hosts name=containerd-shim-v2 pid=152537 sandbox=00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61 source=virtcontainers subsystem=container
10.3.1.2: time="2025-05-30T22:09:36.304748517Z" level=error msg="rollback failed unmountHostMounts()" container=d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507 error="no such file or directory" name=containerd-shim-v2 pid=152537 sandbox=00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61 source=virtcontainers subsystem=container
10.3.1.2: time="2025-05-30T22:09:36.304774575Z" level=warning error="no such file or directory" name=containerd-shim-v2 pid=152537 sandbox=00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61 share-dir=/run/kata-containers/shared/sandboxes/00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61/mounts/d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507/rootfs source=virtcontainers subsystem=mount
10.3.1.2: time="2025-05-30T22:09:36.304800387Z" level=warning msg="Could not remove container share dir" error="no such file or directory" name=containerd-shim-v2 pid=152537 sandbox=00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61 share-dir=/run/kata-containers/shared/sandboxes/00e7c72f42e267ac64b677df0d8b024084665a5e0b049aebf349aa0dfbdf4c61/mounts/d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507 source=virtcontainers subsystem=fs_share
10.3.1.2: {"error":"reading from a closed fifo","level":"error","msg":"Failed to pipe stdout of container \"d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507\"","time":"2025-05-30T22:09:36.307417376Z"}
10.3.1.2: {"error":"reading from a closed fifo","level":"error","msg":"Failed to pipe stderr of container \"d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507\"","time":"2025-05-30T22:09:36.307426873Z"}
10.3.1.2: {"error":"rpc error: code = Internal desc = failed to create containerd task: failed to create shim task: ENOTDIR: Not a directory","level":"error","msg":"StartContainer for \"d3f6ef8603517e9903b9d42a171964dee61a088385dfd4fe45e16cfc8045c507\" failed","time":"2025-05-30T22:09:36.315622895Z"}
```

# Expected result

The container should start

# Actual result

The container fails to start

# Further information

Unfortunately I cannot run the data collection script, as I'm running Kata on nodes without a root namespace shell or most dependencies (Talos).
