### ISSUE TITLE
Initdata/image pull | Get rid of image pull kernel cmdline configurations

### ISSUE THREAD

**Issue by Xynnn007** [kata-containers/kata-containers#11428]
At present, especially in the CoCo scenario, we are widely using Kernel Cmdline to pass some image pull configuration information for Pod.

For examples:
- [The registry auth](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats#L83). (Note that it's embedded [here](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/confidential_common.sh#L143))
- [The image security policy id](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/confidential_common.sh#L138)

These configurations are highly dynamic relative to the guest image/initrd. For some architectures, a change in the kernel cmdline means a change in the entire measurement, making it difficult to maintain a reference value.

The kernel cmdline reading functionalities were handled by kata-agent. In a recent PR of [moving image pull abilities from kata-agent to CDH](https://github.com/kata-containers/kata-containers/pull/11197), we deleted relative code from kata-agent, and moves it to the CDH for backward compability.

But now we have the initdata mechanism, and it's suitable for this kind of dynamic configuration to be handled by initdata and recorded in the remote attestation report. As for the original kernel cmdline items, they will appear in the CDH configuration file as configuration items.

Here are some excerpts from the configuration files (the [whole](https://github.com/confidential-containers/guest-components/blob/main/confidential-data-hub/example.config.toml)):
```toml
# If any image security policy would be used to control the image pulling
# like signature verification, this field is used to set the URI of the
# policy file.
#
# Now it supports two different forms:
# - `KBS URI`: the iamge security policy will be fetched from KBS.
# - `Local Path`: the security policy will be fetched from somewhere locally.
# e.g. `file:///etc/image-policy.json`.
#
# The policy follows the format of
# <https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md>.
#
# At the same time, some enhencements based on CoCo is used, that is the
# `keyPath` field can be filled with a KBS URI like `kbs:///default/key/1`
#
# By default this value is not set.
image_security_policy_uri = "kbs:///default/security-policy/test"
```

After inspiring discussions with @stevenhorsman, we hope to gradually abandon the reliance on kernel cmdline and use initdata in a gradual way. This includes several steps
- [ ] Create a new version of the tests that use initdata instead of kernel cmdlines for image pull settings to pass through the required settings
- [ ] Mark image pull configs of the kernel cmdline as deprecated and planned to be removed in a few months. At the meantime to collect feedbacks from the community.
- [ ] Remove the the CI tests that use kernel cmdline and the relative code in CDH. Fully get rid of kernel cmdline for image pull.

cc @fitzthum @ChengyuZhu6 @Apokleos @burgerdev

**Comment by fitzthum** [comment]
I think we may want to keep `aa_kbc_params` so that simple use cases (with secrets but without init-data) will still work, but I think we can remove everything else.

**Comment by Apokleos** [comment]
Yeah, agree, and initdata is a good way to do such dynamic configs passing work in sandbox level. 
I have a question, is cdh a consumer of initdata ?

**Comment by Xynnn007** [comment]
> I have a question, is cdh a consumer of initdata ?

The direct consumer is now the kata-agent, and kata-agent spilits the initdata into config files. One of them is CDH's config.

There is also another issue that wants to move the initdata handling logic out of kata-agent to keep the kata-agent clean and decoupled. https://github.com/issues/created?issue=kata-containers%7Ckata-containers%7C10980

**Comment by Apokleos** [comment]
> > I have a question, is cdh a consumer of initdata ?
> 
> The direct consumer is now the kata-agent, and kata-agent spilits the initdata into config files. One of them is CDH's config.
> 
> There is also another issue that wants to move the initdata handling logic out of kata-agent to keep the kata-agent clean and decoupled. [#10980](https://github.com/kata-containers/kata-containers/issues/10980)
>
Yeah, now kata-agent is indeed the direct consumer. According this issue's description, will cdh, aa and policy engine become direct consumer ?  And more, how image-rs make full use the power of initdata ?

**Comment by Xynnn007** [comment]
> According this issue's description, will cdh, aa and policy engine become direct consumer ?


Oh, I may have misunderstood what you meant by "direct consumer". What I mean "initdata" is the [toml](https://github.com/kata-containers/kata-containers/commit/2a4b1c4fb0be79456e60cc72af9feb9a86481416#diff-3e4130457a1848fa03969b9b61556d35d7c8c87e5b683f89dc581a691c679e97R44-R52) from host. [The issue](https://github.com/kata-containers/kata-containers/issues/10980) proposes a component to handle the toml. The toml contains some configurations in `data` for AA, CDH, etc. They direct consumes the configuretions.

As for image-rs configurations, they are all moved to CDH's configuration. That means, we can set "cdh.toml" section of initdata toml to include image pull relative configs. e.g. the following initdata toml
```toml
version = "0.1.0"
algorithm = "sha256"
[data]
"policy.rego" = '''
# Copyright (c) 2023 Microsoft Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

package agent_policy

default AddARPNeighborsRequest := true
default AddSwapRequest := true
default CloseStdinRequest := true
default CopyFileRequest := true
default CreateContainerRequest := true
default CreateSandboxRequest := true
default DestroySandboxRequest := true
default ExecProcessRequest := true
default GetMetricsRequest := true
default GetOOMEventRequest := true
default GuestDetailsRequest := true
default ListInterfacesRequest := true
default ListRoutesRequest := true
default MemHotplugByProbeRequest := true
default OnlineCPUMemRequest := true
default PauseContainerRequest := true
default PullImageRequest := true
default ReadStreamRequest := true
default RemoveContainerRequest := true
default RemoveStaleVirtiofsShareMountsRequest := true
default ReseedRandomDevRequest := true
default ResumeContainerRequest := true
default SetGuestDateTimeRequest := true
default SetPolicyRequest := true
default SignalProcessRequest := true
default StartContainerRequest := true
default StartTracingRequest := true
default StatsContainerRequest := true
default StopTracingRequest := true
default TtyWinResizeRequest := true
default UpdateContainerRequest := true
default UpdateEphemeralMountsRequest := true
default UpdateInterfaceRequest := true
default UpdateRoutesRequest := true
default WaitProcessRequest := true
default WriteStreamRequest := true
'''
"aa.toml" = '''
[token_configs]
[token_configs.kbs]
url = "https://1.1.1.1:8080"
id = "spiffe://domain/user2"
cert = """
-----BEGIN CERTIFICATE-----
MIIDpjCCAo6gAwIBAgIUcV4NZmtvyf4zHirQG04hbjmWwkAwDQYJKoZIhvcNAQEL
...
-----END CERTIFICATE-----

"""
'''

"cdh.toml" = '''
[kbc]
name = "cc_kbc"
url = "https://1.1.1.1:8080"
kbs_cert = """
-----BEGIN CERTIFICATE-----
MIIDpjCCAo6gAwIBAgIUcV4NZmtvyf4zHirQG04hbjmWwkAwDQYJKoZIhvcNAQEL
...
-----END CERTIFICATE-----

"""
[image]
# The maximum number of layers downloaded concurrently when
# pulling one specific image.
#
# This defaults to 3.
max_concurrent_layer_downloads_per_image = 3

# Sigstore config file URI for simple signing scheme.
#
# When `image_security_policy_uri` is set and `SimpleSigning` (signedBy) is
# used in the policy, the signatures of the images would be used for image
# signature validation. This policy will record where the signatures is.
#
# Now it supports two different forms:
# - `KBS URI`: the sigstore config file will be fetched from KBS,
# e.g. `kbs:///default/sigstore-config/test`.
# - `Local Path`: the sigstore config file will be fetched from somewhere locally,
# e.g. `file:///etc/simple-signing.yaml`.
#
# By default this value is not set.
sigstore_config_uri = "kbs:///default/sigstore-config/test"

# If any image security policy would be used to control the image pulling
# like signature verification, this field is used to set the URI of the
# policy file.
#
# Now it supports two different forms:
# - `KBS URI`: the iamge security policy will be fetched from KBS.
# - `Local Path`: the security policy will be fetched from somewhere locally.
# e.g. `file:///etc/image-policy.json`.
#
# The policy follows the format of
# <https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md>.
#
# At the same time, some enhencements based on CoCo is used, that is the
# `keyPath` field can be filled with a KBS URI like `kbs:///default/key/1`
#
# By default this value is not set.
image_security_policy_uri = "kbs:///default/security-policy/test"

# If any credential auth (Base) would be used to connect to download
# image from private registry, this field is used to set the URI of the
# credential file.
#
# Now it supports two different forms:
# - `KBS URI`: the registry auth will be fetched from KBS,
# e.g. `kbs:///default/credential/test`.
# - `Local Path`: the registry auth will be fetched from somewhere locally,
# e.g. `file:///etc/image-registry-auth.json`.
#
# By default this value is not set.
authenticated_registry_credentials_uri = "kbs:///default/credential/test"

# To support registries with self signed certs. This config item
# is used to add extra trusted root certifications. The certificates
# must be encoded by PEM.
#
# By default this value is not set.
extra_root_certificates = [
"""
-----BEGIN CERTIFICATE-----
MIIFTDCCAvugAwIBAgIBADBGBgkqhkiG9w0BAQowOaAPMA0GCWCGSAFlAwQCAgUA
oRwwGgYJKoZIhvcNAQEIMA0GCWCGSAFlAwQCAgUAogMCATCjAwIBATB7MRQwEgYD
VQQLDAtFbmdpbmVlcmluZzELMAkGA1UEBhMCVVMxFDASBgNVBAcMC1NhbnRhIENs
YXJhMQswCQYDVQQIDAJDQTEfMB0GA1UECgwWQWR2YW5jZWQgTWljcm8gRGV2aWNl
czESMBAGA1UEAwwJU0VWLU1pbGFuMB4XDTIzMDEyNDE3NTgyNloXDTMwMDEyNDE3
NTgyNlowejEUMBIGA1UECwwLRW5naW5lZXJpbmcxCzAJBgNVBAYTAlVTMRQwEgYD
VQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExHzAdBgNVBAoMFkFkdmFuY2Vk
IE1pY3JvIERldmljZXMxETAPBgNVBAMMCFNFVi1WQ0VLMHYwEAYHKoZIzj0CAQYF
K4EEACIDYgAExmG1ZbuoAQK93USRyZQcsyobfbaAEoKEELf/jK39cOVJt1t4s83W
XM3rqIbS7qHUHQw/FGyOvdaEUs5+wwxpCWfDnmJMAQ+ctgZqgDEKh1NqlOuuKcKq
2YAWE5cTH7sHo4IBFjCCARIwEAYJKwYBBAGceAEBBAMCAQAwFwYJKwYBBAGceAEC
BAoWCE1pbGFuLUIwMBEGCisGAQQBnHgBAwEEAwIBAzARBgorBgEEAZx4AQMCBAMC
AQAwEQYKKwYBBAGceAEDBAQDAgEAMBEGCisGAQQBnHgBAwUEAwIBADARBgorBgEE
AZx4AQMGBAMCAQAwEQYKKwYBBAGceAEDBwQDAgEAMBEGCisGAQQBnHgBAwMEAwIB
CDARBgorBgEEAZx4AQMIBAMCAXMwTQYJKwYBBAGceAEEBEDDhCejDUx6+dlvehW5
cmmCWmTLdqI1L/1dGBFdia1HP46MC82aXZKGYSutSq37RCYgWjueT+qCMBE1oXDk
d1JOMEYGCSqGSIb3DQEBCjA5oA8wDQYJYIZIAWUDBAICBQChHDAaBgkqhkiG9w0B
AQgwDQYJYIZIAWUDBAICBQCiAwIBMKMDAgEBA4ICAQACgCai9x8DAWzX/2IelNWm
ituEBSiq9C9eDnBEckQYikAhPasfagnoWFAtKu/ZWTKHi+BMbhKwswBS8W0G1ywi
cUWGlzigI4tdxxf1YBJyCoTSNssSbKmIh5jemBfrvIBo1yEd+e56ZJMdhN8e+xWU
bvovUC2/7Dl76fzAaACLSorZUv5XPJwKXwEOHo7FIcREjoZn+fKjJTnmdXce0LD6
9RHr+r+ceyE79gmK31bI9DYiJoL4LeGdXZ3gMOVDR1OnDos5lOBcV+quJ6JujpgH
d9g3Sa7Du7pusD9Fdap98ocZslRfFjFi//2YdVM4MKbq6IwpYNB+2PCEKNC7SfbO
NgZYJuPZnM/wViES/cP7MZNJ1KUKBI9yh6TmlSsZZOclGJvrOsBZimTXpATjdNMt
cluKwqAUUzYQmU7bf2TMdOXyA9iH5wIpj1kWGE1VuFADTKILkTc6LzLzOWCofLxf
onhTtSDtzIv/uel547GZqq+rVRvmIieEuEvDETwuookfV6qu3D/9KuSr9xiznmEg
xynud/f525jppJMcD/ofbQxUZuGKvb3f3zy+aLxqidoX7gca2Xd9jyUy5Y/83+ZN
bz4PZx81UJzXVI9ABEh8/xilATh1ZxOePTBJjN7lgr0lXtKYjV/43yyxgUYrXNZS
oLSG2dLCK9mjjraPjau34Q==
-----END CERTIFICATE-----
"""
]

# The path to store the pulled image layer data.
#
# This value defaults to `/run/kata-containers/image/`.
work_dir = "/run/kata-containers/image/"

[image.image_pull_proxy]

# HTTPS proxy that will be used to pull image
#
# By default this value is not set.
https_proxy = "http://127.0.0.1:5432"

# HTTP proxy that will be used to pull image
#
# By default this value is not set.
http_proxy = "http://127.0.0.1:5432"

# No proxy env that will be used to pull image.
#
# This will ensure that when we access the image registry with specified
# IPs, both `https_proxy` and `http_proxy` will not be used.
#
# If neither `https_proxy` nor `http_proxy` is not set, this field will do nothing.
#
# By default this value is not set.
no_proxy = "192.168.0.1,localhost"
'''

```
