### ISSUE TITLE
dragonball: Cannot attach a block volume to a pod

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#11465]
When trying to a attach a PVC which has `volumeMode: Block` specified dragonball fails with:
```sh
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               2s    default-scheduler  Successfully assigned default/dagger to runtime-rs
  Normal   SuccessfulMountVolume   2s    kubelet            MapVolume.MapPodDevice succeeded for volume "block-pv" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/block-pv"
  Normal   SuccessfulMountVolume   2s    kubelet            MapVolume.MapPodDevice succeeded for volume "block-pv" volumeMapPath "/var/lib/kubelet/pods/abcd56d7-e867-4b2a-b296-66f7854f789d/volumeDevices/kubernetes.io~local-volume"
  Warning  FailedCreatePodSandBox  1s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox "f4672509c81d269ef969475cceee6bcc01d980a0f0cabd0f6d2a55a8d6e42f97": failed to create containerd task: failed to create shim task: Others("failed to handle message create container\n\nCaused by:\n    0: handler rootfs\n    1: new share fs rootfs\n    2: mount rootfs from Mount { source: \"/var/lib/containerd/io.containerd.snapshotter.v1.blockfile/snapshots/283\", destination: \"\", fs_type: \"ext4\", options: [\"loop\", \"rw\"], device_id: None, host_shared_fs_path: None, read_only: false } to /run/containerd/io.containerd.runtime.v2.task/k8s.io/f4672509c81d269ef969475cceee6bcc01d980a0f0cabd0f6d2a55a8d6e42f97/rootfs\n    3: Invalid mount option: loop\n\nStack backtrace:\n   0: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context\n   1: resource::rootfs::share_fs_rootfs::ShareFsRootfs::new::{{closure}}\n   2: virt_container::container_manager::container::Container::create::{{closure}}\n   3: <virt_container::container_manager::manager::VirtContainerManager as common::container_manager::ContainerManager>::create_container::{{closure}}\n   4: runtimes::manager::RuntimeHandlerManager::handler_task_message::{{closure}}::{{closure}}\n   5: runtimes::manager::RuntimeHandlerManager::handler_task_message::{{closure}}\n   6: <service::task_service::TaskService as containerd_shim_protos::shim::shim_ttrpc_async::Task>::create::{{closure}}\n   7: <containerd_shim_protos::shim::shim_ttrpc_async::CreateMethod as ttrpc::asynchronous::utils::MethodHandler>::handler::{{closure}}\n   8: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll\n   9: ttrpc::asynchronous::server::HandlerContext::handle_msg::{{closure}}\n  10: <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll\n  11: <ttrpc::asynchronous::server::ServerReader as ttrpc::asynchronous::connection::ReaderDelegate>::handle_msg::{{closure}}::{{closure}}\n  12: tokio::runtime::task::core::Core<T,S>::poll\n  13: tokio::runtime::task::harness::Harness<T,S>::poll\n  14: tokio::runtime::scheduler::multi_thread::worker::Context::run_task\n  15: tokio::runtime::scheduler::multi_thread::worker::Context::run\n  16: tokio::runtime::context::runtime::enter_runtime\n  17: tokio::runtime::scheduler::multi_thread::worker::run\n  18: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll\n  19: tokio::runtime::task::core::Core<T,S>::poll\n  20: tokio::runtime::task::harness::Harness<T,S>::poll\n  21: tokio::runtime::blocking::pool::Inner::run\n  22: std::sys::backtrace::__rust_begin_short_backtrace\n  23: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  24: std::sys::pal::unix::thread::Thread::new::thread_start")
```

I'm using containerd 2.1.2, Kata Containers 3.18.0, and the default configuration shipped for dragonball.

This one may also be related to: https://github.com/kata-containers/kata-containers/issues/11464

**Comment by Apokleos** [comment]
Hey bro @fidencio you're using `volumeDevice` in pod yaml ?

**Comment by fidencio** [comment]
@Apokleos, yep, this is my pod yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dagger
spec:
  runtimeClassName: kata-rs
  volumes:
  - name: local-disk
    persistentVolumeClaim:
      claimName: block-pvc
  containers:
  - name: top
    image: quay.io/fidencio/top:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        sleep infinity
    securityContext:
      privileged: true
  - name: engine
    image: registry.dagger.io/engine:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        mkfs.xfs /dev/vsda;
        mkdir -p /var/lib/dagger;
        mount /dev/vsda /var/lib/dagger;
        exec /usr/local/bin/dagger-entrypoint.sh
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    volumeDevices:
    - name: local-disk
      devicePath: /dev/vsda
  restartPolicy: Never
```
