### ISSUE TITLE
2.0: vcpus are not properly utilized in the guest

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1156]
# Get your issue reviewed faster

To help us understand the problem more quickly, please do the following:

This is tested utilizing the binaries available directly from the 2.0.0 release page. ie:
$ wget https://github.com/kata-containers/kata-containers/releases/download/2.0.0/kata-static-2.0.0-x86_64.tar.xz
$ sudo tar xvf kata-static-2.0.0-x86_64.tar.xz -C /

# Description of problem

While vCPUs are being hot plugged and cgroups on the host are being applied correctly, I see that only a single CPU is being utilized within the guest itself. Since vCPUs are online properly, I tend to think this is an issue wrt cgroup management?

# Expected result

I should be able to launch a pod with 

```
apiVersion: v1
kind: Pod
metadata:
  name: kata-bb
spec:
  containers:
  - name: bb
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        cpu: 4
        memory: 1Gi
      limits:
        cpu: 4
        memory: 2Gi
  runtimeClassName: kata-qemu
```

Then I should be able to exec and spin up CPU work:

kubetl exec -it kata-bb -- sh

$ md5sum /dev/urandom & 
$ md5sum /dev/urandom & 
$ md5sum /dev/urandom & 
$ md5sum /dev/urandom & 

I should then be able to see on the host ~4 CPUs being used by the vCPUs, and I should see in the guest each md5sum taking ~ 100%.
(replace this text with an explanation of what you thought would happen)

# Actual result

Single CPU (100%) on host, and minimal CPU utilization per vCPU in the guest.

```
CPU:  4.9% usr 15.1% sys  0.0% nic 79.9% idle  0.0% io  0.0% irq  0.0% sirq
Load average: 4.99 3.53 1.64 6/88 14
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    9     2 root     R     1308  0.0   0  3.9 md5sum /dev/urandom
   11     2 root     R     1308  0.0   0  3.9 md5sum /dev/urandom
   12     2 root     R     1308  0.0   0  3.9 md5sum /dev/urandom
   13     2 root     R     1308  0.0   0  3.9 md5sum /dev/urandom
   10     2 root     R     1308  0.0   0  3.9 md5sum /dev/urandom
    2     0 root     S     1320  0.0   0  0.0 sh
   14     2 root     R     1312  0.0   0  0.0 top
    1     0 root     S     1300  0.0   0  0.0 sleep infinity
```

# Further information

This is with 2.0.0 release binaries, with enable_debug enabled for runtime and `sandbox_cgroup_only=true`
