### ISSUE TITLE
2.0: exit from exec hangs if background process is present

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1160]
# Get your issue reviewed faster

(with 2.0.0 release binaries in place) 

# Description of problem

You cannot exit a exec shell if there are background processes associated with that session 

# Expected result

```
eernst@ubuntu:~$ kubectl exec -it kata-bb -- sh
/ # md5sum /dev/urandom & 
/ # exit
```

You can exit and background processes persist 

# Actual result

kubectl exec is still running. 
# Further information

test yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kata-bb
spec:
  containers:
  - name: bb
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        cpu: 4
        memory: 1Gi
      limits:
        cpu: 4
        memory: 2Gi
  runtimeClassName: kata-qemu
```
