### ISSUE TITLE
kata container 2.0 applications can only use one CPU

### ISSUE THREAD

**Issue by wilhelmguo** [kata-containers/kata-containers#1365]
# Get your issue reviewed faster

To help us understand the problem more quickly, please do the following:

1. Run the `kata-collect-data.sh` script, which is installed as part of Kata Containers
   or `kata-containers.collect-data`, which is installed as part of the Kata Containers
   snapcraft package.
   ```sh
   $ sudo kata-collect-data.sh > /tmp/kata.log
   ```
   or
   ```sh
   $ sudo kata-containers.collect-data > /tmp/kata.log
   ```
1. Review the output file (`/tmp/kata.log`) to ensure it doesn't
   contain any private / sensitive information
1. Paste the *entire* contents of the file into this issue as a comment
   (the script generates markdown format output).

The information provided will help us to understand the problem more quickly
so saves time for both of us! :smile:

# Description of problem
Here is my kubernetes deplyment yaml file

```yaml
apiVersion: apps/Deployment
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
    wayne.io/app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: busybox
        wayne-app: busybox
    spec:
      runtimeClassName: kata
      containers:
        - command:
            - /bin/sh
            - '-ec'
            - sleep 3600000
          env: []
          envFrom: []
          image: debian:10
          imagePullPolicy: Always
          name: busybox
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '2'
              memory: 8Gi
``` 

when the container started, I exec the container and then start two command
```bash
for i in $(seq 1 1000000000);do echo  > /dev/null;done&
```

kata 2.0.1 version started container can only use one CPU

# Expected result

The cpu limit equal with  k8s resource cpu limit 

# Actual result

The container  always can only use one CPU.
![image](https://user-images.githubusercontent.com/12826425/107023573-cb3ce400-67e1-11eb-8809-b5aa6450c2f5.png)

# Further information

When I use kata-runtime exec the qemu vm, the cgroup value has benn set correctly. Then I kill the container progress, the the container recreate, and everything is ok.

**Comment by fidencio** [comment]
@c3d, do you remember we had a quite similar discussion in the past? It was related to @RobertKrawitz measurements.
Do you happen to remember the outcome of that discussion?

**Comment by liubin** [comment]
hi @wilhelmguo What do you mean `Then I kill the container progress, the the container recreate`? Is it that kill the container process in QEMU VM or kill QEMU in host?

**Comment by liubin** [comment]
Don't know whether the `top` command didn't show the correct stats.

I used this resource:

```yaml
  resources:
    limits:
      cpu: '2'
      memory: 1024Mi
    requests:
      memory: 1024Mi
      cpu: '2'
```

After Pod/container has started:

```
#  crictl stats -s 5 --id 78ad6064a5910 
CONTAINER           CPU %               MEM                 DISK                INODES
78ad6064a5910       0.01                356.4kB             28.72kB             10
```

Start the first `for i in $(seq 1 1000000000);do echo  > /dev/null;done&`:

```
#  crictl stats -s 5 --id 78ad6064a5910 
CONTAINER           CPU %               MEM                 DISK                INODES
78ad6064a5910       145.19              162.1MB             32.88kB             12
```

Start the second `for i in $(seq 1 1000000000);do echo  > /dev/null;done&`:

```
#  crictl stats -s 5 --id 78ad6064a5910 
CONTAINER           CPU %               MEM                 DISK                INODES
78ad6064a5910       199.89              297.6MB             32.88kB             12
```

Start the third, 4th, 5th `for i in $(seq 1 1000000000);do echo  > /dev/null;done&`:

```
#  crictl stats -s 5 --id 78ad6064a5910 
CONTAINER           CPU %               MEM                 DISK                INODES
78ad6064a5910       200.11              473.4MB             32.88kB             12
#  crictl stats -s 5 --id 78ad6064a5910 
CONTAINER           CPU %               MEM                 DISK                INODES
78ad6064a5910       200.18              565.7MB             32.88kB             12
#  crictl stats -s 5 --id 78ad6064a5910 
CONTAINER           CPU %               MEM                 DISK                INODES
78ad6064a5910       200.07              676.5MB             32.88kB             12

```
