### ISSUE TITLE
Run top command in Pod without tty=true get OOMKilled event

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1369]
With this Pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: img
  namespace: default
spec:
  runtimeClassName: kata
  restartPolicy: Never
  containers:
    - image: ubuntu #docker.io/containerstack/alpine-stress:latest
      name: ctr1
      env:
      - name: CONTAINER_NAME
        value: ctr1
      command:
        - top 
      resources:
        limits:
          cpu: '2'
        requests:
          cpu: '2'
```

The pod will get OOMKilled after created.

Add this will OK:
```
      tty: true
```

The OOMKilled is not correct, some other error should be reported.
