### ISSUE TITLE
groups not fully handled when exec'ing into container

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#1500]
To reproduce,  run:

 ```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: kata-bb
spec:
  containers:
  - name: bb
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 256Mi
  runtimeClassName: kata-qemu
  securityContext:
    fsGroup: 266
    runAsGroup: 51020
    runAsUser: 264
```

Then, check to see what uid/gids are available via exec:

```bash
$ kubectl exec -it kata-bb  -- sh -c id
uid=264 gid=51020
```

It is expected that the fsCgroup also be exposed. In the (working) runc case:
```bash
$ kubectl exec -it bb  -- sh -c id
uid=264 gid=51020 groups=266
```
