### ISSUE TITLE
Low memory utilisation with high number of memory-constrained workloads

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#1695]
# Summary

Trying deployments with increasing numbers of pods, I came across one scenario where Kata cannot utilize more than half the memory available in the cluster, whereas `runc` can take advantage of a much larger fraction.

## Workload

The workload is a [special simple workload](https://github.com/c3d/workload) intended to consume a configurable amount of memory and CPU. The deployment starts with the following yaml file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-deployment
  labels:
    app: workload

spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      runtimeClassName: kata
      containers:
      - name: workload
        image: quay.io/c3d/workload
        env:
        - name: CPU
          value: "5"
        - name: MEMORY
          value: "500"
        - name: INCREMENT
          value: "250"
      resources:
        requests:
          memory: 384Mi
        limits:
          memory: 512Mi
```

A script then scales the deployment. The cluster has 5 worker nodes with a total of 80G available memory.

Without the memory request and limit, I observed the following as the number of containers increased:

![kata-memory](https://user-images.githubusercontent.com/1695924/114854910-9ce11380-9de5-11eb-88b0-ce3fdbccc9e6.png)

With the memory request and limit, but without the `runtimeClass` (i.e. running with `runc`), I observe a similar pattern:

![runc-limited-memory](https://user-images.githubusercontent.com/1695924/114855374-301a4900-9de6-11eb-947b-cb574f93bae1.png)

With kata, on the other hand, the memory utilization stays well below 50% of the memory of the cluster

![kata-512M-memory](https://user-images.githubusercontent.com/1695924/114855575-69eb4f80-9de6-11eb-9846-47cbc4279d7c.png)

Interestingly, the behavior does not seem to depend on the size of the limit. For example, with 512M request and 1G limit we get:

![kata-1G-memory](https://user-images.githubusercontent.com/1695924/114855675-812a3d00-9de6-11eb-8eed-3b0a21b27b9b.png)

With 1G limit and 2G request we get:

![kata-2G-memory](https://user-images.githubusercontent.com/1695924/114855721-8e472c00-9de6-11eb-9060-909d334574fb.png)
