### ISSUE TITLE
cri-o cannot use "privileged: true" when using kata-containers

### ISSUE THREAD

**Issue by wangkuan** [kata-containers/kata-containers#1699]
**Description**

cri-o cannot use "privileged: true" when using kata-containers

**Steps to reproduce the issue:**
1. kubectl apply -f ubuntu.yaml

**Describe the results you received:**

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  27s                default-scheduler  Successfully assigned default/ubuntu-deployment-65b8db789c-jxw6h to kata-worker-1
  Normal   Pulled     10s (x4 over 25s)  kubelet            Container image "ubuntu:20.04" already present on machine
  Warning  Failed     10s (x4 over 25s)  kubelet            Error: CreateContainer failed: invalid read count expect 100 get 24: unknown

**Describe the results you expected:**

Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  14m   default-scheduler  Successfully assigned default/ubuntu-deployment-67f54cc86-cx5ff to kata-worker-1
  Normal  Pulled     14m   kubelet            Container image "ubuntu:20.04" already present on machine
  Normal  Created    14m   kubelet            Created container ubuntu
  Normal  Started    14m   kubelet            Started container ubuntu

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.21.0
Version:       1.21.0
GitCommit:     bc1ef35a932acc2f6f3b6d3eb19a4f68aa9423f6
GitTreeState:  clean
BuildDate:     2021-04-14T23:18:40Z
GoVersion:     go1.14.12
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

crio.conf

```
# The CRI-O configuration file specifies all of the available configuration
# options and command-line flags for the crio(8) OCI Kubernetes Container Runtime
# daemon, but in a TOML format that can be more easily modified and versioned.
#
# Please refer to crio.conf(5) for details of all configuration options.

# CRI-O supports partial configuration reload during runtime, which can be
# done by sending SIGHUP to the running process. Currently supported options
# are explicitly mentioned with: 'This option supports live configuration
# reload'.

# CRI-O reads its storage defaults from the containers-storage.conf(5) file
# located at /etc/containers/storage.conf. Modify this storage configuration if
# you want to change the system's defaults. If you want to modify storage just
# for CRI-O, you can change the storage configuration options here.
[crio]

# The crio.runtime table contains settings pertaining to the OCI runtime used
# and options for how to set up and manage the OCI runtime.
[crio.runtime]

# If true, SELinux will be used for pod separation on the host.
selinux = true

[crio.runtime.runtimes.kata]
runtime_path = "/opt/kata/bin/containerd-shim-kata-v2"
runtime_type = "vm"
runtime_root = "/run/vc"
privileged_without_host_devices = true

# The crio.network table containers settings pertaining to the management of
# CNI plugins.
[crio.network]

# Paths to directories where CNI plugin binaries are located.
plugin_dirs = [
        "/opt/cni/bin",
        "/usr/libexec/cni",
]

# A necessary configuration for Prometheus based metrics retrieval
[crio.metrics]

# Globally enable or disable metrics support.
enable_metrics = true

# The port on which the metrics server will listen.
metrics_port = 9537
```

ubuntu.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      runtimeClassName: kata
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kata-worker-1
      containers:
      - name: ubuntu
        securityContext:
          privileged: true
        image: ubuntu:20.04
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 3600; done;"]
```
