### ISSUE TITLE
Logs output on Kata Containers pod is being truncated

### ISSUE THREAD

**Issue by littlejawa** [kata-containers/kata-containers#1713]
# Description of problem

When printing the logs from a Kata Container, the logs content ends up being truncated, which doesn't happen with vanilla containers.

vanilla.yaml:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: test-vanilla
spec:
  restartPolicy: Never
  containers:
  - name: "test-vanilla"
    image: "fedora:latest"
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "cat /etc/services 1>&2"
```
kata.yaml:
```
--- 
apiVersion: v1
kind: Pod
metadata:
  name: test-kata
spec:
  restartPolicy: Never
  runtimeClassName: "kata"
  containers:
  - name: "test-kata"
    image: "fedora:latest"
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "cat /etc/services 1>&2"
```

In order to reproduce the issue, simply create those two pods:
```
kubectl create -f vanilla.yaml
kubectl create -f --kata.yaml
```

Then wait till the pods are completed;
Finally, compare the outputs:

```
kubectl logs test-vanilla | wc -l
kubectl logs test-kata | wc -l
kubectl logs test-vanilla | tail
kubectl logs test-kata | tail
```

# Expected result
The outputs should be the same.

# Actual result
Sometimes (about 1 out of 3), the logs from the test-kata pod are truncated.
The amount of missing data is not always the same.
