### ISSUE TITLE
jenkins reports "out of file descriptors" when kata-runtime launched from kubernetes

### ISSUE THREAD

**Issue by c3d** [kata-containers/kata-containers#1715]
# Description of problem

1. Deployed kubernetes on top of crio on Fedora 32
2. Create a Jenkins deployment with the following manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kata
  labels:
    app: jenkins
  # Annotation unimportant, added to check if it mattered
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      # But initially found with kata-qemu-virtiofs, as installed by kata-deploy
      # The 'kata' runtime uses the default kata-runtime installed by the Fedora 32 kata package
      # The result is the same in both cases
      runtimeClassName: kata
      containers:
        - name: jenkins
          image: jenkins/jenkins
          # Tried adding the following resource limits, they had no effect.
          # Neither did changing the default memory size to 8192 in configuration.toml
          resources:
            limits:
              memory: "8000Mi"
            requests:
              memory: "4000Mi"
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          nfs:
              path: /data/k8s
              server: turbo.local
```

# Expected result

Jenkins should start normally. It does start when either the runtimeClass is removed or when run inside kata-runtime using podman.

# Actual result

Pod does not start correctly:

```
  Normal   Scheduled  20s               default-scheduler  Successfully assigned default/jenkins-kata-575bff8798-8tc67 to muse
  Normal   Pulling    7s (x2 over 14s)  kubelet, muse      Pulling image "jenkins/jenkins"
  Normal   Pulled     3s (x2 over 9s)   kubelet, muse      Successfully pulled image "jenkins/jenkins"
  Normal   Created    2s (x2 over 8s)   kubelet, muse      Created container jenkins
  Normal   Started    2s (x2 over 8s)   kubelet, muse      Started container jenkins
  Warning  BackOff    1s                kubelet, muse      Back-off restarting failed container
```

The logs show a "well known" Java error:

```
library initialization failed - unable to allocate file descriptor table - out of memory
```

This seems to be an issue with ulimit being too low, see https://stackoverflow.com/questions/49435109/error-upon-jar-execution-unable-to-allocate-file-descriptor-table.

It's not clear why there would be any difference between the kubernetes and podman cases. After altering the CRIO configuration files to use the default configuration for Fedora (i.e. machine type q35, etc), I still get the same error.

qemu command line when starting from podman (which works):

```
/usr/bin/qemu-system-x86_64 -machine accel=kvm -name sandbox-851f97f457b2348bb619e432d75893fcd70c0f901a637515a1bda1a0787328da -uuid 83e661bb-ed8c-459e-b00e-381994ddec42 -machine q35,accel=kvm,kernel_irqchip -cpu host -qmp unix:/run/vc/vm/851f97f457b2348bb619e432d75893fcd70c0f901a637515a1bda1a0787328da/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=16945M -device pci-bridge,bus=pcie.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/851f97f457b2348bb619e432d75893fcd70c0f901a637515a1bda1a0787328da/console.sock,server,nowait -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device vhost-vsock-pci,disable-modern=false,vhostfd=3,id=vsock-1251054135,guest-cid=1251054135,romfile= -chardev socket,id=char-4bc771929bee0d9c,path=/run/vc/vm/851f97f457b2348bb619e432d75893fcd70c0f901a637515a1bda1a0787328da/vhost-fs.sock -device vhost-user-fs-pci,chardev=char-4bc771929bee0d9c,tag=kataShared,romfile= -netdev tap,id=network-0,vhost=on,vhostfds=4,fds=5 -device driver=virtio-net-pci,netdev=network-0,mac=da:e6:9b:61:49:1e,disable-modern=false,mq=on,vectors=4,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-file,id=dimm1,size=2048M,mem-path=/dev/shm,share=on -numa node,memdev=dimm1 -kernel /usr/lib/modules/5.6.0-0.rc4.git0.1.fc32.x86_64/vmlinuz -initrd /var/cache/kata-containers/osbuilder-images/5.6.0-0.rc4.git0.1.fc32.x86_64/fedora-kata-5.6.0-0.rc4.git0.1.fc32.x86_64.initrd -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 quiet panic=1 nr_cpus=8 agent.use_vsock=true -pidfile /run/vc/vm/851f97f457b2348bb619e432d75893fcd70c0f901a637515a1bda1a0787328da/pid -smp 1,cores=1,threads=1,sockets=8,maxcpus=8
```

Command line when run from kubernetes with default `kata-deploy` install and the `kata-qemu-virtiofs` runtime, which fails:

```
/opt/kata/bin/qemu-virtiofs-system-x86_64 -name sandbox-728336afe7411c11516211fec006e405bae3f83eea6bb94251d1d8da1d71edb4 -uuid 2c5bc067-5ead-4249-9be0-642c6bf7cb3f -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/728336afe7411c11516211fec006e405bae3f83eea6bb94251d1d8da1d71edb4/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=16945M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/728336afe7411c11516211fec006e405bae3f83eea6bb94251d1d8da1d71edb4/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.10.0_agent_a8007c2969.img,size=134217728 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/728336afe7411c11516211fec006e405bae3f83eea6bb94251d1d8da1d71edb4/kata.sock,server,nowait -chardev socket,id=char-05ec60d3878de856,path=/run/vc/vm/728336afe7411c11516211fec006e405bae3f83eea6bb94251d1d8da1d71edb4/vhost-fs.sock -device vhost-user-fs-pci,chardev=char-05ec60d3878de856,tag=kataShared,cache-size=1024M -netdev tap,id=network-0,vhost=on,vhostfds=3,fds=4 -device driver=virtio-net-pci,netdev=network-0,mac=96:eb:6e:59:fa:cf,disable-modern=false,mq=on,vectors=4,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-file,id=dimm1,size=2048M,mem-path=/dev/shm,share=on -numa node,memdev=dimm1 -kernel /opt/kata/share/kata-containers/vmlinuz-virtio-fs-v0.3-60 -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 quiet systemd.show_status=false panic=1 nr_cpus=8 agent.use_vsock=false systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket -pidfile /run/vc/vm/728336afe7411c11516211fec006e405bae3f83eea6bb94251d1d8da1d71edb4/pid -smp 1,cores=1,threads=1,sockets=8,maxcpus=8
```

qemu command line with `kata` runtime and the default Fedora 32 install:

```
/usr/bin/qemu-system-x86_64 -machine accel=kvm -name sandbox-a3a900668827bf56cd230d197c3191138145cbf0c5cf61d55b6ca8d77b491dfa -uuid 77a6ae3f-f88a-48da-8bf4-945453dad7f1 -machine q35,accel=kvm,kernel_irqchip -cpu host -qmp unix:/run/vc/vm/a3a900668827bf56cd230d197c3191138145cbf0c5cf61d55b6ca8d77b491dfa/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=16945M -device pci-bridge,bus=pcie.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/a3a900668827bf56cd230d197c3191138145cbf0c5cf61d55b6ca8d77b491dfa/console.sock,server,nowait -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device vhost-vsock-pci,disable-modern=false,vhostfd=3,id=vsock-1001320104,guest-cid=1001320104,romfile= -chardev socket,id=char-60f27d8263263f78,path=/run/vc/vm/a3a900668827bf56cd230d197c3191138145cbf0c5cf61d55b6ca8d77b491dfa/vhost-fs.sock -device vhost-user-fs-pci,chardev=char-60f27d8263263f78,tag=kataShared,romfile= -netdev tap,id=network-0,vhost=on,vhostfds=4,fds=5 -device driver=virtio-net-pci,netdev=network-0,mac=c6:a1:9b:c0:7a:f5,disable-modern=false,mq=on,vectors=4,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-file,id=dimm1,size=2048M,mem-path=/dev/shm,share=on -numa node,memdev=dimm1 -kernel /usr/lib/modules/5.6.0-0.rc4.git0.1.fc32.x86_64/vmlinuz -initrd /var/cache/kata-containers/osbuilder-images/5.6.0-0.rc4.git0.1.fc32.x86_64/fedora-kata-5.6.0-0.rc4.git0.1.fc32.x86_64.initrd -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 quiet panic=1 nr_cpus=8 agent.use_vsock=true -pidfile /run/vc/vm/a3a900668827bf56cd230d197c3191138145cbf0c5cf61d55b6ca8d77b491dfa/pid -smp 1,cores=1,threads=1,sockets=8,maxcpus=8
```
