### ISSUE TITLE
kubernetes: inconsistent behavior when using subPath with emptyDir volumes

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#1728]
# Description of problem

TL;DR: If you set a `subPath` in an emptyDir (memory medium) the mount point type is not the expected `tmpfs` (rather it seems the volume is being backed on the host filesystem).

There is a failing test on openshift-ci:

```
[sig-storage] EmptyDir volumes when FSGroup is specified [LinuxOnly] [NodeFeature:FSGroup] nonexistent volume subPath should have the correct mode and owner using FSGroup [Suite:openshift/conformance/parallel] [Suite:k8s]
```
After some investigation I could reproduce the problem, as I explained on https://github.com/kata-containers/kata-containers/pull/1703

# Actual result

Here is how to reproduce the bug. See down below that the mount type is `1702057286

```
[root@xxxx kubernetes]# cat runtimeclass_workloads/pod-empty-dir-fsgroup.yaml
#
# Copyright (c) 2021 Red Hat, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: sharevol-kata
spec:
  runtimeClassName: kata
  restartPolicy: Never
  securityContext:
    runAsUser: 1001
    fsGroup: 123
  containers:
  - name: mounttest-container-3
    image: "k8s.gcr.io/e2e-test-images/agnhost:2.21"
    args:
      - mounttest
      - --fs_type=/test-volume-3
      - --file_perm=/test-volume-3
      - --file_owner=/test-volume-3
      - --file_mode=/test-volume-3
    volumeMounts:
      - name: mem-emptydir-volume
        mountPath: /test-volume-3
        subPath: test-sub
  volumes:
  - name: mem-emptydir-volume
    emptyDir:
      medium: Memory
[root@xxxx kubernetes]# kubectl create -f runtimeclass_workloads/pod-empty-dir-fsgroup.yaml 
pod/sharevol-kata created
[root@xxxx kubernetes]# kubectl logs sharevol-kata
mount type of "/test-volume-3": 1702057286
mode of file "/test-volume-3": dgtrwxrwxrwx
perms of file "/test-volume-3": -rwxrwxrwx
owner UID of "/test-volume-3": 0
owner GID of "/test-volume-3": 123
```

# Expected result

Running the same pod but rather with `runc` the mount point is correctly set to `tmpfs`:
```
[root@xxxx kubernetes]# kubectl logs sharevol-non-kata
mount type of "/test-volume-3": tmpfs
mode of file "/test-volume-3": dgtrwxrwxrwx
perms of file "/test-volume-3": -rwxrwxrwx
owner UID of "/test-volume-3": 0
owner GID of "/test-volume-3": 123
```
