### ISSUE TITLE
Kata agent runtime configuration

### ISSUE THREAD

**Issue by sameo** [kata-containers/kata-containers#1837]
## Problem Statement

The [kata-agent](https://github.com/kata-containers/agent) communicates with the host through a [gRPC API](https://github.com/kata-containers/agent/blob/master/protocols/grpc/agent.proto#L16), via a vsock channel. The host typically sends commands and request to the kata-agent, though this RPC mechanism.

In a [confidential computing context](#1332), where the host software stack is out of the guest TCB, parts of that host <-> guest interface can not be supported without breaking the expected confidential computing threat model.

## Proposal

We want to propose for the `kata-agent` to **optionally** use a configuration file that would allow for a more dynamically defined agent behaviour. The configuration file would be passed to the `kata-agent` as a command line option: `kata-agent -c agent-configuration.toml` 

We expect this file to be added to the guest primary root filesystem (initramfs or virtio-block device). As a consequence, confidential computing technologies would include that configuration file as part of their verified TCB measurements. In other words, an attested guest could only start its kata-agent through a verified configuration file.

### Goals

Although a `kata-agent` runtime configuration file could be used to extensively customize the agent's behaviour, the primary and initial goal of that proposal is to use it as a runtime definition of the supported agent gRPC API, in order to meet and build the confidential computing threat model.

In other words the goals of that proposal are:

- Allow for the `kata-agent` binary to use an optional configuration file
- Define an API restriction section for this configuration file
- Add the existing `kata-agent` command line parameters to the configuration file. The command line parameters would overwrite the configuration file ones.

### Configuration file format

For consistency sake with the other `kata-containers` components, we propose for the agent configuration file to use the TOML format.

### API section

The `kata-agent` configuration file would contain an `[api]` section. The section would then contain a `blocked_endpoints` entry describing the blocked gRPC endpoints as a string list.

Each entry in the `blocked_endpoints` list should map exactly to one of the agent gRPC service method defined in the [AgentService](https://github.com/kata-containers/agent/blob/master/protocols/grpc/agent.proto) proto file.

The agent should fail to start if one or more entry in the `blocked_endpoints` does not map to an `AgentService` method.

### Sample

```toml

# Agent runtime settings.
# A configured values will be overwritten when passing it through its corresponding command line interface option.
[agent]
debug_console = false
debug_console_vport = 0
log_level = "default"
log_vport = 0
hotplug_timeout = 3
container_pipe_size = 0
server_addr = "vsock://-1:1024"
unified_cgroup_hierarchy = false

# Agent gRPC API settings.
[api]
# Blocked API endpoints.
# A list of blocked gRPC endpoints. For example:
# blocked_endpoints = ["ExecProcess", "ReseedRandomDev"]
#
# Any client request to a blocked enpoint will return a "UNIMPLEMENTED" gRPC status code. 
blocked_enpoints = []
```
