### ISSUE TITLE
Secret generation with `/dev/urandom | fold -w 32 | head -n 1` never terminates (SIGPIPE not sent?)

### ISSUE THREAD

**Issue by LFrobeen** [kata-containers/kata-containers#1887]
**Description**

While trying to create a random secret based on `/dev/urandom` I noticed that the following command does not terminate when run in a kata environment: 
```cat /dev/urandom | fold -w 32 | head -n 1```
It does generate some output, but does not finish execution. 

When I run this command in a non-kata environment it terminates as expected after printing some random output.

**_Observed behavior:_**

```cat /dev/urandom | fold -w 32 | head -n 1``` prints random output but does not terminate when run with gvsior. 

Note that this is not limited to `/dev/urandom`, I am getting similar results with `/dev/zero`.

**_Expected behavior:_**

```cat /dev/urandom | fold -w 32 | head -n 1``` should terminate after printing some random output.

**Steps to reproduce**

I was able to reproduce the error in my kubernetes environment with this Pod manifest: 
```
kind: Pod
apiVersion: v1
metadata:
  name: test
  namespace: kata-debug
spec:
  runtimeClassName: kata
  restartPolicy: 'Never'
  containers:
    - name: main
      image: 'busybox:latest'
      command:
        - sh
        - -c
        - |
          cat /dev/urandom | fold -w 32 | head -n 1
          echo Done
          exit 0
      imagePullPolicy: Always
```

The pod prints some random output, but does not reach the `echo Done` command and never completes. 
When applying the manifest without the `runtimeClassName`, the Pod completes as expected.

**Additional Notes**

I recently filed a similar issue over in the gvisor repository (google/gvisor#5974) and apparently the above error is caused by a SIGPIPE signal not being sent for closed pipes.

For gvisor, the error has been fixed in google/gvisor#6006, which might be of some use here as well.
