### ISSUE TITLE
Failed to mount sysfs directory in kubernetes

### ISSUE THREAD

**Issue by sunwoo2** [kata-containers/kata-containers#1962]
# Description of problem

I tried to mount sysfs directory to kata container in k8s. But Failed. #1923 
I installed kata via kata-deploy (https://github.com/kata-containers/kata-containers/tree/stable-2.1/tools/packaging/kata-deploy)
And I've refered to docs (https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/run-kata-with-k8s.md#containerd-with-cri-plugin).
My CRI runtime is containerd.
The sysfs directory mount works well with runc rather than kata container.

What did I missed ??
I don't really know what caused the problem. kata container? containerd? kubernetes?

# Actual result
```
root# kubectl apply -f kata-qemu.yaml
pod/secquant created
```
```
root# kubectl describe pods
Name:         secquant
Namespace:    default
Priority:     0
Node:         proxima02/192.168.0.212
Start Time:   Fri, 04 Jun 2021 16:57:25 +0900
Labels:       app=secquant
Annotations:  <none>
Status:       Failed
IP:           10.61.0.61
IPs:
  IP:  10.61.0.61
Containers:
  secquant:
    Container ID:  containerd://c4f77ba72ba1623e137618c9b1d1c895cbd348e36e90ed0617d0935318b0008e
    Image:         abab702/secquant:v5.0
    Image ID:      docker.io/abab702/secquant@sha256:0cd4502927ffb225efb533318e46c66c5d0b25eca06b4d23f0cfe134179f1ff6
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sleep
      3650d
    State:          Terminated
      Reason:       StartError
      Message:      failed to create containerd task: No such file or directory (os error 2): unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 09:00:00 +0900
      Finished:     Fri, 04 Jun 2021 16:57:29 +0900
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /sys/kernel/tracing from trace-marker (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-db2ck (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  trace-marker:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/tracing
    HostPathType:
  kube-api-access-db2ck:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              katacontainers.io/kata-runtime=true
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  26s   default-scheduler  Successfully assigned default/secquant to proxima02
  Normal   Pulled     25s   kubelet            Container image "abab702/secquant:v5.0" already present on machine
  Normal   Created    22s   kubelet            Created container secquant
  Warning  Failed     22s   kubelet            Error: failed to create containerd task: No such file or directory (os error 2): unknown
```

# Further information

I'm work on ubuntu 20.04. my k8s version is 1.21.1.
Here's my pod spec that I tried.
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  runtimeClassName: kata-qemu
  containers:
    - name: test
      image: abab702/secquant:v5.0
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: /home
        name: trace-marker
  restartPolicy: Never
  volumes:
  - name: trace-marker
    hostPath:
      path: /sys/kernel/tracing
```

This is the successful pod spec with runc.
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: test
    image: abab702/secquant:v5.0
    command: ["/bin/sleep", "3650d"]
    volumeMounts:
    - mountPath: /home
      name: trace-marker
  restartPolicy: Never
  volumes:
  - name: trace-marker
    hostPath:
      path: /sys/kernel/tracing
```

The only different thing is `runtimeClassName: kata-qemu`
The reason why I try to mount sysfs directory is to use trace_marker of ftrace.
