### ISSUE TITLE
io.katacontainers.config.hypervisor.memory_offset: is not enabled

### ISSUE THREAD

**Issue by pohly** [kata-containers/kata-containers#2002]
# Description of problem

I installed Kata Containers 2.1.0 on Kubernetes 1.20 with kata-deploy, with the version locked onto 2.1.0 by https://github.com/pohly/pmem-CSI/blob/fix-kata-containers-support/test/setup-kata-containers.sh#L1-L43

I then tried to create this pod:
```
kind: Pod
apiVersion: v1
metadata:
  name: my-kata-app
  annotations:
    io.katacontainers.config.hypervisor.memory_offset: "2147483648" # 2Gi, must be at least as large as the PMEM volume
spec:
  runtimeClassName: kata-qemu
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
  containers:
    - name: my-frontend
      image: intel/pmem-csi-driver-test:canary
      command: [ "sleep", "100000" ]
```

# Expected result

Pod should run.

# Actual result

Fails to start:

```
$ kubectl describe pods/my-kata-app
Name:         my-kata-app
Namespace:    default
...
Events:
  Type     Reason                  Age                 From               Message
  ----     ------                  ----                ----               -------
  Normal   Scheduled               53s                 default-scheduler  Successfully assigned default/my-kata-app to pmem-csi-pmem-govm-worker3
  Warning  FailedCreatePodSandBox  28s (x25 over 52s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: annotation io.katacontainers.config.hypervisor.memory_offset is not enabled: unknown
```

# Further information

Kubernetes: 1.20.5
containerd: 1.3.7

This was encountered while fixing PMEM-CSI's Kata Containers support, see https://github.com/intel/pmem-csi/issues/987

It can be reproduced on the QEMU cluster that gets started by running `make start && test/setup-kata-containers.sh` in the root of the PMEM-CSI source branch linked to above.
