### ISSUE TITLE
docker:dind reports ... cannot find cgroup mount destination: unknown.

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#2014]
We're in the process of moving from kata 1.12.1 to 2.1. We noticed a change in behavior when we launch docker:dind.

```
/ # docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b8dfde127a29: Pull complete 
Digest: sha256:9f6ad537c5132bcce57f7a0a20e317228d382c3cd61edae14650eec68b2b345c
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.
```
This is actually easy to workaround but at least wanted to report the issue...
```
/ # mkdir /sys/fs/cgroup/systemd
/ # mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
/ # docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by skaegi** [comment]
Here's the pod recipe I was using...
```
apiVersion: v1
kind: Pod
metadata:
  name: untrusted-dind
spec:
  containers:
    - name: docker
      image: docker:19-dind
      command: ["sh", "-c"]
      args:
      - if [[ $(df -PT /var/lib/docker | awk 'NR==2 {print $2}') == virtiofs ]]; then 
          apk add e2fsprogs && 
          truncate -s 20G /tmp/disk.img && 
          mkfs.ext4 /tmp/disk.img && 
          mount /tmp/disk.img /var/lib/docker; fi &&
        dockerd-entrypoint.sh --mtu=1400;
      securityContext:
        privileged: true
  runtimeClassName: kata-qemu
  ```
  I ran ...
  ```
  kubectl apply -f untrusted-dind.yaml
  kubectl exec -it untrusted-dind -- sh
  ```
