### ISSUE TITLE
Missing directory for K8s container "workingDir" causes fatal error instead of creating it 

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#2555]
We are trying to move from Kata1 to Kata2 in our K8s clusters and noticed a small difference/problem with "workingDir" support. When the workingDir in our containers does not exist we are getting an error and the container is failing to start -- `'failed to create containerd task: ENOENT: No such file or directory: unknown'.` This unfortunately is used in many of the recipes our customers have in their CI/CD containers.

The behaviour is not specified terribly clearly at least where I've been looking but what we currently see is that if the folder does not exist already it gets created. This is what we see when using both the docker cli and k8s.

e.g.

For docker...
```
$  docker run -it --rm -w /does-not-exist alpine ls -ld /does-not-exist
drwxr-xr-x    2 root     root          4096 Sep  1 14:18 /does-not-exist
```

For K8s....
```
apiVersion: v1
kind: Pod
metadata:
  name: rc-alpine
spec:
  #runtimeClassName: kata-qemu
  containers:
    - name: alpine
      image: alpine
      imagePullPolicy: IfNotPresent
      command:
      - sleep
      - "50000000"
      workingDir: /does-not-exist
 ```
 Works right now but will fail if the `#runtimeClassName: kata-qemu` line is uncommented and results in a CrashLoop with the ENOENT error above
