### ISSUE TITLE
Newest Rust version listed in versions.yaml is rather old

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#2633]
# Description of problem

`versions.yaml` includes this stanza:

```
languages:
  . . .
  rust:
    description: "Rust language"
    notes: "'version' is the default minimum version used by this project."
    version: "1.45.0"
    meta:
      description: |
        'newest-version' is the latest version known to work when
        building Kata
      newest-version: "1.47.0"
```

So the latest tested Rust version is 1.47.0, which is now fairly old.  Fedora, for example includes version 1.54.0 and upstream has released 1.55.0.

# Expected result

Kata is tested and works with recent Rust versions.
