### ISSUE TITLE
RFC | feature proposal: execute a helper binary alongside containerd-shim-kata-v2

### ISSUE THREAD

**Issue by bchalios** [kata-containers/kata-containers#2814]
We are building vAccel, a framework to facilitate hardware acceleration in multi-tenant platforms by decoupling user functions from their respective hardware implementations. To enable guest-to-host communication we use a transport mechanism with two ends: one in the guest and one in the host. This RFC examines the options to design this and integrate it in kata containers.

## Background & Motivation

In vAccel, we are using kata-containers to sandbox the user application and integrate it with higher-level orchestration frameworks (k8s). 

vAccel consists of two main layers: the runtime system, vAccelRT and a set of plugins that contain the hardware implementations of the user-facing API (see Figure above). For instance, to execute a BLAS application on vAccel, the user needs to change the function calls for the BLAS functions to the respective vAccel ones and add a BLAS plugin to vAccel. For more information about vAccel please have a look at our FOSDEM talks [1](https://fosdem.org/2021/schedule/event/vai_ml_lightweight_vmms/) and [2](https://fosdem.org/2021/schedule/event/containers_ml_kata/).

## Use case

When executing from inside a VM, the framework consists of two components, a vAccel application (which in the case of Kata, it would run inside the container) and a host component, the vAccel agent, which has direct access to hardware devices and acts as a gRPC server that receives and executes acceleration requests. The communication of the two components, in this scenario, happens over the vsock transport, through a transport plugin used by the guest application.

![image](https://user-images.githubusercontent.com/26031778/136591677-ad1d15ba-48c6-4123-bd0f-4ed598b2490a.png)

In order to enable vAccel execution with kata containers essentially we need to execute a binary, the vAccel agent, with a proper environment, whenever a new VM is spawned and make it listen to the unix end of the vsock channel. In our own fork of the kata containers runtime we have made changes to add the necessary mechanisms to achieve that, which are currently tailored to the vAccel particular use-case.

We believe that this could be implemented in a much cleaner and generic way which could potentially interest other use-cases as well. Essentially, the binary launched by the containerd-shim-kata-v2 runtime does not need to be a vAccel agent.

## Requirements / Discussion

Ideally, at least for the vAccel use-case, we would like the containerd-shim-kata-v2 to do the following:
1. spawn a binary with a specific environment (before or during the sandbox creation)
1. have it listen to the VMs Unix end of the vsock transport layer (during the sandbox creation process)
1. kill it (before or after the sandbox tear-down process).

An example configuration for such a setup could look like:

```toml
[proxy]
# If enabled, a helper binary will be executed when the sandbox 
# is created. This allows for additional handling of container lifecycle
# management (eg. run a monitoring process, or a service for the container)
# (default: disabled)
#enable_proxy = true

# Specify the path to the proxy binary.
path = "/opt/kata/libexec/kata-containers/proxy"

# A set of environment variables to pass to the launched process
[proxy.env]
#env1 = val1
#env2 = val2

# If enabled, proxy messages will be sent to the system log
# (default: disabled)
#enable_debug = true
```

A further idea to explore would be defining an API between the Kata runtime and the proxy application (through gRPC?) so that we could have the two components interact, regardless of the lifetime of the VM. For example, this would enable us to have one proxy application on the host, handling requests from multiple VMs.

We would like feedback from the community in the following aspects:
1. Are there other members of the community that have a use-case like this?
1. Would you think that this is a mechanism worth integrating in the kata runtime?
1. What would be the proper way to design and implement this ?
        - as an external vendor package?
        - as an internal mechanism?

cc @kata-containers/architecture-committee  @ananos
