### ISSUE TITLE
Fail to pass the mount point from init container.

### ISSUE THREAD

**Issue by shuochen0311** [kata-containers/kata-containers#2819]
# Get your issue reviewed faster

To help us understand the problem more quickly, please do the following:

1. Run the `kata-collect-data.sh` script, which is installed as part of Kata Containers
   or `kata-containers.collect-data`, which is installed as part of the Kata Containers
   snapcraft package.
   ```sh
   $ sudo kata-collect-data.sh > /tmp/kata.log
   ```
   or
   ```sh
   $ sudo kata-containers.collect-data > /tmp/kata.log
   ```
1. Review the output file (`/tmp/kata.log`) to ensure it doesn't
   contain any private / sensitive information
1. Paste the *entire* contents of the file into this issue as a comment
   (the script generates markdown format output).

The information provided will help us to understand the problem more quickly
so saves time for both of us! :smile:

# Description of problem

I am using the following yaml file to create a pod 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-raw-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 8Gi
  storageClassName: default
---
apiVersion: v1
kind: Pod
metadata:
  name: init-raw-pod
spec:
  runtimeClassName: kata-qemu
  initContainers:
    - name: format-raw-device
      image: ubuntu
      securityContext:
        privileged: true
      volumeMounts:
        - name: connectors
          mountPath: /shared_dir
          mountPropagation: Bidirectional
      volumeDevices:
        - devicePath: /dev/sdc
          name: init-raw-volume
      command: ['bash', '-c', 'mkfs.ext4 /dev/sdc; mkdir -p /shared_dir/local_disk0; mount /dev/sdc /shared_dir/local_disk0']
  containers:
    - name: my-container
      image: ubuntu
      volumeMounts:
        - name: connectors
          mountPath: /shared_dir
          mountPropagation: HostToContainer
      command: ['sh', '-c', 'sleep infinity']
  volumes:
    - name: init-raw-volume
      persistentVolumeClaim:
        claimName: init-raw-pvc
    - name: connectors
      emptyDir: {}
```
What this yaml file does is passing the remote ssd(I am using Azure for example) as a block device `/dev/sdc` . Then I use an init container to make filesystem and mount this block device to a mountpoint located inside emptydir directory. Then I create a normal container with an emptydir mount.

# Expected result

What I expected to see is under the emptydir directory, I can see the mountpoint created by init container and it is mounted with /dev/sdc. 

# Actual result

I can see the mountpoint folder get created in emptydir directory. But I can not see /dev/sdc get mounted and I can not do any I/Os in that directory. (can not touch files for example)

# Further information
If I use a normal container instead of a init container to do mounting works, everything works.
