### ISSUE TITLE
Kata not creating symbolic links on mounted ConfigMap

### ISSUE THREAD

**Issue by hleal18** [kata-containers/kata-containers#2950]
## Kubelet version

v1.20.11+k3s1 - deployed on k3s.

v1.20.10-gke.2100 - gke cluster.

## Operating System

Ubuntu 20.04.3 LTS

## Kata version

kata-runtime: 2.2.0-alpha1 → 2.3.0-alpha2

# Description of problem

When mounting a ConfigMap the default behavior is for Kubernetes to create hidden folders and some symbolic links between them and the file on the top level. We've found that when using `kata-clh` runtime class this is not the case. Rather than symbolic links being created, the original files are used instead.

This affects the behavior of commands that scan for scripts on the mounted folder, as using the following command `find -type f` will show the same file three times: 

- The mounted file.
- The file inside the `..{DATE}` folder
- The file inside the `..data` folder

This interferes with our operation of certain helm charts as the initialization scripts loaded from a ConfigMap will mistakenly get executed three times which is not desired.

We have attached more information about the expected outcome and the behavior we're experiencing.

# Sample Manifests

The following are the Kubernetes resources used to reproduce the issue. Once deployed, exec into the container and go to the `/scripts` folder:

```bash
kubectl exec {nginx-pod-name} -i -t -- /bin/bash
cd /scripts
```

### Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: nginx-configmap
      runtimeClassName: kata-clh
```

### ConfigMap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  init-script.sh: |
    #!/bin/bash
    echo "Hello there"
```

# Expected result

Using the previous manifests without a runtime class, inspecting the mounted folder on the `/scripts` path, which contains one file called `init-script.sh` , we can observe the expected results after running `ls -la`:

```jsx
/scripts$ ls -la
total 13
drwxrwxrwx 3 root root 4096 Oct 29 03:10 .
drwxr-xr-x 1 root root 4096 Oct 29 03:11 ..
drwxr-xr-x 2 root root 4096 Oct 29 03:10 ..2021_10_29_03_10_48.161654083
lrwxrwxrwx 1 root root   31 Oct 29 03:10 ..data -> ..2021_10_29_03_10_48.161654083
lrwxrwxrwx 1 root root   21 Oct 29 03:10 init-script.sh -> ..data/init-script.sh
```

Symbolic links from the `init-script.sh` on the top level to the file located at`..data/init-script.sh` . Similarly, a symlink from the `..data` folder to the `..2021_10_29_03_10_48.161654083` folder is observed.

Running `ls -la` from each subfolder shows the following output.

- `/scripts/..2021_10_29_03_10_48.161654083` :

```jsx
/scripts/..2021_10_29_03_10_48.161654083$ ls -la
total 9
drwxr-xr-x 2 root root 4096 Oct 29 03:10 .
drwxrwxrwx 3 root root 4096 Oct 29 03:10 ..
-rw-r--r-- 1 root root   31 Oct 29 03:10 init-script.sh
```

- `/scripts/..data` :

```jsx
/scripts/..data$ ls -la
total 9
drwxr-xr-x 2 root root 4096 Oct 29 03:10 .
drwxrwxrwx 3 root root 4096 Oct 29 03:10 ..
-rw-r--r-- 1 root root   31 Oct 29 03:10 init-script.sh
```

# Actual result

Now with the same deployment and configmap but now using `kata-clh` runtime class, running the same `ls -la` command:

```jsx
/scripts$ ls -la
total 12
drwxr-xr-x 4 root root  100 Oct 29 02:50 .
drwxr-xr-x 1 root root 4096 Oct 29 02:50 ..
drwxr-xr-x 2 root root   60 Oct 29 02:50 ..2021_10_29_02_50_12.610733714
drwxr-xr-x 2 root root   60 Oct 29 02:50 ..data
-rw-r--r-- 1 root root   31 Oct 29 02:50 init-script.sh
```

The symbolic links are not there anymore. 

Running  `ls -la` from `/script/..2021_10_29_02_50_12.610733714` shows the following results:

```jsx
/scripts/..2021_10_29_02_50_12.610733714$ ls -la
total 4
drwxr-xr-x 2 root root  60 Oct 29 02:50 .
drwxr-xr-x 4 root root 100 Oct 29 02:50 ..
-rw-r--r-- 1 root root  31 Oct 29 02:50 init-script.sh
```

Running `ls -la` from `/scripts/..data` shows the following results:

```jsx
/scripts/..data$ ls -la
total 4
drwxr-xr-x 2 root root  60 Oct 29 02:50 .
drwxr-xr-x 4 root root 100 Oct 29 02:50 ..
-rw-r--r-- 1 root root  31 Oct 29 02:50 init-script.sh
```

# Further Information

We've tried different versions of kata-runtime. We tested `2.1.1`, `2.2.0-alpha0` , `2.2.0-alpha1`, `2.2.0` and `2.3.0-alpha2`. The only ones that worked as expected were `2.1.1` and `2.2.0-alpha0`, hence, we believe the change might have been introduced at `2.2.0-alpha1`. We hope this serves as a good starting point for looking into this issue.
