### ISSUE TITLE
Nested data volumes using configmap, downwardsapi, secrets, emptydir are broken in Kata 2

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#3140]
# Description of problem

If a pod declares mountpoints that are nested or overlap that are using a mixture of configmaps, secrets, downward api, and emptydir we are seeing unexpected behaviour that result in CrashLoopBackOffs, RunContainerError, and/or very slow resolution. The same pod definitions will work correctly with a standard runc based runtime Kubernetes as well as Kata v1.

Here's a gist that includes testcases we're using -- https://gist.github.com/skaegi/fa67f00ed0fe34d91a6b2a699b0f9ba4

The above gist includes test-cases for vanilla k8s, kata-qemu runtimeclass, and the old untrusted annotation style. To try the runtime class variant you can use...
```
kubectl apply -f https://gist.githubusercontent.com/skaegi/fa67f00ed0fe34d91a6b2a699b0f9ba4/raw/870491963ca7a0c75605b0979b6e81cea8da8903/testcase-nested-kata-qemu.yaml
```

The suite above is more complete but here's a sample test...
```
apiVersion: v1
data:
  config: my config
kind: ConfigMap
metadata:
  name: config
---
apiVersion: v1
data:
  secret: c2VjcmV0Cg==
kind: Secret
metadata:
  name: moresecrets
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: nested-config-secret
spec:
  containers:
  - args:
    - -c
    - ls /config/secrets
    command:
    - /bin/sh
    image: gcr.io/google_containers/busybox:latest
    name: busybox
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /config/secrets
      name: secrets
  restartPolicy: OnFailure
  volumes:
  - name: secrets
    secret:
      secretName: secrets
  - configMap:
      name: config
    name: config
 ```
 
 These tests all worked correctly in Kata v1 as well as vanilla K8s but do not work in Kata 2.2.1 or 2.2.3. 

# Expected result

These pods should resolve and the containers complete successfully quickly.
```
$ k get po
NAME                            READY   STATUS      RESTARTS   AGE
nested-config-config            0/1     Completed   0          19m
nested-config-config-revmount   0/1     Completed   0          19m
nested-config-down              0/1     Completed   0          19m
nested-config-empty             0/1     Completed   0          19m
nested-config-secret            0/1     Completed   0          19m
nested-config-self              0/1     Completed   0          19m
nested-down-config              0/1     Completed   0          19m
nested-down-down                0/1     Completed   0          19m
nested-down-down-revmount       0/1     Completed   0          19m
nested-down-empty               0/1     Completed   0          19m
nested-down-secret              0/1     Completed   0          19m
nested-down-self                0/1     Completed   0          19m
nested-empty-config             0/1     Completed   0          19m
nested-empty-down               0/1     Completed   0          19m
nested-empty-empty              0/1     Completed   0          19m
nested-empty-empty-revmount     0/1     Completed   0          19m
nested-empty-secret             0/1     Completed   0          19m
nested-empty-self               0/1     Completed   0          19m
nested-secret-config            0/1     Completed   0          19m
nested-secret-down              0/1     Completed   0          19m
nested-secret-empty             0/1     Completed   0          19m
nested-secret-secret            0/1     Completed   0          19m
nested-secret-secret-revmount   0/1     Completed   0          19m
nested-secret-self              0/1     Completed   0          19m
```

# Actual result

We are seeing unexpected behaviour that result in a semi-random mixture of CrashLoopBackOffs, RunContainerError, and/or very slow resolution. Results can be a bit random but here's a sample using Kata 2.2.3 ...
```
$ k get po
NAME                            READY   STATUS              RESTARTS   AGE
nested-config-config            0/1     CrashLoopBackOff    1          25s
nested-config-config-revmount   0/1     CrashLoopBackOff    1          25s
nested-config-down              0/1     CrashLoopBackOff    1          25s
nested-config-empty             0/1     CrashLoopBackOff    1          24s
nested-config-secret            0/1     RunContainerError   2          24s
nested-config-self              0/1     CrashLoopBackOff    1          24s
nested-down-config              0/1     Completed           0          24s
nested-down-down                0/1     Completed           0          24s
nested-down-down-revmount       0/1     Completed           0          24s
nested-down-empty               0/1     Completed           0          23s
nested-down-secret              0/1     Completed           0          23s
nested-down-self                0/1     Completed           0          23s
nested-empty-config             0/1     Completed           0          23s
nested-empty-down               0/1     Completed           0          23s
nested-empty-empty              0/1     Completed           0          23s
nested-empty-empty-revmount     0/1     Completed           0          23s
nested-empty-secret             0/1     Completed           0          23s
nested-empty-self               0/1     ContainerCreating   0          22s
nested-secret-config            0/1     ContainerCreating   0          22s
nested-secret-down              0/1     ContainerCreating   0          22s
nested-secret-empty             0/1     ContainerCreating   0          22s
nested-secret-secret            0/1     ContainerCreating   0          22s
nested-secret-secret-revmount   0/1     ContainerCreating   0          22s
nested-secret-self              0/1     ContainerCreating   0          22s
```

# Further information

This sort of thing may look strange but is in very common use in our CI/CD system where we had so many customers report problems we were forced to roll back to Kata 1. Not sure if this might be helpful but the original issues/fixes in Kube from 2017 might be relevant as this is where this behaviour became officially supported.
1) https://github.com/kubernetes/kubernetes/issues/57421
2) https://github.com/kubernetes/kubernetes/pull/57422
