### ISSUE TITLE
Kata block the traffic internally in k8s

### ISSUE THREAD

**Issue by RamyChaabane** [kata-containers/kata-containers#3159]
# Description of problem
Hello
I have a simple daemonSet (flask app)  configured with a hostPort and a simple pod running in the same namespace and the same node. The pod is using kata-container as runtimeClassName.

When I try to curl the ds from the pod using the internal node IP and the hostPort, the connection is always refused:
```
curl http://<internal_node_ip>:<hostPort>
connection refused
```
However:

- using the external node ip
- or, pod is running without a runtimeClass

It works fine

I guess there is something wrong when forwarding traffic

The container runtime is `containerd`
Thank you for the help

(replace this text with the list of steps you followed)

# Expected result
internal connection between pod and ds works

# Actual result
connection refused

**Comment by liubin** [comment]
@RamyChaabane can you help to share your Pod definition file?

**Comment by RamyChaabane** [comment]
yes sure
runtime definition:
```
apiVersion: node.k8s.io/v1
handler: kata
kind: RuntimeClass
metadata:
  name: kata
```
deploy definition:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kata-ubuntu
  name: kata-ubuntu
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kata-ubuntu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kata-ubuntu
    spec:
      containers:
      - args:
        - infinity
        command:
        - sleep
        image: ubuntu
        imagePullPolicy: Always
        name: ubuntu
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      runtimeClassName: kata
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

daemonSet definition:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flask
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: flask
  template:
    metadata:
      labels:
        name: flask
    spec:
      containers:
      - image: docker.io/ramydocker/flask-tutorial
        imagePullPolicy: Always
        name: flask
        ports:
        - containerPort: 5000
          hostPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

I'm using:
- containerd as a runtime
- cilium as network overlay
