### ISSUE TITLE
kata-deploy creates no containerd-shim-kata-v2 binary

### ISSUE THREAD

**Issue by Jakob-Naucke** [kata-containers/kata-containers#3228]
Let me preface by saying I'm not sure whether this is intentional, but I find it a little inconsistent.
When applying kata-deploy, we create
```
$ ls -l /opt/kata/share/defaults/kata-containers/
total 64
-rw-r--r-- 1 root root  9384 Nov 29 19:42 configuration-acrn.toml
-rw-r--r-- 1 root root 11507 Nov 29 19:42 configuration-clh.toml
-rw-r--r-- 1 root root 14807 Nov 29 19:43 configuration-fc.toml
-rw-r--r-- 1 root root 24138 Nov 29 19:43 configuration-qemu.toml
lrwxrwxrwx 1 root root    23 Nov 29 19:43 configuration.toml -> configuration-qemu.toml
```

and in `/etc/containerd/config.toml`:
```toml
[plugins.cri.containerd.runtimes.kata]
  runtime_type = "io.containerd.kata.v2"
  …
  [plugins.cri.containerd.runtimes.kata.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration.toml"
[plugins.cri.containerd.runtimes.kata-fc]
  runtime_type = "io.containerd.kata-fc.v2"
  …
  [plugins.cri.containerd.runtimes.kata-fc.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-fc.toml"
```

but only:
```
$ ls -l /usr/local/bin/*kata*
-rwxr-xr-x 1 root root 134 Dec  7 19:25 /usr/local/bin/containerd-shim-kata-clh-v2
-rwxr-xr-x 1 root root 133 Dec  7 19:25 /usr/local/bin/containerd-shim-kata-fc-v2
-rwxr-xr-x 1 root root 135 Dec  7 19:25 /usr/local/bin/containerd-shim-kata-qemu-v2
```

i.e. we create a `kata` runtime class that will use the QEMU config by default (:heart: for cross-platform compatibility) but no containerd shim to match? This means the `kata` runtime isn't usable as is. I think we should either:

1. remain neutral and remove the link and `kata` runtime class, or
2. accept QEMU as default and also create a `containerd-shim-kata-v2`.
