### ISSUE TITLE
flock Doesn't Lock With Default Configuration

### ISSUE THREAD

**Issue by haslersn** [kata-containers/kata-containers#3408]
With default configuration, kata doesn't support locking files using the `flock` syscall. There's not even an error. Consequently, the file is seemingly locked, but it isn't. The file can be seemingly locked in multiple containers at once.

# Expected result

`flock` should work as in runc, in order to avoid a surprise (and potential data corruption) when replacing runc by Kata in, e.g., a Kubernetes Deployment.

# Workaround

Apply the following patch to Kata's `configuration.toml`:

```diff
@@ -154,7 +154,7 @@
 #   ["-o", "arg1=xxx,arg2", "-o", "hello world", "--arg3=yyy"]
 #
 # see `virtiofsd -h` for possible options.
-virtio_fs_extra_args = ["--thread-pool-size=1"]
+virtio_fs_extra_args = ["--thread-pool-size=1", "-o", "flock"]
 
 # Cache mode:
 #
```

# Actual result

When deploying the following example on Kubernetes, you can see in the logs of the two Pods that both seemlingly hold the lock simultaneously.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lock
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      component: test
  template:
    metadata:
      labels:
        component: test
    spec:
      runtimeClassName: kata
      containers:
        - name: debian
          image: debian
          command:
            - bash
            - -c
            - |
              die() {
                  echo "*** $*" 1>&2
                  exit 1
              }

              set -e

              echo "Acquiring lock..."
              exec 42>/lock/lockfile || die "Failed to access lock"
              flock -w 120 42 || die "Timeout waiting for lock" # does NOT work with kata

              echo "Starting sleep ..."
              for i in {1..20}; do sleep 1; echo $i; done
              echo "Done."

              # Lock released by process exit
          volumeMounts:
            - name: lock
              mountPath: /lock
      volumes:
        - name: lock
          persistentVolumeClaim:
            claimName: lock
```
