### ISSUE TITLE
memory hotplug on aarch64 with nvdimm may not work for now on kubernetes

### ISSUE THREAD

**Issue by Bevisy** [kata-containers/kata-containers#3426]
- kata version 2.2.3 (Both qemu and shim are compiled from the source branch v2.2.3 on aarch64)
- containerd 1.4.6
---
use configuration.toml to enable nvdimm (default configuration)
```sh
disable_image_nvdimm = false
pflashes = ["/usr/share/kata/kata-flash0.img", "/usr/share/kata/kata-flash1.img"]
```
We can find pod running, but limits.memory is not working. Error logs as below:
```log
vmconsole="[    5.097973] Block size [0x40000000] unaligned hotplug range: start 0xe0000000, size 0x80000000"
vmconsole="[    5.097980] acpi PNP0C80:01: add_memory failed"
vmconsole="[    5.100349] acpi PNP0C80:01: acpi_memory_enable_device() error"
vmconsole="[    5.101364] acpi PNP0C80:01: Enumeration failure"
```

When using configuration.toml to disable nvdimm
```sh
disable_image_nvdimm = true
pflashes = ["/usr/share/kata/kata-flash0.img", "/usr/share/kata/kata-flash1.img"]
```
We can find pod running, and limits.memory setting takes effect.

So it looks like memory hotplug using nvdimm may not work now on aarch64.

---
the pod yaml
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: test-kata
  labels:
    app: test-kata
  annotations:
    # io.katacontainers.config.hypervisor.kernel: ""
    # io.katacontainers.config.hypervisor.image: ""
spec:
  runtimeClassName: rune
  containers:
  - name: test
    image: nginx:1.13
    resources:
      limits:
        memory: 2Gi
EOF
```
/cc @jongwu
