### ISSUE TITLE
v2 Kata agent allocating a tty even though container is non-interactive

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#3518]
/dev/tty is allocated and live with the v2 agent even when using a standard non-interactive container. This is different behavior than the v1 agent as well as regular runc. This was confirmed in all 2.2 and 2.3.1 agents with our internal builds which are using alpine as the guest os however I believe the problem is not specific to our build.

--

We have a customer using [sbt](https://www.scala-sbt.org/) for a scala build. Under the covers this tools can operate interactively and does a check to see if /dev/tty is "live", and if so tries to configure it. Since a kube process is actually a background process this ends up resulting in a SIGTTOU which suspends the process sequence ultimately hanging the build process. More info [here](http://curiousthing.org/sigttin-sigttou-deep-dive-linux) 

Our parent process should be fixed to handle this signal similar to work done for tini however this worked correctly with the v1 agent and is currently breaking our customer's use.

Here's a minimal pod to illustrate...
```
apiVersion: v1
kind: Pod
metadata:
  name: untrusted-sbt-min
spec:
  containers:
    - name: sbt
      image: hseeberger/scala-sbt:8u265_1.3.13_2.12.12
      imagePullPolicy: Always
      command: ["sh", "-c"]
      args:
        - ls -al /dev/tty && sh -c "stty -g < /dev/tty"
      #stdin: true
      #tty: true
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
  restartPolicy: Never
  runtimeClassName: kata-qemu
  ```
  
  When run this logs...
  ```
  $ k logs untrusted-sbt-min 
crw-rw-rw- 1 root root 5, 0 Jan 20 20:59 /dev/tty
500:5:4bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
```
... which is incorrect as the tty should not be allocated.

 If you remove the `runtimeClassName` or use a v1 agent you will get...
```
$ k logs untrusted-sbt-min 
crw-rw-rw- 1 root root 5, 0 Jan 20 20:59 /dev/tty
sh: 1: cannot open /dev/tty: No such device or address
```
... which is correct as the tty should not be allocated and live.

If you now uncomment the `stdin: true` and `tty: true` while using runc or a v1 agent and re-run you will get...
```
$ k logs untrusted-sbt-min 
crw-rw-rw- 1 root root 5, 0 Jan 20 21:09 /dev/tty
500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
```
... which makes sense as we do want the tty allocated.

**Comment by fidencio** [comment]
It seems that the agent is purposefully opening `/dev/tty`, see: https://github.com/kata-containers/kata-containers/blob/618aa659d652a18f1fcd9b43f5dc9bdc15d6904b/src/agent/rustjail/src/container.rs#L163-L171 and it seems to be like that since f8ced638d253bbae63d2cdfc35eb873dfb547e59.

/cc @lifupan @liubin, the patch to be proposed is a quite simple one, but what's the intention for having `/dev/tty` opened by default?

**Comment by skaegi** [comment]
Hmm... if there is a simple patch for this I'd be happy to rebuild and try it.

 I looked briefly at the code and I think the creation of the device is what I'd expect... the connecting up also looked correct here... https://github.com/kata-containers/kata-containers/blob/618aa659d652a18f1fcd9b43f5dc9bdc15d6904b/src/agent/rustjail/src/container.rs#L675-L679
 ...  unless something like the deserialization was busted.

@lifupan I'm happy to write the tests here. Let me know if there is there anything I could to do to help.

**Comment by lifupan** [comment]
Hi @skaegi 

It's weird, I had tried with kata-2.3.0 and I couldn't reproduce this issue. I used the following pod yaml:

lifupan@kant-server:~$ cat pod.yaml 
```
apiVersion: v1
kind: Pod
metadata:
  name: untrusted-sbt-min
spec:
  containers:
    - name: sbt
      image: ubuntu:latest
      imagePullPolicy: Always
      command: ["sh", "-c"]
      args:
        - ls -al /dev/tty && sh -c "stty -g < /dev/tty"
          #stdin: true
          #tty: true
  restartPolicy: Never
  runtimeClassName: kata
```

and I actually got the following logs with: 
lifupan@kant-server:~$ sudo kubectl logs untrusted-sbt-min 

```
crw-rw-rw- 1 root root 5, 0 Jan 25 12:23 /dev/tty
sh: 1: cannot open /dev/tty: No such device or address
```
