### ISSUE TITLE
Application coredumps doesn't work on Kata containers by default

### ISSUE THREAD

**Issue by bpradipt** [kata-containers/kata-containers#3562]
# Description of problem

The default setting for process core dumps in Kata initrd points to helper program which is non-existent
For example in Fedora rootfs it’s set to `|/usr/lib/systemd/coredump-wrapper %E %P %u %g %s %t %c %h %e`

The helpers are not present in the initrd and consequently application core dumps are not generated by default.

It's possible for end user to set the coredump location by creating a privileged container and modify the 
# Expected result

Application coredump saved in the container.

# Actual result

No coredump generated

# Further information

I can think of two potential solutions:

- Include coredump helper (eg. systemd-coredump) in the Kata initrd
   
   Even if we decide to add the helper to the Kata VM, the container might not be able to access the coredump file due to permission issues. For example when using the `systemd-coredump` helper the core dump will be saved under "/var/lib/systemd/coredump", and this path might not be present in the container rootfs. Also adding additional binaries to the VM will increase the size of the boot image.

- Add a sysctl setting in the initrd to ensure core-dump file is in the current directory where the application crashed
For eg adding `kernel.core_pattern=core.%P.%u.%g.%s.%t.%c.%h.%e'` to sysctl settings in initrd

   This might be a good default which will at least provide coredumps out-of-the-box.

   Setting the pattern to a well-defined directory present in every container rootfs is also not guaranteed to work for all the cases. 
   For example setting the location to root directory(“/”) will not work for containers running with non-root userid as the app won’t have write permissions to the root directory and dump will not be generated.

**Comment by houstar** [comment]
How to persist the coredump file  if application crashed and the container was destroyed ?

**Comment by Jakob-Naucke** [comment]
@bpradipt Interesting question from @houstar. Are we (for now anyway) okay with just having it in the container, effectively depending on the container remaining alive? (which probably won't work for most containers out there when their applications crash)

**Comment by bpradipt** [comment]
@houstar @Jakob-Naucke, there are different use cases for core dumps 
1. For development inside the container. Start container with dev tools inside Kata, debugging the crashed application. Not possible today without provisioning a privileged container and changing the `core_pattern`
2. A container running different processes and one of them crashed. The container is still running. Debugging the crashed application is not possible today without provisioning a privileged container and changing the `core_pattern`3.
3. Persisting core dumps outside of the container for later usage. For this case, the solution available today is to mount a persistent volume and change the `core_pattern` as needed. An example yaml explaining the approach
```
apiVersion: v1
kind: Pod
metadata:
  name: example-fedora-kata
  labels:
    app: example-fedora-app-kata
  namespace: default
spec:
  containers:
    - name: example-fedora-kata
      image: quay.io/bpradipt/crash
      ports:
        - containerPort: 8080
      command: ["python3"]
      args: [ "-m", "http.server", "8080"]
      volumeMounts:
        - mountPath: "/core-dump"
          name: task-pv-storage
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: kata-dump
    runtimeClassName: kata
```
Either the core dump path can be set by the application itself (requires privileged container) or a privileged sidecar container can set the required path. 

For 1,2 we can ensure Kata provides a workable out-of-box experience by having the proper setting in the initrd.
For 3, imho it has to be left to the end-user to decide on the suitable path for saving coredump.

One approach that might work for all three cases and avoid end-user fiddling with the setting is to have Kata runtime create a well-defined path available in the container to save core dumps and which is accessible to the current running USER. For example `/tmp/core`. If the end-user needs to persist it, then they can mount a PV to this path.
Currently I don't know how feasible it is.
