### ISSUE TITLE
Kata does not correctly mount 1Gi hugepage resources

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#3743]
# Description of problem

Deploy the following yaml on a Kubernetes cluster with kata installed and several 1GiB hugepages allocated:
```
apiVersion: v1
kind: Pod
metadata:
  name: hugepage-1g
  namespace: default
spec:
  containers:
  - name: test
    image: quay.io/libpod/busybox:latest
    securityContext:
      capabilities:
        add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"] 
    volumeMounts:
    - mountPath: /dev/hugepages 
      name: hugepage
    resources:
      limits:
        memory: "1Gi"
        cpu: "1" 
        hugepages-1Gi: "4Gi" 
      requests:
        memory: "1Gi"
        cpu: "1"
        hugepages-1Gi: "4Gi"
    command: ["/bin/sh", "-c", "echo Running... && sleep infinity"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
---
apiVersion: v1
kind: Pod
metadata:
  name: hugepage-1g-kata
  namespace: default
spec:
  runtimeClassName: kata-qemu
  containers:
  - name: test
    image: quay.io/libpod/busybox:latest
    securityContext:
      capabilities:
        add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"] 
    volumeMounts:
    - mountPath: /dev/hugepages 
      name: hugepage
    resources:
      limits:
        memory: "1Gi"
        cpu: "1" 
        hugepages-1Gi: "4Gi" 
      requests:
        memory: "1Gi"
        cpu: "1"
        hugepages-1Gi: "4Gi"
    command: ["/bin/sh", "-c", "echo Running... && sleep infinity"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
```

This yaml is intended to create two pods, one with kata, one with runc, but otherwise identical, each with a mount of 1GiB hugepages on `/dev/hugepages`.

# Expected result

Both pods get usable 1GiB hugepage mounts on `/dev/hugepages`.

# Actual result

The runc pod gets a 1GiB hugepage mount as expected:

```
# kubectl exec hugepage-1g -- grep hugetlbfs /proc/mounts
nodev /dev/hugepages hugetlbfs rw,seclabel,relatime,pagesize=1024M 0 0
```

However, the kata pod incorrectly gets a 2MiB hugepage mount instead:

```
# kubectl exec  hugepage-1g-kata -- grep hugetlbfs /proc/mounts
nodev /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
```

Additionally the Kata VM kernel appears to have no hugepages allocated, of either 2MiB *or* 1GiB size:

```
# kubectl exec  hugepage-1g-kata -- cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
0
# kubectl exec  hugepage-1g-kata -- cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
0
```
(equivalent commands are not relevant for the non-kata container, since it will show host values).
