### ISSUE TITLE
Kata does not allocate hugepages within guest

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#3752]
# Description of problem

Deploy the following yaml on a Kubernetes cluster with kata installed and plenty of 2MiB hugepages allocated:
```
`piVersion: v1
kind: Pod
metadata:
  name: hugepage-2m
  namespace: default
spec:
  containers:
  - name: test
    image: quay.io/libpod/busybox:latest
    securityContext:
      capabilities:
        add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
        hugepages-2Mi: "1Gi"
      requests:
        memory: "1Gi"
        cpu: "1"
        hugepages-2Mi: "1Gi"
    command: ["/bin/sh", "-c", "echo Running... && sleep infinity"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
---
apiVersion: v1
kind: Pod
metadata:
  name: hugepage-2m-kata
  namespace: default
spec:
  runtimeClassName: kata-qemu
  containers:
  - name: test
    image: quay.io/libpod/busybox:latest
    securityContext:
      capabilities:
        add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
        hugepages-2Mi: "1Gi"
      requests:
        memory: "1Gi"
        cpu: "1"
        hugepages-2Mi: "1Gi"
    command: ["/bin/sh", "-c", "echo Running... && sleep infinity"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
```

This yaml is intended to create two pods, one with kata, one with runc, but otherwise identical, each with a mount of 2MiB hugepages on `/dev/hugepages`.

# Expected result

Both pods can use 2MiB hugepages.

# Actual result

The runc pod can use hugepages as expected.

The kata pod does correctly have a hugepage mountpoint:

```
# kubectl exec hugepage-2m-kata -- grep hugetlbfs /proc/mounts
nodev /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
```

However, the Kata VM has no hugepages allocated:

```
# kubectl exec  hugepage-2m-kata -- cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
0
# kubectl exec  hugepage-2m-kata -- cat /proc/meminfo
MemTotal:        4127988 kB
MemFree:         4059740 kB
MemAvailable:    4021300 kB
Buffers:             620 kB
Cached:             1468 kB
SwapCached:            0 kB
Active:              684 kB
Inactive:           4464 kB
Active(anon):         52 kB
Inactive(anon):     3044 kB
Active(file):        632 kB
Inactive(file):     1420 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:          3008 kB
Mapped:              940 kB
Shmem:                40 kB
KReclaimable:       1836 kB
Slab:              11672 kB
SReclaimable:       1836 kB
SUnreclaim:         9836 kB
KernelStack:        1872 kB
PageTables:          240 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2063992 kB
Committed_AS:      13332 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        2540 kB
VmallocChunk:          0 kB
Percpu:            15872 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:       24444 kB
DirectMap2M:     3383296 kB
DirectMap1G:     1048576 kB
```

# Further info

I first noted this in #3743, however it appears to affect all hugepage requests with kata, essentially making hugepages unusable.  I'll leave #3743 tracking just the problem with the mountpoint, which does appear to be specific to 1GiB (or at least non-default-size) hugepages.
