### ISSUE TITLE
Different behaviors for emptydir in runc and kata containers

### ISSUE THREAD

**Issue by fengwang666** [kata-containers/kata-containers#3779]
We noticed the kubernetes `emptydir` volume shows different behaviors in runc and kata containers. In `runc` containers, the emptydir files are written back to the `/var/lib/kubelet/pods/[pod_id]` folder, for example:
```
root:/var/lib/kubelet/pods/ba30cbb1-50f5-4e16-a331-cc04e2c4f15f/volumes/kubernetes.io~empty-dir/runc-volume# ls
test.txt
```
But for `kata` containers, the same folder is empty. For example:
 ```
root:/var/lib/kubelet/pods/75d391dc-eb48-4c34-bf31-a14461d18ccc/volumes/kubernetes.io~empty-dir/data-volume# ls
```
There is also a difference on the pause container containerd rootfs folder.
For `kata`, the emptydir data is written to a `local` folder:
```
root:/run/containerd/io.containerd.runtime.v2.task/k8s.io/c36c142e6444f25545875dc6d233f4e24541da04467c967715dc5af7f6e51971/rootfs/local/data-volume# ls
data.txt
```
For `runc`, the `local` folder doesn't even exist:
```
root:/run/containerd/io.containerd.runtime.v1.linux/k8s.io/87c1c2a4447ab27fb05549a7f09cfb5230387325899e5c59cd1793903327d008/rootfs# ls
dev  etc  pause  proc  sys
```

Is this a bug or expected behavior change between runtime.v1 and runtime.v2? We have some existing behavior reading the emptydir content from the kubelet folder and now it's broken with kata containers. 


This can be easily reproduced with the following spec:
kata pod spec:
```
 apiVersion: v1                                                                                                                                                                                                                                                                                                              
 kind: Pod                                                                                                                                                                                                                                                                                                                   
 metadata:                                                                                                                                                                                                                                                                                                                   
   name: kata-test                                                                                                                                                                                                                                                                                                
   labels:                                                                                                                                                                                                                                                                                                                   
     app: test                                                                                                                                                                                                                                                                                                           
 spec:                                                                                                                                                                                                                                                                                                                       
   runtimeClassName: kata-qemu                                                                                                                                                                                                                                                                                               
   containers:                                                                                                                                                                                                                                                                                                               
   - name: test                                                                                                                                                                                                                                                                                                          
     image: ubuntu                                                                                                                                                                                                                                                                                                           
     command: ['/bin/sh', '-c', 'sleep infinity']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
     volumeMounts:                                                                                                                                                                                                                                                                                                           
     - mountPath: /data                                                                                                                                                                                                                                                                                                      
       name: data-volume                                                                                                                                                                                                                                                                                                     
   volumes:                                                                                                                                                                                                                                                                                                                  
   - name: data-volume                                                                                                                                                                                                                                                                                                       
     emptyDir: {}  
```

runc pod spec:
```
 apiVersion: v1                                                                                                                                                                                                                                                                                                              
 kind: Pod                                                                                                                                                                                                                                                                                                                   
 metadata:                                                                                                                                                                                                                                                                                                                   
   name: runc-test                                                                                                                                                                                                                                                                                                 
   labels:                                                                                                                                                                                                                                                                                                                   
     app: test                                                                                                                                                                                                                                                                                                           
 spec:                                                                                                                                                                                                                                                                                                                       
   containers:                                                                                                                                                                                                                                                                                                               
   - name: test                                                                                                                                                                                                                                                                                                          
     image: ubuntu                                                                                                                                                                                                                                                                                                           
     command: ['/bin/sh', '-c', 'sleep infinity']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
     volumeMounts:                                                                                                                                                                                                                                                                                                           
     - mountPath: /data2                                                                                                                                                                                                                                                                                                     
       name: runc-volume                                                                                                                                                                                                                                                                                                     
   volumes:                                                                                                                                                                                                                                                                                                                  
   - name: runc-volume                                                                                                                                                                                                                                                                                                       
     emptyDir: {} 
```
