### ISSUE TITLE
Agent attempts to allocate hugepages before memory is hotplugged into sandbox

### ISSUE THREAD

**Issue by dgibson** [kata-containers/kata-containers#3839]
# Description of problem

On a Kubernetes cluster with Kata deployed, try making a pod with the following yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: hugepage-2m-kata
  namespace: default
spec:
  runtimeClassName: kata-qemu
  containers:
  - name: test
    image: quay.io/libpod/busybox:latest
    securityContext:
      capabilities:
        add: ["IPC_LOCK","SYS_RESOURCE","NET_RAW"] 
    volumeMounts:
    - mountPath: /dev/hugepages 
      name: hugepage
    resources:
      limits:
        memory: "1Gi"
        cpu: "1" 
        hugepages-2Mi: "4Gi" 
      requests:
        memory: "1Gi"
        cpu: "1"
        hugepages-2Mi: "4Gi"
    command: ["/bin/sh", "-c", "while :; do date; grep hugetlbfs /proc/mounts; cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages; sleep 1; done"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
```

Use the default values in `configuration.toml`, which in particular has:

```
[hypervisor.qemu]
. . .
default_memory = 2048
```

# Expected result

Container is started with 1GiB of normal memory and 4GiB of hugepage memory, accessible via `/dev/hugepages`, similar to a runc container.  All of the 4GiB hugepages should be allocateable by the workload.

# Actual result

Only a little under 2GiB of hugepage memory is allocated within the guest (in my tests, 960 or 961 2MiB pages, instead of the requested 2048).

If using my extra error checking patches from #3766, this will result in an explicit error during container startup.  If not the container will start, but attempting to actually allocate hugepages within the workload will run out before it is supposed to.

# Further information

Hugepages are allocated by `allocate_hugepages` which is called during the CreateContainer agent RPC call ([runtime] `AgentService::create_container` → `AgentServce::do_create_container` → `add_storages` → `ephemeral_storage_handler` → `handle_hugetlbfs_storage` → `allocate_hugepages`).

On the runtime side the CreateContainer RPC call happens at the `c.create()` call in `CreateContainer`.   Only *after* this do we call `updateResources` → `s.hypervisor.ResizeMemory` → `HotplugAddDevice` which actually hotplus memory for the new container to the sandbox VM.

So, we're trying to allocate hugepages within the guest before we've attached the memory which will be used to back the hugepages.  Obviously that's not going to work; it only works by accident if there are relatively small hugepage allocations which can be "borrowed" from the sandbox's overhead memory (2GiB by default) then replaced when the hotplug occurs.

The agent doesn't get any explicit notification for when the memory hotplug is completed.  There are at least two calls to the OnlineCPUMem RPC, but this contains little information and at least one occurs before the memory hotplug.  It's probably reasonable to assume that the hotplug is complete once the StartContainer RPC is issued, though.

/cc @liubin @bpradipt
