### ISSUE TITLE
Failed to write to /etc/resolv.conf in kubernetes Pod running with kata

### ISSUE THREAD

**Issue by lining2020x** [kata-containers/kata-containers#3896]
# Description of problem
Failed to write to /etc/resolv.conf in kata container.

```
root@ubuntu-r:~# kubectl  exec -ti   test-kata-vdnxl  -- sh -c "echo test >> /etc/resolv.conf"
sh: 1: cannot create /etc/resolv.conf: Read-only file system
command terminated with exit code 2

root@ubuntu-r:~# kubectl  exec -ti   test-kata-vdnxl  -- mount |grep kataShare
kataShared on / type virtiofs (rw,relatime)
kataShared on /etc/hosts type virtiofs (rw,relatime)
kataShared on /dev/termination-log type virtiofs (rw,relatime)
kataShared on /etc/hostname type virtiofs (rw,relatime)
kataShared on /etc/resolv.conf type virtiofs (rw,relatime)
kataShared on /run/secrets/kubernetes.io/serviceaccount type virtiofs (ro,relatime)

root@ubuntu-r:~# kubectl  exec -ti   test-kata-vdnxl  -- ls -al /etc/resolv.conf
-rw-r--r-- 1 root root 103 Mar 15 07:36 /etc/resolv.conf
```

# Expected result
Succeed to write to ` /etc/resolv.conf`

# Actual result
Failed to write to `/etc/resolv.conf`

# Further information
Versions:
- Kubernetes v1.23.4
- Containerd v1.5.10
- Kata Containers v2.3.3
- OS/Kernel: ubuntu 20.04/5.13.0-35-generic

**Comment by lining2020x** [comment]
Here is my test pod yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-kata
spec:
  selector:
    matchLabels:
      name: test-kata
  template:
    metadata:
      labels:
        name: test-kata
    spec:
      runtimeClassName: kata-qemu
      containers:
      - name: kata-pod
        image: debian:buster
        command: ["tail", "-f", "/dev/null"]
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
```
