### ISSUE TITLE
Kata shim leak due to container process unclean exit inside guest 

### ISSUE THREAD

**Issue by fengwang666** [kata-containers/kata-containers#3913]
Recently we observed a failure scenario where kata shim leaks because the container fails to exit. 

### *A normal container exit sequence*:

In the [stopContainer()](https://github.com/containerd/containerd/blob/main/pkg/cri/server/container_stop.go#L60) method inside cri server, it sends signal ([SIGTERM](https://github.com/containerd/containerd/blob/main/pkg/cri/server/container_stop.go#L151) and [SIGKILL](https://github.com/containerd/containerd/blob/main/pkg/cri/server/container_stop.go#L174)) to stop the task and then [wait](https://github.com/containerd/containerd/blob/main/pkg/cri/server/container_stop.go#L179) for a [TaskExit](https://github.com/containerd/containerd/blob/0c701654a1f496d73cb414c7b30b03ee4d115b18/pkg/cri/server/events.go#L365) event to confirm the container has exited successfully. In the case of Kata Container, both `task.Kill()` and `waitContainerStop()` methods eventually translate into grpc requests to the kata agent. 

When a container is started, the shim also starts a [wait](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/start.go#L91) goroutine to reap the container when it exits. The wait goroutine normally is blocked by the [exitIOch](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/wait.go#L33) channel. The shim keeps [three goroutines](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/stream.go#L89) to copy the stdin, stdout and stderr between the container process inside the guest and shim. The `exitIOch` channel is closed when the ioCopy is stopped, which in turn unblocks the wait method and allows it to call [waitProcess](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/wait.go#L46) to reap the process inside the guest VM. 

### *Failure Scenario*:

Previously we have seen ESRCH error not handled in the kill method, which is fixed [here](https://github.com/kata-containers/kata-containers/commit/aa5ae6b17c688a3fa22c28d1ec3a71a6cabb9c57). 
However, after adressing ESRCH, now the container exit is stuck at waiting for the taskExit event. 
`Mar 13 16:43:35 aks-c17f7be0f8e2-25985862-vmss00000H containerd[6780]: time="2022-03-13T16:43:35.477125396Z" level=error msg="StopPodSandbox for \"3291cd957c1908e26d696ca7a5bed3519d2e205c9b3b9d3e02758d5520e38c33\" failed" error="rpc error: code = Canceled desc = failed to stop container \"99d48ee20441ecd19dda143cca986bfaf6979defb72f627c6572df7836a1ac9a\": an error occurs during waiting for container \"99d48ee20441ecd19dda143cca986bfaf6979defb72f627c6572df7836a1ac9a\" to be killed: wait container \"99d48ee20441ecd19dda143cca986bfaf6979defb72f627c6572df7836a1ac9a\": context canceled"
`
Tracing the code paths eventually leads to a suspicion that the [wait](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/wait.go#L33) goroutine is blocked by the `exitIOch`.  Potentially the[ io goroutines](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/stream.go#L89) are not closed properly.  

This hypothesis is supported by the fact that I didn't see any "[wait process](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L439)" log printed by the [do_wait_process() ](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L425)method in the kata agent `rpc.rs`. Because `do_wait_process` is not called, the container process is never [fully cleaned](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L489) even though it has exited.  

The kubelet will keep retrying stop the container, which causes [StopContainer()](https://github.com/containerd/containerd/blob/main/pkg/cri/server/container_stop.go#L37) invoked repeatedly. And the previously mentioned [signal](https://github.com/containerd/containerd/blob/main/pkg/cri/server/container_stop.go#L151) and [wait](https://github.com/containerd/containerd/blob/main/pkg/cri/server/container_stop.go#L160) codepath will be hit again and again. However, since the real container process has already exit, there is not a way to recover. 

**There are two issues:**
1. There might be a bug somewhere that causes [io copy streams](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/stream.go#L89-L131) not close properly when a container process exits. It might be a race condition and I haven't been able to fully root cause it yet.
2. When it enters this bad state, there is NOT a way the kata agent can recover. I have made a PR to address this.

**Comment by fengwang666** [comment]
@liubin @Tim-Zhang @bergwolf Can you please take a look? It seems you guys have been the main authors of the kata agent.
Also cc @egernst

**Comment by sameo** [comment]
@fengwang666 FWIW, our `iocopy` implementation is most likely a copy of [containerd's](https://github.com/containerd/containerd/blob/main/cio/io_unix.go#L56). There's a subtle difference though: containerd's implemenation does not add the container's `stdin` to the `wg` sync.

**Comment by fengwang666** [comment]
Two things worth calling out: 
1. The container uses fuse mount;
2. It also uses nohup to redirect stdout/stderr.
But still not sure whether/how they can cause read hang.

**Comment by fengwang666** [comment]
Okay. I'm able to reliably reproduce it. Unfortunately this seems to be a bug in Kata related to `shareProcessNamespace`. The container does not exit cleanly and prevents shim from shutting down when the `shareProcessNamespace` is set to true and there are more than one long running processes. Based on the logs I added locally, the exit code path is blocked in reading the [stdout](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/rpc.rs#L1472). In this case, no EOF is returned even though the container init process has exited. My suspicion is, it has something to do with the pause container being the init process (pid 1) when `shareProcessNamespace` is set to `true`. But I don't know exactly what happened yet. 

Here is a simple pod spec to reproduce it:
```
apiVersion: apps/v1                                                                                                                                                                            
 kind: Deployment                                                                                                                                                                               
 metadata:                                                                                                                                                                                      
   name: shim-test                                                                                                                                                                              
 spec:                                                                                                                                                                                          
   replicas: 1 # tells deployment to run 2 pods matching the template                                                                                                                           
   selector:                                                                                                                                                                                    
     matchLabels:                                                                                                                                                                               
       app: shim-test                                                                                                                                                                           
   template:                                                                                                                                                                                    
     metadata:                                                                                                                                                                                  
       labels:                                                                                                                                                                                  
         app: shim-test                                                                                                                                                                         
     spec:                                                                                                                                                                                                                                                                                                                                                 
       shareProcessNamespace: true                                                                                                                                                              
       runtimeClassName: kata-qemu
       containers:                                                                                                                                                                              
         - name: testcontainer3                                                                                                                                                                 
           image: ubuntu                                                                                                                                                                        
           command: ["/bin/bash","-c","sleep 1800 && tail -f /dev/null"]                                                                                                                        
           resources:                                                                                                                                                                           
             limits:                                                                                                                                                                            
               memory: "4Gi"                                                                                                                                                                    
             requests:                                                                                                                                                                          
               memory: "1Mi"
```

cc @sameo @egernst @bergwolf @fidencio
