### ISSUE TITLE
Pods stuck "Terminating" when using Kata 2.4.0 + CLH 0.22.1

### ISSUE THREAD

**Issue by skaegi** [kata-containers/kata-containers#4043]
We've been testing the Kata 2.4.0 release tag with our built equivalent of kata-deploy and have noticed that after running with moderate load in our CI/CD clusters where pods come and go regularly that we get into a state where pods are stuck "Terminating". Pods are "running" fine and performing correctly... they just seem to get stuck when the pods are being deleted/stopped.

Here's a sample of what we see...
```
$ k get po -A -owide | grep pw-
pw-52efae9d-2ca3-4f8e-ac30-72a9931dd41d   consumption-monitor-run-r974n-simple-tekton-pipeline-jnhb-2wspf   0/1     Terminating        0          7m19s   172.30.192.49    10.101.101.101   <none>           <none>
pw-73622c77-a269-43d1-82cc-eeb474e03c8c   pipelinerun-73622c77-a269-43d1-82cc-eeb474e03c8c-pipeline-s2xtd   0/2     Terminating        0          7m19s   172.30.187.210    10.101.101.102      <none>           <none>

on node...
# ps aux | grep opt/kat
root     150683  0.8  0.1 1413460 39216 ?       Sl   21:09   0:00 /opt/kata/bin/containerd-shim-kata-v2 -namespace k8s.io -address /run/containerd/containerd.sock -publish-binary /usr/local/bin/containerd -id 937e8d714b71a7a430a0a949ad836f8a4f8133f884511a3e98bbae43a42b132a
root     150691  0.0  0.0  76412  1896 ?        Sl   21:09   0:00 /opt/kata/bin/virtiofsd --syslog -o cache=auto -o no_posix_lock -o source=/run/kata-containers/shared/sandboxes/937e8d714b71a7a430a0a949ad836f8a4f8133f884511a3e98bbae43a42b132a/shared --fd=3 -f --thread-pool-size=1 -o announce_submounts -o xattr -o modcaps=+sys_admin -o allow_direct_io --rlimit-nofile=524288
root     150704  3.7  0.5 4357844 184232 ?      Sl   21:09   0:00 /opt/kata/bin/cloud-hypervisor --api-socket /run/vc/vm/937e8d714b71a7a430a0a949ad836f8a4f8133f884511a3e98bbae43a42b132a/clh-api.sock
root     150718  0.0  0.0 4491912 1732 ?        Sl   21:09   0:00 /opt/kata/bin/virtiofsd --syslog -o cache=auto -o no_posix_lock -o source=/run/kata-containers/shared/sandboxes/937e8d714b71a7a430a0a949ad836f8a4f8133f884511a3e98bbae43a42b132a/shared --fd=3 -f --thread-pool-size=1 -o announce_submounts -o xattr -o modcaps=+sys_admin -o allow_direct_io --rlimit-nofile=524288

```

We saw this when using CLH and I didn't think to test QEMU to help narrow before rolling back to Kata 2.3.3 + CLH 0.21.0 although we are still sticking with the 5.15 kernel which has been stable for us and needed for other reasons. Our host in this case is Ubuntu 18.04.6 LTS running 4.15 -- containerd v1.5.10 -- and using block-storage as the basis of our guest as well as virtiofs (C) from QEMU 6.2.0 which has been stable for us for a long time. I'm unfortunately not able to go back to trying Kata 2.4.x for more testing (like trying QEMU) until next week but wanted to at least log an issue and provide any info I can.

**Comment by fidencio** [comment]
Assigning to myself as I will take a look at this Today / Tomorrow.

**Comment by fidencio** [comment]
Okay, I was able to reproduce this one and this is the backtrace I'm getting:
```
"thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', rustjail/src/cgroups/fs/mod.rs:593:31"
"stack backtrace:"
"   0:     0x7f0390edcc3a - std::backtrace_rs::backtrace::libunwind::trace::hd5eff4de16dbdd15"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5"
"   1:     0x7f0390edcc3a - std::backtrace_rs::backtrace::trace_unsynchronized::h04a775b4c6ab90d6"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5"
"   2:     0x7f0390edcc3a - std::sys_common::backtrace::_print_fmt::h3253c3db9f17d826"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5"
"   3:     0x7f0390edcc3a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h02bfc712fc868664"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22"
"   4:     0x7f0390a91fbc - core::fmt::write::hfd5090d1132106d8"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17"
"   5:     0x7f0390edb804 - std::io::Write::write_fmt::h34acb699c6d6f5a9"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15"
"   6:     0x7f0390edbee0 - std::sys_common::backtrace::_print::hfca761479e3d91ed"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5"
"   7:     0x7f0390edbee0 - std::sys_common::backtrace::print::hf666af0b87d2b5ba"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9"
"   8:     0x7f0390edbee0 - std::panicking::default_hook::{{closure}}::hb4617bd1d4a09097"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50"
"   9:     0x7f0390edb2da - std::panicking::default_hook::h84f684d9eff1eede"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9"
"  10:     0x7f0390edb2da - std::panicking::rust_panic_with_hook::h8e784f5c39f46346"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17"
"  11:     0x7f0390f0c416 - std::panicking::begin_panic_handler::{{closure}}::hef496869aa926670"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:500:13"
"  12:     0x7f0390f0c3b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h8e9b039b8ed3e70f"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18"
"  13:     0x7f0390f0c372 - rust_begin_unwind"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5"
"  14:     0x7f03909062c0 - core::panicking::panic_fmt::h568976b83a33ae59"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14"
"  15:     0x7f039090641c - core::panicking::panic::he2e71cfa6548cc2c"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5"
"  16:     0x7f0390eb443f - <rustjail::cgroups::fs::Manager as rustjail::cgroups::Manager>::get_stats::h85031fc1c59c53d9"
"  17:     0x7f03909c0138 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfa6e6cd7516f8d11"
"  18:     0x7f0390d697e5 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hffbaa534cfa97d44"
"  19:     0x7f039099c0b3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hae3ab083a06d0b4b"
"  20:     0x7f0390af9e1e - std::panic::catch_unwind::h1fdd25c8ebba32e1"
"  21:     0x7f0390b7c4e6 - tokio::runtime::task::raw::poll::hd3ebbd0717dac808"
"  22:     0x7f0390f49f3f - tokio::runtime::thread_pool::worker::Context::run_task::hfdd63cd1e0b17abf"
"  23:     0x7f0390f3a599 - tokio::runtime::task::raw::poll::h62954f6369b1d210"
"  24:     0x7f0390f37863 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1c58f232c078bfe9"
"  25:     0x7f0390f4f3dd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h2d329a84c0feed57"
"  26:     0x7f0390f0e535 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h137e5243c6233a3b"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694:9"
"  27:     0x7f0390f0e535 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7331c46863d912b7"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694:9"
"  28:     0x7f0390f0e535 - std::sys::unix::thread::Thread::new::thread_start::h1fb20b966cb927ab"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/thread.rs:106:17"
```

**Comment by Champ-Goblem** [comment]
Hello there. We are also experiencing pods stuck in a terminating state. This is having an impact on stateful workloads that we deploy with PVs setup via GKE’s CSI driver.

#### Manual resolution we have found involves:
Killing the PID of the cloud hypervisor sandbox, followed by unmounting the associated PV volume on the host.



#### We are running:
OS: Flatcar Linux (kernel 5.15.26)
Containerd: 1.5.10
KataVM: 2.3.3 with kernel 5.15.26
Cloud Hypervisor: 21.0
GKE: 1.21.9+gke.300



#### What we experience specifically:
This problem doesn't happen consistently, the majority of terminating pods are killed in sufficient time and do not get stuck in a terminating state. We seem to experience this problem the most with stateful workloads such as databases that have a PVC attached. When the delete command is issued through Kubernetes we see the pod entering a `Terminating` phase and never leaves/takes far longer than the terminating grace period to be killed. Kubernetes force deletion doesn't allow for the new pod to start due to the PVC already being mounted and locked by another process and thus requires a PID kill to be resolved.

#### Our debugging efforts have found:
We have been unable to reproduce the issue ourselves by neither starting and terminating pods in batches, or killing a database under load. So far it seems to be either random or related to specific circumstances we have yet to identify. 

Also, on a side note, during our debugging we identified a separate and potentially unrelated discrepancy with how Kata issues Unix signals to the process when compared to runC. I wrote a quick NodeJS script to log all available signals received and essentially ignore them, mostly to investigate how the container stop is handled. In runC the logs for the pod show:
```
Waiting for signals
Got TERM
```
Where the `Got TERM` is issued almost instantly after the deletion request is sent, this then stays around for another 30s before finally being killed and exiting.
In kata this seems to be handled slightly different, the same workload shows:
```
Waiting for signals
```
There is no output that indicates a SIGTERM signal like runC and the time between the deletion request and the container stopping is around 1-2s rather than 30s as defined in the termination grace period seconds. This could potentially impact stateful workloads that require the SIGTERM signal to shutdown properly. We understand this may be a completely separate issue so will be happy to open a new ticket if required.

@fidencio @skaegi

**Comment by fengwang666** [comment]
@Champ-Goblem We recently fixed an [issue](https://github.com/kata-containers/kata-containers/issues/3913#issuecomment-1077943739) related to container exit. Do your containers share a PID namespace?

**Comment by fidencio** [comment]
@Champ-Goblem, I think the issue you're facing is the one pointed (and fixed) by @fengwang666, which didn't make to the (now EOLed) stable-2.3 branch.

However, updating to 2.4 would lead to the issue reported by @skaegi.

By the beginning of the next week I hope to have this properly bisect and with a fix proposed, then we may promptly cut a 2.4.1 release with that fix in.

**Comment by fidencio** [comment]
I bisected this one back to https://github.com/kata-containers/kata-containers/pull/3406
I still don't know which commit of that series introduced the regression, but that's something for next week.

**Comment by bergwolf** [comment]
So it panics at
```
 592         let usage_in_usermode =
 593             (((*h.get("user").unwrap() * NANO_PER_SECOND) as f64) / *CLOCK_TICKS) as u64;
```
which looks to be a cpu stats issue racing with maybe pod deletion? When it happens, can you check what is the in pod's cpu cgroups file `cpuacct.stat`? Does it exist at all?

**Comment by fidencio** [comment]
> which looks to be a cpu stats issue racing with maybe pod deletion?

I think you're onto something here @bergwolf!

> When it happens, can you check what is the in pod's cpu cgroups file `cpuacct.stat`? Does it exist at all?

This is interesting ...
```sh
root@90c4e9a4835a:/# cat ./sys/fs/cgroup/cpu,cpuacct/cri-containerd/b8ca1bd3f9f91a9652c26e593abec56a4411d36c43a9befdd6123a05a1991726/cpuacct.stat
user 0
system 0
```
But what I'm getting from additional logs is:
```
Apr 11 12:37:46 kata-worker-0 kata[30862]: time="2022-04-11T12:37:46.714876438Z" level=debug msg="reading guest console" console-protocol=pty console-url=/dev/pts/0 name=containerd-shim-v2 pid=30862 sandbox=b8ca1bd3f9f91a9652c26e593abec56a4411d36c43a9befdd6123a05a1991726 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"FIDENCIO | get_cpuacct_stats | cpuacct.stat: \\\"\\\"\",\"level\":\"WARN\",\"ts\":\"2022-04-11T12:37:45.916519145+00:00\",\"name\":\"kata-agent\",\"pid\":\"55\",\"version\":\"0.1.0\",\"subsystem\":\"cgroups\",\"source\":\"agent\"}"
```

With this in mind we can mitigate the crash, but I'm not exactly sure how to avoid the race, nor why it's being consistently exposed by https://github.com/kata-containers/kata-containers/pull/3406.

**Comment by fidencio** [comment]
With the following patch we avoid the crash, but the pod is still hanging on `Terminating`:
```rust
diff --git a/src/agent/rustjail/src/cgroups/fs/mod.rs b/src/agent/rustjail/src/cgroups/fs/mod.rs
index b264e5e9d..563120cca 100644
--- a/src/agent/rustjail/src/cgroups/fs/mod.rs
+++ b/src/agent/rustjail/src/cgroups/fs/mod.rs
@@ -590,9 +590,9 @@ fn get_cpuacct_stats(cg: &cgroups::Cgroup) -> SingularPtrField<CpuUsage> {
 
         let h = lines_to_map(&cpuacct.stat);
         let usage_in_usermode =
-            (((*h.get("user").unwrap() * NANO_PER_SECOND) as f64) / *CLOCK_TICKS) as u64;
+             (((*h.get("user").unwrap_or(&0) * NANO_PER_SECOND) as f64) / *CLOCK_TICKS) as u64;
         let usage_in_kernelmode =
-            (((*h.get("system").unwrap() * NANO_PER_SECOND) as f64) / *CLOCK_TICKS) as u64;
+             (((*h.get("system").unwrap_or(&0) * NANO_PER_SECOND) as f64) / *CLOCK_TICKS) as u64;
 
         let total_usage = cpuacct.usage;
 
@@ -623,9 +623,9 @@ fn get_cpuacct_stats(cg: &cgroups::Cgroup) -> SingularPtrField<CpuUsage> {
     let cpu_controller: &CpuController = get_controller_or_return_singular_none!(cg);
     let stat = cpu_controller.cpu().stat;
     let h = lines_to_map(&stat);
-    let usage_in_usermode = *h.get("user_usec").unwrap();
-    let usage_in_kernelmode = *h.get("system_usec").unwrap();
-    let total_usage = *h.get("usage_usec").unwrap();
+    let usage_in_usermode = *h.get("user_usec").unwrap_or(&0);
+    let usage_in_kernelmode = *h.get("system_usec").unwrap_or(&0);
+    let total_usage = *h.get("usage_usec").unwrap_or(&9);
     let percpu_usage = vec![];
 
     SingularPtrField::some(CpuUsage {

```

**Comment by fidencio** [comment]
Let me just add a little bit more info here on how I was able to reproduce this on my local environment.

1. Setup a k8s cluster: `kcli create kube generic -P workers=1 -P masters=1 -P image=ubuntu2004 kata`
2. Setup devmapper to be used on the worker node (done using the `setup_devmapper.sh` script)
3. Ensure containerd is setup for using devmapper (see the `config.toml` file), and restart the service
4. Deploy kata-deploy, using the instructions for the stable deployment: https://quay.io/repository/kata-containers/kata-deploy?tab=info
    ```sh
    kubectl apply -f https://raw.githubusercontent.com/kata-containers/kata-containers/main/tools/packaging/kata-deploy/kata-rbac/base/kata-rbac.yaml

    kubectl apply -f https://raw.githubusercontent.com/kata-containers/kata-containers/main/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml

    kubectl -n kube-system wait --timeout=10m --for=condition=Ready -l name=kata-deploy pod

    kubectl apply -f https://raw.githubusercontent.com/kata-containers/kata-containers/main/tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
    ```
5. Deploy a pod using QEMU or Cloud Hypervisor
    ```sh
    kubectl apply -f https://raw.githubusercontent.com/kata-containers/kata-containers/main/tools/packaging/kata-deploy/examples/test-deploy-kata-qemu.yaml

    kubectl apply -f https://raw.githubusercontent.com/kata-containers/kata-containers/main/tools/packaging/kata-deploy/examples/test-deploy-kata-clh.yaml
    ```
6. After the pod is up and running, delete them and see them hanging on "Terminating" ...
    ```sh
    kubectl delete -f https://raw.githubusercontent.com/kata-containers/kata-containers/main/tools/packaging/kata-deploy/examples/test-deploy-kata-qemu.yaml

    kubectl delete -f https://raw.githubusercontent.com/kata-containers/kata-containers/main/tools/packaging/kata-deploy/examples/test-deploy-kata-clh.yaml
    ```



Additional info:

`setup_devmapper.sh`:

```sh
#!/bin/bash
set -ex

DATA_DIR=/var/lib/containerd/io.containerd.snapshotter.v1.devmapper
POOL_NAME=containerd-pool

sudo mkdir -p ${DATA_DIR}

# Create data file
sudo touch "${DATA_DIR}/data"
sudo truncate -s 10G "${DATA_DIR}/data"

# Create metadata file
sudo touch "${DATA_DIR}/meta"
sudo truncate -s 4G "${DATA_DIR}/meta"

# Allocate loop devices
DATA_DEV=$(sudo losetup --find --show "${DATA_DIR}/data")
META_DEV=$(sudo losetup --find --show "${DATA_DIR}/meta")

# Define thin-pool parameters.
# See https://www.kernel.org/doc/Documentation/device-mapper/thin-provisioning.txt for details.
SECTOR_SIZE=512
DATA_SIZE="$(sudo blockdev --getsize64 -q ${DATA_DEV})"
LENGTH_IN_SECTORS=$(bc <<< "${DATA_SIZE}/${SECTOR_SIZE}")
DATA_BLOCK_SIZE=128
LOW_WATER_MARK=32768

# Create a thin-pool device
sudo dmsetup create "${POOL_NAME}" \
	    --table "0 ${LENGTH_IN_SECTORS} thin-pool ${META_DEV} ${DATA_DEV} ${DATA_BLOCK_SIZE} ${LOW_WATER_MARK}"

cat << EOF
#
# Add this to your config.toml configuration file and restart containerd daemon
#
[plugins]
  [plugins.devmapper]
    pool_name = "${POOL_NAME}"
    root_path = "${DATA_DIR}"
    base_image_size = "4GB"
EOF
```


`config.toml` (after using kata-deploy):

```toml
disabled_plugins = []
imports = []
oom_score = 0
plugin_dir = ""
required_plugins = []
root = "/var/lib/containerd"
state = "/run/containerd"
version = 2

[cgroup]
  path = ""

[debug]
  address = ""
  format = ""
  gid = 0
  level = "debug"
  uid = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216
  tcp_address = ""
  tcp_tls_cert = ""
  tcp_tls_key = ""
  uid = 0

[metrics]
  address = ""
  grpc_histogram = false

[plugins]

  [plugins."io.containerd.gc.v1.scheduler"]
    deletion_threshold = 0
    mutation_threshold = 100
    pause_threshold = 0.02
    schedule_delay = "0s"
    startup_delay = "100ms"

  [plugins."io.containerd.grpc.v1.cri"]
    disable_apparmor = false
    disable_cgroup = false
    disable_hugetlb_controller = true
    disable_proc_mount = false
    disable_tcp_service = true
    enable_selinux = false
    enable_tls_streaming = false
    ignore_image_defined_volumes = false
    max_concurrent_downloads = 3
    max_container_log_line_size = 16384
    netns_mounts_under_state_dir = false
    restrict_oom_score_adj = false
    sandbox_image = "k8s.gcr.io/pause:3.5"
    selinux_category_range = 1024
    stats_collect_period = 10
    stream_idle_timeout = "4h0m0s"
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    systemd_cgroup = false
    tolerate_missing_hugetlb_controller = true
    unset_seccomp_profile = ""

    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"
      conf_template = ""
      max_conf_num = 1

    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "runc"
      disable_snapshot_annotations = true
      discard_unpacked_layers = false
      no_pivot = false
      snapshotter = "devmapper"

      [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime]
        base_runtime_spec = ""
        container_annotations = []
        pod_annotations = []
        privileged_without_host_devices = false
        runtime_engine = ""
        runtime_root = ""
        runtime_type = ""

        [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime.options]

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          base_runtime_spec = ""
          container_annotations = []
          pod_annotations = []
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            BinaryName = ""
            CriuImagePath = ""
            CriuPath = ""
            CriuWorkPath = ""
            IoGid = 0
            IoUid = 0
            NoNewKeyring = false
            NoPivotRoot = false
            Root = ""
            ShimCgroup = ""
            SystemdCgroup = false

      [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime]
        base_runtime_spec = ""
        container_annotations = []
        pod_annotations = []
        privileged_without_host_devices = false
        runtime_engine = ""
        runtime_root = ""
        runtime_type = ""

        [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime.options]

    [plugins."io.containerd.grpc.v1.cri".image_decryption]
      key_model = "node"

    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = ""

      [plugins."io.containerd.grpc.v1.cri".registry.auths]

      [plugins."io.containerd.grpc.v1.cri".registry.configs]

      [plugins."io.containerd.grpc.v1.cri".registry.headers]

      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]

    [plugins."io.containerd.grpc.v1.cri".x509_key_pair_streaming]
      tls_cert_file = ""
      tls_key_file = ""

  [plugins."io.containerd.internal.v1.opt"]
    path = "/opt/containerd"

  [plugins."io.containerd.internal.v1.restart"]
    interval = "10s"

  [plugins."io.containerd.metadata.v1.bolt"]
    content_sharing_policy = "shared"

  [plugins."io.containerd.monitor.v1.cgroups"]
    no_prometheus = false

  [plugins."io.containerd.runtime.v1.linux"]
    no_shim = false
    runtime = "runc"
    runtime_root = ""
    shim = "containerd-shim"
    shim_debug = false

  [plugins."io.containerd.runtime.v2.task"]
    platforms = ["linux/amd64"]

  [plugins."io.containerd.service.v1.diff-service"]
    default = ["walking"]

  [plugins."io.containerd.snapshotter.v1.aufs"]
    root_path = ""

  [plugins."io.containerd.snapshotter.v1.btrfs"]
    root_path = ""

  [plugins."io.containerd.snapshotter.v1.devmapper"]
    async_remove = false
    pool_name = "containerd-pool"
    root_path = "/var/lib/containerd/io.containerd.snapshotter.v1.devmapper"
    base_image_size = "4GB"

  [plugins."io.containerd.snapshotter.v1.native"]
    root_path = ""

  [plugins."io.containerd.snapshotter.v1.overlayfs"]
    root_path = ""

  [plugins."io.containerd.snapshotter.v1.zfs"]
    root_path = ""

[proxy_plugins]

[stream_processors]

  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+encrypted"]
    args = ["--decryption-keys-path", "/etc/containerd/ocicrypt/keys"]
    env = ["OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf"]
    path = "ctd-decoder"
    returns = "application/vnd.oci.image.layer.v1.tar"

  [stream_processors."io.containerd.ocicrypt.decoder.v1.tar.gzip"]
    accepts = ["application/vnd.oci.image.layer.v1.tar+gzip+encrypted"]
    args = ["--decryption-keys-path", "/etc/containerd/ocicrypt/keys"]
    env = ["OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf"]
    path = "ctd-decoder"
    returns = "application/vnd.oci.image.layer.v1.tar+gzip"

[timeouts]
  "io.containerd.timeout.shim.cleanup" = "5s"
  "io.containerd.timeout.shim.load" = "5s"
  "io.containerd.timeout.shim.shutdown" = "3s"
  "io.containerd.timeout.task.state" = "2s"

[ttrpc]
  address = ""
  gid = 0
  uid = 0
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
  runtime_type = "io.containerd.kata.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc]
  runtime_type = "io.containerd.kata-fc.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-fc.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-fc.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu]
  runtime_type = "io.containerd.kata-qemu.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-qemu.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh]
  runtime_type = "io.containerd.kata-clh.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-clh.toml"
```
