### ISSUE TITLE
qemu.log file is empty, without any qemu log info

### ISSUE THREAD

**Issue by flyflypeng** [kata-containers/kata-containers#4147]
kata.log is attached at the end of this issue description

# Description of problem

The `/run/vc/vm/<sandbox-name>/qemu.log` file is empty which should be filled with qemu process log info when kata-containers is started.

qemu hypervisor info in the configuration.toml
```toml
[hypervisor.qemu]
path = "/opt/kata/bin/qemu-system-x86_64"
kernel = "/opt/kata/share/kata-containers/vmlinux.container"
image = "/opt/kata/share/kata-containers/kata-containers.img"
machine_type = "q35"
```

and all binaries (includes `/opt/kata/bin/qemu-system-x86_64` binary) come from the release page: https://github.com/kata-containers/kata-containers/releases/download/2.4.0/kata-static-2.4.0-x86_64.tar.xz

# Expected result

The `/run/vc/vm/<sandbox-name>/qemu.log` is not empty, and filled with qemu process log info.

# Actual result

```bash
$ sudo cat /run/vc/vm/test-kata/qemu.log

$ sudo ls -al /run/vc/vm/test-kata/qemu.log
-rw-r--r-- 1 root root 0 Apr 24 20:54 /run/vc/vm/test-kata/qemu.log
```

# Further information

I just start a simplest kata-container with the following command:
```bash
$ sudo ctr run --runtime "io.containerd.kata.v2" -d -t docker.io/library/busybox:latest test-kata sleep 999999
```

[kata.log](https://github.com/kata-containers/kata-containers/files/8549733/kata.log)
