### ISSUE TITLE
Extreme poor storage performance, what I have done wrong?

### ISSUE THREAD

**Issue by liyimeng** [kata-containers/kata-containers#4149]
# Get your issue reviewed faster

To help us understand the problem more quickly, please do the following:

1. Run the `kata-collect-data.sh` script, which is installed as part of Kata Containers
   or `kata-containers.collect-data`, which is installed as part of the Kata Containers
   snapcraft package.
   ```sh
   $ sudo kata-collect-data.sh > /tmp/kata.log
   ```
   or
   ```sh
   $ sudo kata-containers.collect-data > /tmp/kata.log
   ```
1. Review the output file (`/tmp/kata.log`) to ensure it doesn't
   contain any private / sensitive information
1. Paste the *entire* contents of the file into this issue as a comment
   (the script generates markdown format output).

The information provided will help us to understand the problem more quickly
so saves time for both of us! :smile:

# Description of problem

1. install k3s. 
2. deploy kata with kata-deploy daemonset
3. deploy kata-runtime classes
5. deploy ngnix qemu kata-container with local-path volume  
6. install fio and run a quick test. 
7. delete pods and re-deploy using the same volume but default runtime
8. compare fio benchmark result 
# Expected result

kata should be similar disk performance with default runtime 
# Actual result

kata only reach about 10% of default runtime performance. 

# Further information

My test use the same volume, first test with kata, when tear down kata pod and run with default runtime. using the same fio commands, kata only achieve about 10% of bandwidth/iops of default runtime, a huge drop.
## kata test setup
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-qemu
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      runtimeClassName: kata-qemu
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /www
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-test
```
## Default runtime setup:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /www
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-test   
```

## Test  Result

kata

```
fio --name=random-write --ioengine=posixaio --rw=randwrite --bs=4k --size=960M --numjobs=1 --runtime=60 --time_based --end_fsync=1
random-write: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=posixaio, iodepth=1
fio-2.16
Starting 1 process
random-write: Laying out IO file(s) (1 file(s) / 960MB)
Jobs: 1 (f=1): [F(1)] [100.0% done] [0KB/1840KB/0KB /s] [0/460/0 iops] [eta 00m:00s]
random-write: (groupid=0, jobs=1): err= 0: pid=563: Sat Apr 23 06:05:47 2022
  write: io=672648KB, bw=10898KB/s, iops=2724, runt= 61722msec
    slat (usec): min=0, max=174, avg= 1.04, stdev= 2.17
    clat (usec): min=220, max=14762, avg=349.93, stdev=118.59
     lat (usec): min=220, max=14763, avg=350.97, stdev=118.66
    clat percentiles (usec):
     |  1.00th=[  253],  5.00th=[  266], 10.00th=[  274], 20.00th=[  286],
     | 30.00th=[  302], 40.00th=[  314], 50.00th=[  330], 60.00th=[  350],
     | 70.00th=[  370], 80.00th=[  402], 90.00th=[  450], 95.00th=[  494],
     | 99.00th=[  596], 99.50th=[  676], 99.90th=[ 1064], 99.95th=[ 1528],
     | 99.99th=[ 3760]
    lat (usec) : 250=0.52%, 500=95.05%, 750=4.11%, 1000=0.20%
    lat (msec) : 2=0.08%, 4=0.02%, 10=0.01%, 20=0.01%
  cpu          : usr=3.51%, sys=2.31%, ctx=505810, majf=0, minf=33
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=168162/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1
Run status group 0 (all jobs):
  WRITE: io=672648KB, aggrb=10898KB/s, minb=10898KB/s, maxb=10898KB/s, mint=61722msec, maxt=61722msec
```
default

```
fio --name=random-write --ioengine=posixaio --rw=randwrite --bs=4k --size=960M --numjobs=1 --runtime=60 --time_based --end_fsync=1
random-write: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=posixaio, iodepth=1
fio-2.16
Starting 1 process
Jobs: 1 (f=1): [F(1)] [100.0% done] [0KB/10322KB/0KB /s] [0/2580/0 iops] [eta 00m:00s]
random-write: (groupid=0, jobs=1): err= 0: pid=573: Sat Apr 23 06:11:13 2022
  write: io=5585.2MB, bw=92854KB/s, iops=23213, runt= 61592msec
    slat (usec): min=0, max=433, avg= 0.82, stdev= 0.94
    clat (usec): min=16, max=8802, avg=37.42, stdev=25.74
     lat (usec): min=17, max=8803, avg=38.24, stdev=25.80
    clat percentiles (usec):
     |  1.00th=[   26],  5.00th=[   28], 10.00th=[   29], 20.00th=[   30],
     | 30.00th=[   31], 40.00th=[   32], 50.00th=[   33], 60.00th=[   36],
     | 70.00th=[   38], 80.00th=[   42], 90.00th=[   49], 95.00th=[   56],
     | 99.00th=[   82], 99.50th=[  103], 99.90th=[  225], 99.95th=[  354],
     | 99.99th=[  820]
    lat (usec) : 20=0.13%, 50=90.52%, 100=8.81%, 250=0.46%, 500=0.05%
    lat (usec) : 750=0.02%, 1000=0.01%
    lat (msec) : 2=0.01%, 4=0.01%, 10=0.01%
  cpu          : usr=18.51%, sys=38.76%, ctx=1432423, majf=0, minf=35
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=1429763/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1
Run status group 0 (all jobs):
  WRITE: io=5585.2MB, aggrb=92853KB/s, minb=92853KB/s, maxb=92853KB/s, mint=61592msec, maxt=61592msec
Disk stats (read/write):
  vda: ios=0/49885, merge=0/6957, ticks=0/189596, in_queue=178428, util=5.71%
```

## Number: bw=10.9MB/s vs 92.854MB/s, IOPS 2,724 vs 23,213

I have repeated the test a couple of time to be faire for both, e.g. avoiding  one benefit disk warm up, while other not.
