### ISSUE TITLE
agent watchers: emptyDir permission and ownership does not match with source

### ISSUE THREAD

**Issue by yibozhuang** [kata-containers/kata-containers#4188]
Today in agent `watcher.rs`, when updating the target, we check if the source is a directory and if so, call `fs::create_dir_all()` [here](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/watcher.rs#L114)

There is no additional set permission here on the destination directory performed here so this can lead to the destination directory permission being different than source directory.
The same applies for `copy` [here](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/watcher.rs#L91) where if the source path had a different `uid` and `gid` than `root`, then the destination file `uid/gid` will not match the source file ownership.

Both of these cases can lead to permission issues.

Example:

I have a pod that uses `emptyDir`
with spec

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  - name: pod1
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    volumeMounts:
    - mountPath: /cache
      name: test-cache
  volumes:
  - name: test-cache
    emptyDir: {}
```

Here once I apply the pod with runtime `runc`, and then exec into the pod, I see the `/cache` directory has permission
```
drwxrwxrwx    2 root     root             6 May  2 23:43 cache
```

Where as when I use pod with Kata, this is the permission of the `/cache` directory
```
drwxr-xr-x    2 root     root             6 May  2 23:47 cache
```

Ideally the directory permissions should be identical when using Kata vs. `runc`
