### ISSUE TITLE
create kata container failed with "query-hotpluggable-cpus is not enabled" on aarch64

### ISSUE THREAD

**Issue by YchauWang** [kata-containers/kata-containers#4231]
# Get your issue reviewed faster

To help us understand the problem more quickly, please do the following:
k8s events:
```
Error: failed to create containerd task: failed to query hotpluggable CPUS: QMP command failed: The feature 'query-hotpluggable-cpus' is not enabled: unknown
```
kata shim v2 logs:
```
msg="Cleaning up partially created container" container="2870b.....23b51" error="failed to query hotpluggable CPUs: QMP command failed: The feature 'query-hotpluggable-cpus' is not enabled"
```
# Description of problem

I created kata containers with tag v2.4.0 branch codes on aarch64, YAML script as following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kata-test
spec:
  selector:
    matchLabels:
      app: kata-test
  replicas: 1
  template:
    metadata:
      labels:
        app: kata-test
    spec:
      runtimeClassName: kata
      nodeName: nodeXXX
      containers:
      - name: kata-qemu
        image: tomcat:8.5.39-arm64
        ports:
        - containerPort: 80
```
the kata container create successfully. But when add resources limit to the container:
```
        resources:
          limits:
            cpu: 600m
            memory: 512Mi
          requests:
            cpu: 600m
            memory: 512Mi
```
kata container created failed, because of "query-hotpluggable-cpus is not enabled".
[kata v1 #2893](https://github.com/kata-containers/runtime/issues/2893)
