### ISSUE TITLE
Kata with CPU manager Node Exceed expectations

### ISSUE THREAD

**Issue by xujunjie-cover** [kata-containers/kata-containers#4306]
# Node config
kata-containers/configuration.toml
```
default_vcpus = 1
default_memory = 2048
```

kubelet
```
cpuManagerPolicy: static
reservedSystemCPUs: 0-2,8-10
```

kata yaml
```
...
spec:
  runtimeClassName: kata-qemu
  nodeName: eci2
  containers:
  - name: kata-guaranteed
    image: polinux/stress
```

# First
## Expected result
on node without cpu manager
```
grep 'physical id' /proc/cpuinfo | sort -u | wc -l
1
```
on node with cpu manager，we excepted the same as without cpu manager

## Actual result
on node with cpu manager
```
grep 'physical id' /proc/cpuinfo | sort -u | wc -l
6
```

# Second
As we know，if kata doesn't have resources，the kata container's qos will be BestEffort，not Guaranteed，can't binding a cpu with cpuset。
If I need a 1c Kata container，I can't have resources when config set default_vcpu (default_vcpus = 1)；
How to resolve this confluct.

## Further information
If I set resources limit cpu = 1，will has two cpus in kata container.
