### ISSUE TITLE
runtime-rs: [kata ci] k8s-seccomp.bats failed to check seccomp result

### ISSUE THREAD

**Issue by quanweiZhou** [kata-containers/kata-containers#4691]
[kata ci] k8s-seccomp.bats, open the guest_seccomp in the kata configuration, then pull up the pod, and then check the Seccomp in the pod log, the expectation is 2 but the actual value is 0

1. Modify disable_guest_seccomp=true in the kata config file to disable_guest_seccomp=false
2. Create a pod: kubectl create -f pod-seccomp.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-container
spec:
  runtimeClassName: kata
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
  containers:
  - name: busybox
    image: quay.io/prometheus/busybox:latest
    command: ["grep", "Seccomp:", "/proc/self/status"]
    securityContext:
      seccompProfile:
        type: RuntimeDefault
```

check the result
```
kubectl get all
NAME                    READY   STATUS      RESTARTS   AGE
 pod/seccomp-container   0/1     Completed   0          3s

 NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
 service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   32s

crictl pods：
POD ID              CREATED             STATE               NAME                                              NAMESPACE           ATTEMPT             RUNTIME
 90489fbcdca63       2 seconds ago       NotReady            seccomp-container                                 default             0                   kata

critctl ps -a：
CONTAINER           IMAGE               CREATED             STATE               NAME                      ATTEMPT             POD ID
407072b66aa95       342b02f8cb5f5       1 second ago        Exited              busybox                   0                   90489fbcdca63

kubectl logs seccomp-container：
Seccomp:      0  ---- expect 2
```
