### ISSUE TITLE
runtime-rs: [kata ci] k8s-expose-ip.bats failed to curl CLUSTER-IP:PORT

### ISSUE THREAD

**Issue by quanweiZhou** [kata-containers/kata-containers#4726]
1. kubectl create -f  deployment-expose-ip.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
        run: load-balancer-example
    spec:
      terminationGracePeriodSeconds: 0
      runtimeClassName: kata
      containers:
      - name: hello-world
        image: k8s.gcr.io/e2e-test-images/agnhost:2.21
        args:
        - netexec
        ports:
        - containerPort: 8080
```
2. wait for the pod to running: kubectl expose deployment/hello-world --type=LoadBalancer --name=my-service 
3. get the CLUSTER-IP and port: kubectl get svc my-service 
```
# kubectl get svc
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP      10.96.0.1        <none>        443/TCP          17m
my-service   LoadBalancer   10.100.241.102   <pending>     8080:30711/TCP   17m
```
4. curl server and return error
```
# curl http://10.100.241.102:8080/echo?msg=helloworld 
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 10.108.41.143 port 8080: Connection refused
```
