### ISSUE TITLE
runtime-rs: failed to use kubectl cp to copy a file from host to pod 

### ISSUE THREAD

**Issue by studychao** [kata-containers/kata-containers#4729]
This bug is found in the `k8s-copy-file.bats` CI test.

How to reproduce the error :

1. create the pod： kubectl create -f pod.yaml
```
pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: pod-copy-file-from-host
spec:
  terminationGracePeriodSeconds: 0
  runtimeClassName: kata
  shareProcessNamespace: true
  containers:
  - name: ctr-copy-file-from-host
    image: quay.io/prometheus/busybox:latest
    command:
      - sleep
      - "120"
```

2. echo "helloworld" > /tmp/file.txt

3. kubectl cp  /tmp/file.txt pod-copy-file-from-host:/tmp

The step 3 failed and runtime-rs will be stuck.
