### ISSUE TITLE
runtime-rs: after update configmap, pod &container status goes wrong

### ISSUE THREAD

**Issue by studychao** [kata-containers/kata-containers#4731]
This bug is found in the CI test `k8s-inotify.bats`

How to reproduce:
1. create configmap: kubectl apply -f inotify-configmap.yaml
```
apiVersion: v1
data:
  config.toml: |-
    foo original...
kind: ConfigMap
metadata:
  name: cm
```
2. kubectl apply -f inotify-configmap-pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: inotify-configmap-testing
spec:
  containers:
  - name: c1
    image: quay.io/kata-containers/fsnotify:latest
    command: ["bash"]
    args: ["-c", "inotifywait --timeout 120 -r /config/ && [[ -L /config/config.toml ]] && echo success" ]
    resources:
      requests:
        cpu: 1
        memory: 50Mi
      limits:
        cpu: 1
        memory: 1024Mi
    volumeMounts:
      - name: config
        mountPath: /config
  runtimeClassName: kata
  restartPolicy: Never
  volumes:
    - name: config
      configMap:
        name: cm
```

3. update configmap: ：kubectl apply -f notify-updated-configmap.yaml
```
apiVersion: v1
data:
  config.toml: |-
    foo original...
    ... updated
kind: ConfigMap
metadata:
  name: cm
```

Wait 2 mins and then check pod & container status.

 POD ID              CREATED             STATE               NAME                                              NAMESPACE           ATTEMPT             RUNTIME
 77ced9bdeb12e       2 minutes ago       NotReady            inotify-configmap-testing                         default             0                   kata

 CONTAINER           IMAGE               CREATED             STATE               NAME                      ATTEMPT             POD ID
 c5b32bb90854e       3b775632aaa5f       2 minutes ago       Exited              c1                        0                   77ced9bdeb12e
