### ISSUE TITLE
runtime-rs: nginx connection error

### ISSUE THREAD

**Issue by studychao** [kata-containers/kata-containers#4732]
This bug is found in the CI test `k8s-nginx-connectivity.bats`

How to reproduce:
1. create deplyment：kubectl create -f deployment.yaml
```
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: nginx-deployment
 spec:
   selector:
     matchLabels:
       app: nginx
   replicas: 2
   template:
     metadata:
       labels:
         app: nginx
     spec:
       terminationGracePeriodSeconds: 0
       runtimeClassName: kata
       containers:
       - name: nginx
         image: quay.io/sjenning/nginx:1.15-alpine
         ports:
         - containerPort: 80
```

2. expose service after pod is started : kubectl expose deployment/nginx-deployment

3. create a runc pod and try to connect nginx : `kubectl run test-nginx --restart=Never -it --image=busybox -- sh -c 'i=1; while [ $i -le 90 ]; do wget --timeout=5 nginx-deployment && break; sleep 1; i=$(expr $i + 1); done`

following error will be returned:
 Connecting to nginx-deployment (10.100.150.149:80)
 wget: can't connect to remote host (10.100.150.149): Connection refused
