### ISSUE TITLE
When enabling the kernel driver module in the kata container, it always prompts that the module cannot be found.

### ISSUE THREAD

**Issue by fu7100** [kata-containers/kata-containers#4958]
I installed the kata2.1.0 version on the rhel8.4 system through yum, when I need to enable the module in the kata kernel, it is always not found,

```
[root@jump-rhel kata-pod]# oc get pod
NAME        READY   STATUS              RESTARTS   AGE
test-kata   0/1     ContainerCreating   0          24m

-----

Events:
  Type     Reason                  Age   From     Message
  ----     ------                  ----  ----     -------
  Normal   AddedInterface          17s   multus   Add eth0 [10.131.0.243/23] from openshift-sdn
  Warning  FailedCreatePodSandBox  0s    kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = CreateContainer failed: load_kernel_module return code: 1 stdout: stderr:modprobe: FATAL: Module mlx5_core not found in directory /lib/modules/4.18.0-372.16.1.el8_6.x86_64
```

test-kata.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: test-kata
  annotations:
    io.katacontainers.config.agent.kernel_modules: "mlx5_core"
spec:
  runtimeClassName: kata
  terminationGracePeriodSeconds: 0
  containers:
  - name: test-kata
    image: harbor.test.local/mirror/busybox:latest
    command: ["/bin/sh", "-c", "sleep inf"]
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: modules
      mountPath: /lib/modules
  volumes:
  - name: modules
    hostPath:
      path: /lib/modules
      type: Directory
```
