### ISSUE TITLE
the configuration files of kubelet set --cpu-manager-policy=static, the vcpus not equal default_vcpus

### ISSUE THREAD

**Issue by Gezx** [kata-containers/kata-containers#5442]
when I set --cpu-manager-policy=static, and don't set spec.containers.resources ，the vcpus not equal default_vcpus. The number of vcpus is euqal the number of pcpus, does anybody know how it was set up.
the yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: test-cpu
spec:
  runtimeClassName: kata
  containers:
  - image: centos
    name : test-cpu-1
    command:
    - sleep
    - "123600"
```
the result
![image](https://user-images.githubusercontent.com/43102721/196139242-5eeea4c3-f512-4958-8f95-4b707c04a426.png)

**Comment by liubin** [comment]
@Gezx, from the [offical documatation](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy):

> This policy manages a shared pool of CPUs that initially contains all CPUs in the node.

> This shared pool is the set of CPUs on which any containers in BestEffort and Burstable pods run. Containers in Guaranteed pods with fractional CPU requests also run on CPUs in the shared pool. Only containers that are both part of a Guaranteed pod and have integer CPU requests are assigned exclusive CPUs.

So can you give a try:

- firstly, start a Pod/container with CPU specified and check the CPUs:

```yaml
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "2"
```

- then run your pod without any resources again and check the CPUs.
