### ISSUE TITLE
CC | The working directory does not change to match the image

### ISSUE THREAD

**Issue by Jordan9500** [kata-containers/kata-containers#5721]
# Description of problem

After creating an image where the working directory gets changed, I noticed that the directory inside the Pod does not match.
Dockerfile for the image:
```
FROM ubuntu:22.04

RUN mkdir -p /other
WORKDIR /other/

ENTRYPOINT [ "/bin/bash", "-c", "pwd" ]
```

Pod yaml: 
```
apiVersion: v1
kind: Pod
metadata:
  name: workdir-test
spec:
  runtimeClassName: kata
  restartPolicy: OnFailure
  containers:
  - image: jordan9500/workdir-test
    imagePullPolicy: always
    name: jjworkdir
```

# Expected result

When the apply is complete and we check the logs we should get:
`kubectl logs pod/workdir-test`
```
/other
```

# Actual result

However instead when we check the logs we get: 
`kubectl logs pod/workdir-test`
```
/
```

# Further information

This issue seems to be related to this snippet of code: 
https://github.com/kata-containers/kata-containers/blob/ab6b1cbfe94667b54d14f4f72fbd9fa7b1538b2a/src/agent/src/rpc.rs#L130-L140.

Due to the current if statement it never runs the change working directory step.
