### ISSUE TITLE
CC | agent: When creating an OCI process the pod yamls environment variables are ignored

### ISSUE THREAD

**Issue by Jordan9500** [kata-containers/kata-containers#5730]
# Description of problem

When defining both a ENV variable inside the pod yaml and inside a Dockerfile it duplicates the value and does not use the one found inside the YAML. 
For example a Dockerfile with: 
```
FROM ubuntu:22.04
ENV ISPRODUCTION=false
ENTRYPOINT [ "/bin/bash", "-c", "env" ]
```
And in the Pod yaml: 
```
apiVersion: v1
kind: Pod
metadata:
  name: env-test
spec:
  containers:
  - env: 
    - name: ISPRODUCTION
       value: true
    image: jordan9500/env-test:latest
    imagePullPolicy: Always
    name: jjenv
  runtimeClassName: kata
  restartPolicy: OnFailure
```
During the OCI process it will use the ENV variable inside the Dockerfile rather than the pod yamls. In this example it means the Pod will run as "Dev" rather than "Production"

# Expected result

When we check the logs of the running pod:
```
HOSTNAME=env-test
isProduction=false
PWD=/
HOME=/root
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ISPRODUCTION=true
_=/usr/bin/env
```
Noticing the ISPRODUCTION is set to true

# Actual result

However when we actually check the logs of the running pod we get:
```
HOSTNAME=env-test
isProduction=false
PWD=/
HOME=/root
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ISPRODUCTION=false
_=/usr/bin/env
```
Noticing the ISPRODUCTION is set to false

# Further information

This issue seems to be related to this snippet of code: 
https://github.com/kata-containers/kata-containers/blob/ab6b1cbfe94667b54d14f4f72fbd9fa7b1538b2a/src/agent/src/rpc.rs#L130-L140.

Specifically `target.env.append(&mut source.env.clone());` So instead of checking if it exists inside the target already. It will append it automatically.
