### ISSUE TITLE
.github/workflows/cargo-deny-runner.yaml syntax error

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#5808]
There is a syntax error in .github/workflows/cargo-deny-runner.yaml

```
on:
  - pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths-ignore: [ '**.md', '**.png', '**.jpg', '**.jpeg', '**.svg', '/docs/**' ]
```

This will get this error:

> Invalid type for `on`

`on` should has elements as a map, but not an array.
