### ISSUE TITLE
Signal all make graceful shutdown failed

### ISSUE THREAD

**Issue by keloyang** [kata-containers/kata-containers#5831]
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/service.go#L804 use signal all to send signal to container，I think the purpose for signal all is to ensure all processes in the container exit, so it's better to use signal all when the signal is SIGKILL, usually sigterm is used to handle graceful shutdown, but signal all makes graceful shutdown failed. 

# test code
```
func main() {
	go func() {
		for {
			time.Sleep(1 * time.Second)
			fmt.Println("tick")
		}
	}()

	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM)
	<-c

	time.Sleep(1 * time.Second)
	fmt.Println("Shutting down")
}
```

# Dockerfile
```
FROM golang:1.16

RUN apt update && apt install -y apache2-utils
COPY app.go /
RUN go build -o /main /app.go

SHELL ["/bin/bash", "-c"]
CMD exec /main 1> >(rotatelogs -e -l -t -f /tmp/stdout.log 50M 1>&2)
```

# pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: grace
spec:
  containers:
    - name: app
      image: xx/grace
      imagePullPolicy: Always
  runtimeClassName: kata-qemu
  nodeName: box0
  terminationGracePeriodSeconds: 10
```

# reproduce
## use kata
```
terminal 1, kubectl create -f pod.yaml
terminal 2, kubectl logs -f grace
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
rpc error: code = NotFound desc = an error occurred when try to find container "e2db4333ddc28930fea93d3fee32c50f6d0b9d38316ea144707b72918b792a13": not found%
terminal 1, kubectl delete -f pod.yaml
```
we will never see "Shutting down".

## use runc
just remove "runtimeClassName: kata-qemu" from pod.yaml.
```
terminal 1, kubectl create -f pod.yaml
terminal 2, kubectl logs -f grace
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
Shutting down
rpc error: code = NotFound desc = an error occurred when try to find container "52beb597de65ee04623ea8d430f75547d4437d3392bc8dff8af9156302eaac29": not found"e2db4333ddc28930fea93d3fee32c50f6d0b9d38316ea144707b72918b792a13": not found%
terminal 1, kubectl delete -f pod.yaml
```
we can see "Shutting down".
