### ISSUE TITLE
runtime-rs changes Kata config file format

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#5954]
Working on #5242 I spotted a config change that runtime-rs introduces.

In the Kata 2.x TOML config file, we have sections like this:

```toml
[hypervisor.foo]
# ...

[agent.kata]
# ...

[runtime]
# ...
```

... but with runtime-rs, we seem to now have:

```toml
[hypervisor.dragonball]
# ...

[agent.kata]
# ...

[runtime]

# ...
name="virt_container"
hypervisor_name="dragonball"  # XXX: <-- Redundant information.
agent_name="kata"             # XXX: <-- Redundant information.

# ...
```

As shown by the comment, it's unclear why we need runtime.hypervisor_name given that the TOML format itself describes that value as `dragonball` (from the `[hypervisor.dragonball]` heading). In other words, specifying `runtime.hypervisor_name` is redundant - it's already been specified.

Why is this needed? The current runtime-rs code assumes this new format which means existing 2.x config files for stand-alone hypervisors do not work unless their config files are modified to include the redundant `runtime.hypervisor_name` and `runtime.agent_name`.

Specifically, the problem is `Annotation::update_config_by_annotation()` which does this:

```rust
if config.runtime.hypervisor_name.is_empty() {
    config.runtime.hypervisor_name = DEFAULT_HYPERVISOR.to_string()
}
```

... whereas the code should be looking at `config.hypervisor` as that contains the details in the `[hypervisor.name]` TOML section.

> **Note:** The same logic applies for determining the value of "agent".

See:

- https://github.com/kata-containers/kata-containers/blob/main/src/runtime-rs/config/configuration-dragonball.toml.in
- https://github.com/kata-containers/kata-containers/blob/main/src/libs/kata-types/src/annotations/mod.rs#L451..L456

/cc @studychao, @jiangliu, @pmores.
