### ISSUE TITLE
failed to create containerd task: failed to create shim task: UnknownErrno: Unknown errno: unknown

### ISSUE THREAD

**Issue by sky-big** [kata-containers/kata-containers#6088]
# Description of problem

## Env

Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

Containerd Version
```
containerd github.com/containerd/containerd v1.6.9 1c90a442489720eec95342e1789ee8a5e1b9536f
```

containerd-shim-kata-v2 Version
```
containerd-shim-kata-v2:
  Version:  1.6.8+unknown
  Revision:
  Go version: go1.19.3
```

Kata Runtime Version:
```
kata-runtime  : 3.1.0-alpha1
   commit   : 2e54c8e8871bf3a2cdebebd2946182d04e64d5eb-dirty
   OCI specs: 1.0.2-dev
```

## Question

When I create pod in kubernetes with resources request like this :
```
apiVersion: v1
kind: Pod
metadata:
  name: kata-test-pod
spec:
  containers:
  - name: kata-test-pod
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    resources:
      limits:
        cpu: "1"
        memory: "4Gi"
      requests:
        cpu: "1"
        memory: "4Gi"
```

pod start failed, error info like this:
```
Warning  Failed     10m (x5 over 12m)    kubelet            Error: failed to create containerd task: failed to create shim task: UnknownErrno: Unknown errno: unknown
  Warning  BackOff    114s (x48 over 12m)  kubelet            Back-off restarting failed container
```

pod state:
```
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: UnknownErrno: Unknown errno: unknown
      Exit Code:    128
      Started:      Thu, 01 Jan 1970 08:00:00 +0800
      Finished:     Tue, 17 Jan 2023 09:03:49 +0800
    Ready:          False
    Restart Count:  7
    Limits:
      cpu:     1
      memory:  4Gi
    Requests:
      cpu:        1
      memory:     4Gi
```

When I create a Pod without the GPU Resources requirement:
```
apiVersion: v1
kind: Pod
metadata:
  name: kata-gpu-test-pod-cni
  annotations:
    freesia/accountId: f654c54f66aa4c429e052ce0018a26a6
    freesia/clusterid: 9a2f543a-11a9-40ed-a7f0-3834de75854b
    freesia/namespace: default
    freesia/prodInstId: 5b5a4a718dac42c1bfb331ac9cd60097
    freesia/subnetid: e95c3d91-191b-458d-831b-a434ef0ba72a
  labels:
    app: kata-gpu-test-pod-cni
spec:
  containers:
  - name: kata-gpu-test-pod-cni
    image: cce-registry.ctyun.cn:443/nvidia-gpu/nvidia/cuda:11.6.0-base-ubuntu20.04
    command: ['sh', '-c', 'sleep 3600']
    resources:
      limits:
        nvidia.com/gpu: "2"
      requests:
        nvidia.com/gpu: "2"
```

pod create success:
```
    State:          Running
      Started:      Tue, 17 Jan 2023 09:18:10 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      nvidia.com/gpu:  2
    Requests:
      nvidia.com/gpu:  2
```

Is there any solution to this problem please?
