### ISSUE TITLE
Remote hypervisor: pod fails to start with io.katacontainers.config.hypervisor.virtio_fs_extra_args annotation

### ISSUE THREAD

**Issue by RobertKrawitz** [kata-containers/kata-containers#6345]
# Description of problem

OpenShift 4.12, kata containers 2.5.2-1.el8.x86_64

Attempted to start the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift
  labels:
    app: hello-openshift
  annotations:
    io.katacontainers.config.hypervisor.virtio_fs_extra_args: "[ \"-o\", \"allow_direct_io\" ]"
spec:
  runtimeClassName: kata-remote-cc
  imagePullPolicy: IfNotPresent
  containers:
    - name: hello-openshift
      image: quay.io/rkrawitz/bench-army-knife:latest
      command:
        - "/bin/sleep"
      args:
        - "infinity"
```

# Expected result

Pod should start.

# Actual result

Pod fails to start with the following error:
```
  Warning  FailedCreatePodSandBox  3m14s (x25 over 4m10s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = CreateContainer failed: annotation io.katacontainers.config.hypervisor.virtio_fs_extra_args is not enabled: unknown
```

# Further information

Pod starts with standard (runc) runtime and with kata
