### ISSUE TITLE
Memory-backed emptyDir volume size does not scale with sandbox size

### ISSUE THREAD

**Issue by wlan0** [kata-containers/kata-containers#6417]
### Description of problem

When creating emptyDir volumes backed by Memory, the total size of the memory backed volumes is set to 1Gi regardless of the total memory allocated to the Sandbox. This is because ephemeral volumes are created before container memory requests are hotplugged, and is therefore set proportional (0.5x) to the size of the Sandbox (2Gi) at start time

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: tmpfs-repro
spec:
  volumes:
  - name: xyz
    emptyDir:
      medium: Memory
  containers:
  - name: tmpfs-repro
    image: alpine:latest
    resources:
      limits:
        memory: 4Gi
        cpu: 2
    volumeMounts:
    - name: xyz
      mountPath: /xyz
 ```     

# Expected result

```sh
$ kubectl exec -it tmpfs-repro -- df -h /xyz
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           3956M    0 3956M   0% /xyz
 ```
 
# Actual result

```sh
$ kubectl exec -it tmpfs-repro -- df -h /xyz
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           989M     0 989M    0% /xyz
 ```

# Further information

~~Kubernetes provides a field to specify total size of ephemeralMemory. Ideally, the size of these tmpfs mounts should be set to that size, if specified. In cases where this size is not specified, t The total size should be set to the Sandbox's memory limit. Currently, the ephemeralMemory size limit is not easily accessible from the runtime - so a potential solution would be to always set the size to Sandbox's memory limit.~~

Kubernetes expects the runtime to limit the size of memory backed `emptyDir` to the memory limit for the pod (https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run)
