### ISSUE TITLE
[BUG] virtiofsd leaks file descriptors during container crash loop

### ISSUE THREAD

**Issue by fengwang666** [kata-containers/kata-containers#6455]
When a container crashes and restarts, `virtiofsd` doesn't release the file descriptors it opens in the previous container instance. So if a pod is in a crash loop, eventually `virtiofsd` exhausts the file descriptors on the node and impacts other pods on the node. Admittedly, in a normal environment pods shouldn't be in crashloop forever. However, since kata is designed for running untrusted workload in a multi-tenant env. This potentially could be used to perform a DOS attack on the node by a malicious attacker.  

The root cause is unknown. My guess is the kata shim probably should (but doesn't) ask virtiofsd to close all the file descriptors as the container exits. Need to look into it a bit more. 

#### Env:
```
[root@ip-10-10-10-222 /]# /opt/kata/bin/kata-runtime --version
kata-runtime  : 2.5.2
   commit   : 4b39dc0a390584d2ee21072cca7707f4ee7f56c5
   OCI specs: 1.0.2-dev
```
```
[root@ip-10-10-10-222 /]# /opt/kata/libexec/virtiofsd --version
virtiofsd backend 1.3.0
```
```
[root@ip-10-10-10-222 /]# /opt/kata/bin/cloud-hypervisor --version
cloud-hypervisor v26.0
```
#### sample pod to deploy
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: fd-leak-test
  name: fd-leak-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fd-leak-test
  template:
    metadata:
      labels:
        run: fd-leak-test
    spec:
      runtimeClassName: kata-runtime
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      -[your node]
      containers:
        - image: alpine
          imagePullPolicy: Always
          name: fd-leak
          command: ['sh', '-c', 'echo "test exit" && sleep 10 && exit 1']
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 500m
      restartPolicy: Always
```

#### verify the bug

Find the sandbox that is crashing, find the virtiofsd processes associated with it. Only one of the two is leaking file desci

<img width="1000" alt="Screenshot 2023-03-13 at 8 44 31 PM" src="https://user-images.githubusercontent.com/58006590/224887911-768ebc9a-f777-4dd3-8a13-cabe06bc6897.png">
