### ISSUE TITLE
Bug: kata runtime get the wrong container config when update container

### ISSUE THREAD

**Issue by zhaojizhuang** [kata-containers/kata-containers#6475]
# Get your issue reviewed faster

# Description of problem

when update container (such as kill container process) in a pod, then kata-runtime get the containers from map 
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/sandbox.go#L1552

```go
func (s *Sandbox) UpdateContainer(ctx context.Context, containerID string, resources specs.LinuxResources) error {
	// Fetch the container.
	c, err := s.findContainer(containerID)
      
        ... ...
        // udpate container
	if err = c.update(ctx, resources); err != nil {
		return err
	}
```

**Please note here** : 
> findContainer got the wrong container when get one exist container, In the case of container restart in a pod

**In my case:**
> we will replace the `LinuxResources` according to container.config in func `update`
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/container.go#L1122
> since got the wrong container, then we update the wrong LinuxResources for contianer

# How to reproduce

 - a pod with 3 container, then go into kata vm, kill one container, such as busybox（process `sh`）
-  add some log in `s.findContainer(containerID)`, print container's pointer and content, then we will find: the container some pointer point to has been changed to another container's config
- 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cgroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgroup
  template:
    metadata:
      labels:
        app: cgroup
    spec:
      containers:
      - image: busybox
        lifecycle: {}
        name: busybox
        resources:
          limits:
            cpu: "0.5"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "Gi"
      - image: redis
        lifecycle: {}
        name: redis
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: "1"
            memory: "3Gi"
          requests:
            cpu: "1"
            memory: "3Gi"
      runtimeClassName: kata

```

# Expected result

get the right container in `c, err := s.findContainer(containerID)`

# Actual result

get the wrong container in `c, err := s.findContainer(containerID)`

# Further information

1. container's config slice has  been changed here 
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/sandbox.go#L1485

```go 
	// Update sandbox config
	for idx, contConfig := range s.config.Containers {
		if contConfig.ID == containerID {
			s.config.Containers = append(s.config.Containers[:idx], s.config.Containers[idx+1:]...)
			break
		}
	}

```

2. save slice item pointer to map
```go
func (s *Sandbox) createContainers(ctx context.Context) error {
	span, ctx := katatrace.Trace(ctx, s.Logger(), "createContainers", sandboxTracingTags, map[string]string{"sandbox_id": s.id})
	defer span.End()

	for i := range s.config.Containers {

		c, err := newContainer(ctx, s, &s.config.Containers[i])
		if err != nil {
			return err
		}
		if err := c.create(ctx); err != nil {
			return err
		}

		if err := s.addContainer(c); err != nil {
			return err
		}
	}

```
related previous commit https://github.com/kata-containers/kata-containers/commit/831224aa224a5d4bf04a21216a4fe8745e2e9549
