### ISSUE TITLE
DNS request failed in user-defined bridge network

### ISSUE THREAD

**Issue by Vlad1mir-D** [kata-containers/kata-containers#6688]
# Description of problem

Applications built using Docker Compose will fail if the services that compose it depend on name resolution to talk to each other.

# Expected result

Docker Compose applications using name resolution should continue to work correctly.

# Actual result

The services are not able to talk to each other. This can easily be reproduced by following steps 1 to 4 of this Docker Compose Getting Started guide: https://docs.docker.com/compose/gettingstarted/. It works correctly if you use Docker with its default runtime (`runc`) but fails as soon as you switch to Kata Containers runtime.

# Further information

- Copied from original issue: https://github.com/kata-containers/runtime/issues/175
- Previously proposed architecture to fix this issue: https://docs.google.com/presentation/d/1ivBToHgNY0fWEhGBaaE6tdUz7p-mn1M0iFKT-Xw6bRw/edit#
- Other original issues:
- - https://github.com/kata-containers/kata-containers/issues/695
- - https://github.com/clearcontainers/runtime/issues/121
- - https://github.com/clearcontainers/runtime/issues/1042
- - https://github.com/clearlinux/distribution/issues/772
- More information: https://gist.github.com/mcastelino/b11e2fcfee9f2509b74240e23c0545fc

Currently available workaround is to use DNS proxy server which will be able to automatically discover containers:
- https://github.com/mageddo/dns-proxy-server
- ttps://github.com/aacebedo/dnsdock
- https://github.com/crosbymichael/skydock

**Comment by Vlad1mir-D** [comment]
This issue is a very long-lasting from the very beginning of Clear Containers so I reopened it in the actual repository of Kata Containers to keep track of it.

**Comment by Vlad1mir-D** [comment]
Bump :)

**Comment by KrolikowskiK** [comment]
any updates on this?

**Comment by samvv** [comment]
I just installed Kata Containers and this is hitting me too. Is there a workaround?

```
kata-runtime  : 3.19.1
   commit   : acae4480ac84701d7354e679714cc9d084b37f44
   OCI specs: 1.2.0
```

**Comment by dinvlad** [comment]
@samvv I can't even get Kata containers to have a network interface altogether (when launched through Docker), not just DNS.. seems like a long-standing issue

**Comment by samvv** [comment]
@dinvlad That's a shame, because Kata Containers sounds like an aswesome piece of software that I currently cannot use because of this.

**Comment by nicko170** [comment]
Seeing this in Kubernetes with Cilium and kata-clh, too.

Can't resolve DNS.

Move back to runc, works perfectly.

**Comment by wolfendale** [comment]
In my setup the DNS is broken because of docker's mangling of resolv.conf, it forces 127.0.0.11 as the nameserver which does not exist in the kata container VM so all DNS lookups fail.

I have a workaround for this where I mount a new resolv.conf file with a working nameserver and this fixes the issue but doesn't allow for internal name resolution.

If you want internal name resolution you can:
- Run a DNS server within the network and have it forward DNS requests to its own 127.0.0.11 (Note this should be using the runc runtime)
- Update the resolv.conf mounted in your kata container to point to the network gateway as this avoids having to rely on the container's IP directly.

Example setup:
```yaml
# docker-compose.yaml
services:
  
  alpine:
    image: alpine:latest
    runtime: kata
    volumes:
      - ${PWD}/resolv.conf:/etc/resolv.conf # undo docker's internal DNS changes
    networks:
      - custom_bridge
   
  coredns:
    image: coredns/coredns:latest
    runtime: runc
    volumes:
      - ${PWD}/Corefile:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile -dns.port 53
    ports:
      - "53:53/udp"
    networks:
      - custom_bridge
 
networks:
  custom_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
           ip_range: 172.28.5.0/24
           gateway: 172.28.5.254
```

```
# Corefile
. {
    forward . 127.0.0.11
    cache 30
    errors
    log
}
```

```
# resolv.conf
nameserver 172.28.5.254
dns_search ht.home
ndots: 0
```

Example test output

```
> docker compose up -d
> docker compose exec -it alpine sh
/ # nslookup alpine
Server:         172.20.5.254
Address:        172.20.5.254:53

Non-authoritative answer:

Non-authoritative answer:
Name:   opencode
Address: 172.20.5.2
```

Hope this helps someone!
