### ISSUE TITLE
dragonball: Why dragonball not support initrd?

### ISSUE THREAD

**Issue by ZhangShuaiyi** [kata-containers/kata-containers#6915]
Currently, dragonball only support boot_info.image. The code in libs/kata-types/src/config/hypervisor/dragonball.rs.
```rust
            if db.boot_info.kernel.is_empty() {
                return Err(eother!(
                    "Guest kernel image for dragonball hypervisor is empty"
                ));
            }
            if db.boot_info.image.is_empty() {
                return Err(eother!(
                    "Guest boot image for dragonball hypervisor is empty"
                ));
            }
            if !db.boot_info.initrd.is_empty() {
                return Err(eother!("Initrd for dragonball hypervisor should be empty"));
            }
```
But dragonball's BootSourceConfig has have initrd_path item.
```rust
/// Strongly typed data structure used to configure the boot source of the microvm.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize, Default)]
#[serde(deny_unknown_fields)]
pub struct BootSourceConfig {
    /// Path of the kernel image.
    /// We only support uncompressed kernel for Dragonball.
    pub kernel_path: String,
    /// Path of the initrd, if there is one.
    /// ps. rootfs is set in BlockDeviceConfigInfo
    pub initrd_path: Option<String>,
    /// The boot arguments to pass to the kernel.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boot_args: Option<String>,
}
```

**Comment by ZhangShuaiyi** [comment]
After change **cold_start_vm** function to set **BootSourceConfig.initrd_path**,  dragonball can boot with initrd.
configuration-dragonball.toml
```toml
[hypervisor.dragonball]
path = ""
ctlpath = ""
kernel = "/opt/kata/share/kata-containers/vmlinux-dragonball-experimental.container"
#image = "/opt/kata/share/kata-containers/kata-containers.img"
initrd = "/opt/kata/share/kata-containers/kata-containers-initrd.img"
```
Use initrd instead of image to boot, vm will reduce a virtio-blk device.
```
[root@hello-kata-dragonball /]# lsblk
[root@hello-kata-dragonball /]# cat /proc/cmdline
reboot=k earlyprintk=ttyS0 initcall_debug panic=1 systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service agent.log_vport=1025 agent.container_pipe_size=1 agent.debug_console agent.debug_console_vport=1026 console=ttyS1 virtio_mmio.device=8K@0xc0000000:5 virtio_mmio.device=8K@0xc0002000:5 virtio_mmio.device=8K@0xc0004000:5
```
