### ISSUE TITLE
clh: Still set useless kernelRootParams when run with initrd

### ISSUE THREAD

**Issue by ZhangShuaiyi** [kata-containers/kata-containers#6921]
Run clh with initrd image
```toml
[hypervisor.clh]
path = "/opt/kata/bin/cloud-hypervisor"
kernel = "/opt/kata/share/kata-containers/vmlinux.container"
#image = "/opt/kata/share/kata-containers/kata-containers.img"
initrd = "/opt/kata/share/kata-containers/kata-containers-initrd.img"
```
Payload.cmdline still has kernelRootParams which is useless, since there is no pmem device.
```
[root@kata-3.0]# ch-remote --api-socket /run/vc/vm/b9ca4b2f5aa6a2c3be2497a9f8648f403421a3250b995fb49f0228bf03738f26/clh-api.sock info | jq .config.payload
{
  "firmware": null,
  "kernel": "/opt/kata/share/kata-containers/vmlinux-5.19.2-102",
  "cmdline": "root=/dev/pmem0p1 rootflags=data=ordered,errors=remount-ro ro rootfstype=ext4 panic=1 no_timer_check noreplace-smp quiet",
  "initramfs": "/opt/kata/share/kata-containers/kata-alpine-3.15.initrd"
}
```
