### ISSUE TITLE
runtime: devmapper is not working when using ctr and {clh,qemu}

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#6977]
I've tested this with the 3.2.0-alpha3 release, and I'm getting the following error:
```
ubuntu@devmapper-clh:~$ sudo ctr run --snapshotter devmapper --runtime io.containerd.kata.v2 --rm docker.io/library/alpine:latest alpine /bin/sh -c date
ctr: failed to create shim task: write /sys/fs/cgroup/vc/cgroup.procs: invalid argument: unknown
```

If I set `sandbox_cgroup_only=true` the error goes away.

@bergwolf, @egernst, @gkurz, any idea on what may be going on here?

**Comment by fidencio** [comment]
This only happens when using a host with cgroups v2.

**Comment by fidencio** [comment]
> @fidencio I have found same issue! Could you please show me your container config.toml? I want to check it out on my kubernetes cluster. Thx!

This is the containerd configuration, but I'm using it only with `ctr`, no `kubernetes` involved here.
```toml
Last login: Tue May 30 07:11:32 2023 from 192.168.122.1
ubuntu@devmapper-clh:~$ cat /etc/containerd/config.toml
# 2023-05-25T19:34:42+00:00: Added by bash
[debug]
log_level = "debug"

[plugins]
  [plugins.devmapper]
    pool_name = "contd-thin-pool"
    base_image_size = "4096MB"
  [plugins."io.containerd.grpc.v1.cri"]
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "kata"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
          runtime_type = "io.containerd.kata.v2"
```

**Comment by fidencio** [comment]
Let me do a braindump on what I'm seeing here.

I was able to reproduce the issue on Ubuntu 22.04 and Fedora 37.
The failure we're getting comes from: https://github.com/kata-containers/kata-containers/blob/099b4b0d0e3db31b9054e7240715f0d7f51f9a1c/src/runtime/pkg/resourcecontrol/cgroups.go#L317

That's calling a code from containerd, see: https://github.com/containerd/cgroups/blob/37e6f8313779a271987cc0921ee8a35e922cbfb8/v2/manager.go#L339

That code will call https://github.com/containerd/cgroups/blob/37e6f8313779a271987cc0921ee8a35e922cbfb8/v2/manager.go#L163

Which will finally call https://github.com/containerd/cgroups/blob/37e6f8313779a271987cc0921ee8a35e922cbfb8/v2/manager.go#L150

And the part returning the `EINVAL` is returned here https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/os/file.go;l=725, by the `write` function.

I'm not sure why it's only happening with the devmapper snapshotter, but that's the situation right now.
Also, retrying on the `write` will not give us a better result.

When `stat`ing the problematic file in both cases (using VirtioFS and devmapper), we see:
```
VirtioFS:
  File: /sys/fs/cgroup/vc/cgroup.procs
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 1dh/29d	Inode: 18462       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-05-29 15:26:09.164370831 +0000
Modify: 2023-05-29 15:26:09.162167478 +0000
Change: 2023-05-29 15:26:09.162167478 +0000
 Birth: -

Devmapper:
  File: /sys/fs/cgroup/vc/cgroup.procs
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 1dh/29d	Inode: 18592       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-05-29 15:27:36.379150845 +0000
Modify: 2023-05-29 15:27:36.379150845 +0000
Change: 2023-05-29 15:27:36.379150845 +0000
 Birth: -
```

So, no differences that I could actually see.
