### ISSUE TITLE
io.katacontainers.config.hypervisor.kernel_params not working

### ISSUE THREAD

**Issue by jclab-joseph** [kata-containers/kata-containers#7093]
# Description of problem

- version: `3.2.0-alpha3 (commit 9aae3333437948764324f6e51e126fce8808c26b)`
- /etc/kata-containers/configuration.toml: `enable_annotations = [".*"]`

Containerd:
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
  runtime_type = "io.containerd.kata.v2"
  privileged_without_host_devices = true

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
  ConfigPath = "/etc/kata-containers/configuration.toml"
```

Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    io.katacontainers.config.hypervisor.kernel_params: "test=1234"
spec:
  runtimeClassName: kata
  containers:
  - name: nginx
    image: nginx
```

# Actual result

```
# cat /proc/cmdline 
root=/dev/pmem0p1 rootflags=data=ordered,errors=remount-ro ro rootfstype=ext4 panic=1 no_timer_check noreplace-smp quiet systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket
```

# Further information

https://gist.github.com/jclab-joseph/01ac47ac47d6c9a4038e8d0f8a91ec2a
