### ISSUE TITLE
Using fsGroup with direct-assign breaks symbolic link insides container file system

### ISSUE THREAD

**Issue by alakesh** [kata-containers/kata-containers#7364]
# Description of the problem

1. Create a pod spec that has security context and uses fsGroup and persistentVolumeClaim and apply the config

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repro
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: scaleio
---
apiVersion: <version>
kind: StatefulPod
metadata:
  name: repro
spec:
  podSpec:
    containers:
    - image: <any linux>
      command: ["/bin/sh", "-c"]
      args: ["while (true); do sleep 10; done;"]
      imagePullPolicy: Always
      name: c1
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 2Gi
      volumeMounts:
      - mountPath: /mnt/volume
        name: data-volume
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
    priorityClassName: p1
    restartPolicy: Always
    runtimeClassName: microvm
    securityContext:
      fsGroup: 51020
      runAsGroup: 51020
      runAsUser: 264
    volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: repro
  stickyIP: false
  suspend: false
  terminationPolicy:
    authority: onDelete
    serviceInstance: repro
    serviceName: repro
```
2. Inside the container

```
$ mkdir /mnt/volume/data && touch /mnt/volume/data/file && ln -s /mnt/volume/data/file /mnt/volume/link && ls -lart /mnt/volume/
$ echo "foo" > /mnt/volume/link
$ cat /mnt/volume/link
foo
$ cat /mnt/volume/data/file
```
So all looks good till now. 

3. Next we delete the pod which will result in recreating it.

4. When the pod comes up try to read the symbolic link

```
[/]$ cat /mnt/volume/link

```
This results in container status changes to error state and we see a lot of I/O error for metadata and logs in kernel dmesg.

# Expected result

The container is expected to go into "Running" state

# Actual result

It goes into "RunContainerError" state instead. 
There are lot of XFS errors in demsg

```
[Tue Jul 11 23:57:17 2023] XFS (vda): metadata I/O error in "xfs_buf_iodone_callback_error" at daddr 0x40 len 32 error 5
[Tue Jul 11 23:57:22 2023] XFS (vda): metadata I/O error in "xfs_buf_iodone_callback_error" at daddr 0x40 len 32 error 5
[Tue Jul 11 23:57:27 2023] XFS (vda): metadata I/O error in "xfs_buf_iodone_callback_error" at daddr 0x40 len 32 error 5
[Tue Jul 11 23:57:32 2023] XFS (vda): metadata I/O error in "xfs_buf_iodone_callback_error" at daddr 0x40 len 32 error 5
[Tue Jul 11 23:57:37 2023] XFS (vda): metadata I/O error in "xfs_buf_iodone_callback_error" at daddr 0x40 len 32 error 5
[Tue Jul 11 23:57:42 2023] XFS (vda): metadata I/O error in "xfs_buf_iodone_callback_error" at daddr 0x40 len 32 error 5
[Tue Jul 11 23:57:46 2023] XFS (vda): log I/O error -5
[Tue Jul 11 23:57:46 2023] XFS (vda): xfs_do_force_shutdown(0x2) called from line 1250 of file fs/xfs/xfs_log.c. Return address = 00000000e69433c3
[Tue Jul 11 23:57:46 2023] XFS (vda): Log I/O Error Detected. Shutting down filesystem
[Tue Jul 11 23:57:46 2023] XFS (vda): Please unmount the filesystem and rectify the problem(s)
```

# Further information
