### ISSUE TITLE
Does Kata Containers support ebpf? `CONFIG_DEBUG_INFO_BTF` seems no effort

### ISSUE THREAD

**Issue by Wh1isper** [kata-containers/kata-containers#7556]
Hello, I'm trying to run ebpf programs (including `bcc` tools) inside kata containers to collect the guest kernel monitoring information, but I'm finding that it seems that the guest kernel doesn't have the components that BTF or `bcc` depend on such as `/sys/kernel/tracing/`, `/sys/kernel/btf/vmlinux`, etc.

In `/opt/kata/share/defaults/kata-containers/configuration.toml`, I use my own build kernel 

```toml
[hypervisor.qemu]
path = "/opt/kata/bin/qemu-system-x86_64"
#kernel = "/opt/kata/share/kata-containers/vmlinux.container"
kernel = "/usr/share/kata-containers/vmlinuz.container"
image = "/opt/kata/share/kata-containers/kata-containers.img"
# initrd = "/opt/kata/share/kata-containers/kata-containers-initrd.img"
machine_type = "q35"
```

and config `privileged_without_host_devices=true` in `/etc/containerd/config.toml`, This step seems unnecessary to me, as I only want to collect the guest kernel monitoring information.

```toml
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    [plugins."io.containerd.grpc.v1.cri".containerd]
      default_runtime_name = "nvidia"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
          privileged_without_host_devices = false
          runtime_engine = ""
          runtime_root = ""
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
          runtime_type = "io.containerd.kata.v2"
          privileged_without_host_devices = true

  [plugins.cri]
    [plugins.cri.containerd]
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.runc.v2"
    [plugins.cri.cni]
      # conf_dir is the directory in which the admin places a CNI conf.
conf_dir = "/etc/cni/net.d"
[plugins.cri.containerd.runtimes.kata]
  runtime_type = "io.containerd.kata.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration.toml"
[plugins.cri.containerd.runtimes.kata-clh]
  runtime_type = "io.containerd.kata-clh.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata-clh.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-clh.toml"
[plugins.cri.containerd.runtimes.kata-dragonball]
  runtime_type = "io.containerd.kata-dragonball.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata-dragonball.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-dragonball.toml"
[plugins.cri.containerd.runtimes.kata-fc]
  runtime_type = "io.containerd.kata-fc.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata-fc.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-fc.toml"
[plugins.cri.containerd.runtimes.kata-qemu]
  runtime_type = "io.containerd.kata-qemu.v2"
  privileged_without_host_devices = true
  pod_annotations = ["io.katacontainers.*"]
  [plugins.cri.containerd.runtimes.kata-qemu.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-qemu.toml"
```

Then I start container via `nerdctl` with `--privileged`

```bash
sudo nerdctl run -it --runtime=io.containerd.kata.v2 --privileged --rm wh1isper/ubuntu-bcc
```

I got an error. 

```bash
WARN[0000] cannot set cgroup manager to "systemd" for runtime "io.containerd.kata.v2"
FATA[0002] failed to create shim task: Conflicting device updates for /dev/nvme0n1p3: unknow
```

The `privileged` may not be needed here, as I just want to observe what's going on inside the container. So I tried to start the container without privileged, and it worked.

```bash
sudo nerdctl run -it --runtime=io.containerd.kata.v2 --rm wh1isper/ubuntu-bcc
```

But when I try to run the libbpf minimal program `/root/minimal` as well as the bcc example `/usr/share/bcc/examples/hello_world.py`, I get the following error

```bash
$ /root/minimal
libbpf: loading object 'minimal_bpf' from buffer
libbpf: elf: section(2) .symtab, size 216, link 1, flags 0, type=2
libbpf: elf: section(3) tp/syscalls/sys_enter_write, size 104, link 0, flags 6, type=1
libbpf: sec 'tp/syscalls/sys_enter_write': found program 'handle_tp' at insn offset 0 (0 bytes), code size 13 insns (104 bytes)
libbpf: elf: section(4) license, size 13, link 0, flags 3, type=1
libbpf: license of minimal_bpf is Dual BSD/GPL
libbpf: elf: section(5) .bss, size 4, link 0, flags 3, type=8
libbpf: elf: section(6) .rodata, size 28, link 0, flags 2, type=1
libbpf: elf: section(7) .reltp/syscalls/sys_enter_write, size 32, link 2, flags 40, type=9
libbpf: elf: section(8) .BTF, size 608, link 0, flags 0, type=1
libbpf: elf: section(9) .BTF.ext, size 160, link 0, flags 0, type=1
libbpf: looking for externs among 9 symbols...
libbpf: collected 0 externs total
libbpf: map 'minimal_.bss' (global data): at sec_idx 5, offset 0, flags 400.
libbpf: map 0 is "minimal_.bss"
libbpf: map 'minimal_.rodata' (global data): at sec_idx 6, offset 0, flags 80.
libbpf: map 1 is "minimal_.rodata"
libbpf: sec '.reltp/syscalls/sys_enter_write': collecting relocation for section(3) 'tp/syscalls/sys_enter_write'
libbpf: sec '.reltp/syscalls/sys_enter_write': relo #0: insn #2 against 'my_pid'
libbpf: prog 'handle_tp': found data map 0 (minimal_.bss, sec 5, off 0) for insn 2
libbpf: sec '.reltp/syscalls/sys_enter_write': relo #1: insn #6 against '.rodata'
libbpf: prog 'handle_tp': found data map 1 (minimal_.rodata, sec 6, off 0) for insn 6
libbpf: Kernel doesn't support BTF, skipping uploading it.
libbpf: map 'minimal_.bss': created successfully, fd=3
libbpf: map 'minimal_.rodata': created successfully, fd=4
libbpf: Error freezing map(minimal_.rodata) as read-only: Operation not permitted
libbpf: map 'minimal_.rodata': failed to create: Operation not permitted(-1)
libbpf: permission error while running as root; try raising 'ulimit -l'? current value: 8.0 MiB
libbpf: failed to load object 'minimal_bpf'
libbpf: failed to load BPF skeleton 'minimal_bpf': -1
Failed to load and verify BPF skeleton
```

```
$ /usr/share/bcc/examples/hello_world.py
bpf: Failed to load program: Operation not permitted

Traceback (most recent call last):
  File "/usr/share/bcc/examples/hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python3/dist-packages/bcc-0.28.0+8422cd44-py3.10.egg/bcc/__init__.py", line 487, in __init__
  File "/usr/lib/python3/dist-packages/bcc-0.28.0+8422cd44-py3.10.egg/bcc/__init__.py", line 1465, in _trace_autoload
  File "/usr/lib/python3/dist-packages/bcc-0.28.0+8422cd44-py3.10.egg/bcc/__init__.py", line 523, in load_func
Exception: Need super-user privileges to run
```

Then I checked `CONFIG_DEBUG_INFO_BTF` and `/sys/kernel/btf/vmlinux` and `/sys/kernel/tracing` :

```bash
$zgrep CONFIG_DEBUG_INFO_BTF /proc/config.gz # noting, not found CONFIG_DEBUG_INFO_BTF 
```

```bash
$ ll /sys/kernel/btf/vmlinux
ls: cannot access '/sys/kernel/btf/vmlinux': No such file or directory
```

```bash
$ ll /sys/kernel/tracing
ls: cannot access '/sys/kernel/tracing': No such file or directory
```

But `KPROBE` can be found on kernel config

```bash
$ zgrep KPROBE /proc/config.gz
CONFIG_HAVE_KPROBES=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
```

**Q1: Why is the kernel configuration running in kata different than when I build it?**

**Q2: Is there something I'm missing in the configuration, like `kernel modules`?**
