### ISSUE TITLE
How to handle socket and hostPath in kata-containers?

### ISSUE THREAD

**Issue by Joffref** [kata-containers/kata-containers#8024]
I'm looking to use SPIRE along kata-containers on kubernetes. I'm facing an issue, when I mount the unix socket inside my pod the connection to it is refused whereas in a pod with containerd it works. Would you have any thoughts on that?

**Logs**
```
time="2023-09-20T22:40:44Z" level=error msg="Failed to watch the Workload API: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /spiffe-workload-api/spire-agent.sock: connect: connection refused\""
```
**Further information**
- Used CSI driver: https://github.com/spiffe/spiffe-csi
- Deployment example:
```
apiVersion: v1
kind: Pod
metadata:
  name: example-workload
spec:
  containers:
  - name: example-workload
    image: spiffe-csi-driver-example-workload:example
    imagePullPolicy: Never
    volumeMounts:
    - name: spiffe-workload-api
      mountPath: /spiffe-workload-api
      readOnly: true
    env:
    - name: SPIFFE_ENDPOINT_SOCKET
      value: unix:///spiffe-workload-api/spire-agent.sock
  volumes:
  - name: spiffe-workload-api
    csi:
      driver: "csi.spiffe.io"
      readOnly: true
 ```
 
**Before raising this question**

- [x] Have you looked at our [document](https://github.com/kata-containers/kata-containers/tree/main/docs) and still haven't found the answer?
