### ISSUE TITLE
CC: Add sealed secrets support

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/kata-containers#8123]
In CCv0 a feature was added to support [sealed secrets](https://github.com/kata-containers/kata-containers/issues/7555). The idea behind this is that Kubernetes secrets are accessible to the kubernetes admin, that we don't want to trust, so we wrap secrets with an encryption and then decrypt them on the guest image, inside the TCB.

## Things to note/include with this work
- The code changes for sealed secrets are fairly new, so we might be able to cherry pick the commits from https://github.com/kata-containers/kata-containers/pull/7570/ without too many changes
- I think we want to add support for sealed secrets in initrd here, or at least create a follow up issue
- New tests
  - There was a new test case added for this in https://github.com/kata-containers/tests/pull/5754, but we might want to change it up a bit
    - We could separate the environment and volume tests into two test cases so that if there is a failure we can isolate it more easily
    - We should consider adding a negative test case when the incorrect key is used on the host to check that the unsealing doesn't work
    - This test case has switching logic for the KBC in the test case. We might want to try and make this more generic and easier to apply to different KBCs/TEE by extracting out the KBC/TEE logic into library functions, so the test cases are cleaner, similar to the approach done in https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-confidential.bats rather than a pure cherry-pick
    - We need to build on the recent attestation tests #8870 to set up the KBS correctly

## Questions
- ~How do we control and create the attestation-agent integration in the rootfs? If it is small, should we always include it, or do we need separate versions of the image with AA installed? How about support for mutliple KBCs? Currently I don't think there are any plans to support a single attestation-agent binary with multiple KBC modules built, so does this mean that we need different images build for each KBC we support, which will make kata-deploy larger and potential more painful with extra runtime classes? @Xynnn007 @fidencio~ Addressed in the above notes

## Acceptance Criteria

For each supported platform (different TEEs on kubernetes):

_**Scenario: Sealed secrets unsealed as volume correctly**_
**Given** I have a version of kata deployed that is configured to have a decryption key in its KBS under the `"default/sealed-secret/test` resource
  **And** I've created a kubernetes secret called `sealed secret` from a secret that has been 'sealed' with the same key
**When** I try and create a pod/job from a config with:
```
    env:
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sealed-secret
          key: password 
 volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /tmp/secret-volume
  # Expose secret data Containers through a volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: sealed-secret
```
that prints the content of `/tmp/secret-volume/password`
**Then** The pod is successfully created and we can see the unsealed secret in `kubectl logs`

_**Scenario: Sealed secrets unsealed as envar correctly**_
**Given** I have a version of kata deployed that is configured to have a decryption key in its KBS under the `"default/sealed-secret/test` resource
  **And** I've created a kubernetes secret called `sealed secret` from a secret that has been 'sealed' with the same key
**When** I try and create a pod/job from a config with:
```
env:
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sealed-secret
          key: password
```
that prints the value of the `SECRET_PASSWORD` envar
**Then** The pod is successfully created and we can see the unsealed secret in `kubectl logs`

_**Scenario: Sealed secrets volume mount fails with incorrect key**_
**Given** I have a version of kata deployed that is configured to have a decryption key in its KBS under the `"default/sealed-secret/test` resource
  **And** I've created a kubernetes secret called `sealed secret` from a secret that has been 'sealed' with a different key
**When** I try and create a pod/job from a config with:
```
    env:
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sealed-secret
          key: password 
 volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /tmp/secret-volume
  # Expose secret data Containers through a volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: sealed-secret
```
that prints the content of `/tmp/secret-volume/password`
**Then** We *can't* see the unsealed secret in `kubectl logs` and ideally see some sort of error in the logs to indicate that that the secret wasn't valid

_**Scenario: Sealed secrets envar fails with incorrect key**_
**Given** I have a version of kata deployed that is configured to have a decryption key in its KBS under the `"default/sealed-secret/test` resource
  **And** I've created a kubernetes secret called `sealed secret` from a secret that has been 'sealed' with a different key
**When** I try and create a pod/job from a config with:
```
env:
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: sealed-secret
          key: password
```
that prints the value of the `SECRET_PASSWORD` envar
**Then** We *can't* see the unsealed secret in `kubectl logs` and ideally see some sort of error in the logs to indicate that that the secret wasn't valid
