### ISSUE TITLE
kubectl exec into pod with 2.0 hangs

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#869]
# Get your issue reviewed faster

Running Kubernetes 1.18, containerd v1.3.4 and Kata 2.0.0-rc0 or 2.0.0-rc1.

# Description of problem

Console hangs when executing kubectl exec -it for a running pod.(replace this text with the list of steps you followed)

# Expected result

An interactive console 
# Actual result

Hangs

# Further information

On 1.x, this works without issue.

Example:

bb.yaml:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: bb
spec:
  containers:
  - name: bb
    image: busybox
    command: ["sh"]
    args: ["-c", "sleep infinity"]
  runtimeClassName: kata-qemu
```

Run test:
```
kubectl apply -f bb.yaml
(wait until Ready)
kubectl exec -it bb -- bash
```
