### ISSUE TITLE
tools/genpolicy: unable to parse 'spec.dnsPolicy'

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#8832]
The genpolicy tool fails to parse a pod yaml that contains the `dnsPolicy` configuration.

How to reproduce the problem:

1. Create the pod yaml like below:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server-app
spec:
  runtimeClassName: kata-remote
  containers:
    - name: http-server
      image: registry.fedoraproject.org/fedora
      ports:
        - containerPort: 8080
      command: ["python3"]
      args: [ "-m", "http.server", "8080"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
```

2. Try to generate the Policy rego as:

```
$ ./genpolicy -r -y pod.yaml 
thread 'main' panicked at 'Unsupported field: spec.dnsPolicy', src/yaml.rs:303:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Removing `dnsPolicy: ClusterFirst` from the Pod yaml it should work fine. Found this issue while reviewing https://github.com/kata-containers/kata-containers/pull/8814
