### ISSUE TITLE
Bidirectional mount does not work in CVM

### ISSUE THREAD

**Issue by enuoCM** [kata-containers/kata-containers#8853]
# Description of problem

Two containers share data by emptyDir (mountPropagation: Bidirectional), new mounted share folder only works in VM other than CVM.

1. Apply pod-empty-share.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-empty-vm
spec:
  runtimeClassName: kata-qemu    # VM
  restartPolicy: Always
  containers:
  - name: app1
    command:
    - "bin/sh"
    - "-c"
    - "sleep 10000"
    image: docker.io/library/busybox:latest 
    volumeMounts:
    - name: test-shared-data
      mountPath: /data1
      mountPropagation: Bidirectional
    securityContext:
      privileged: true 
  - name: app2 
    command:
    - "bin/sh"
    - "-c"
    - "sleep 10000"
    image: docker.io/library/busybox:latest
    volumeMounts:
    - name: test-shared-data
      mountPath: /data2
      mountPropagation: Bidirectional
    securityContext:
      privileged: true
  volumes:
  - name: test-shared-data
    emptyDir:
      medium: Memory
      sizeLimit: 512Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-empty-cvm
spec:
  runtimeClassName: kata-qemu-snp
  restartPolicy: Always
  containers:
  - name: app1
    command:
    - "bin/sh"
    - "-c"
    - "sleep 10000"
    image: docker.io/library/busybox:latest
    volumeMounts:
    - name: test-shared-data
      mountPath: /data1
      mountPropagation: Bidirectional
    securityContext:
      privileged: true
  - name: app2
    command:
    - "bin/sh"
    - "-c"
    - "sleep 10000"
    image: docker.io/library/busybox:latest
    volumeMounts:
    - name: test-shared-data
      mountPath: /data2
      mountPropagation: Bidirectional
    securityContext:
      privileged: true
  volumes:
  - name: test-shared-data
    emptyDir:
      medium: Memory
      sizeLimit: 512Mi
```

2. Waiting for pods on
```
# kgp
NAME                            READY   STATUS    RESTARTS   AGE
pod-empty-cvm                   2/2     Running   0          21m
pod-empty-vm                    2/2     Running   0          21m
```

3.  Enter container `app1` of two pods, and mount a  `share` folder to '/data1/share'
```
# k exec -it pod-empty-vm -c app1 -- sh
# mkdir /share && cd share && touch hi && mkdir /data1/share && mount --bind /share /data1/share
# exit
# k exec -it pod-empty-cvm -c app1 -- sh
# mkdir /share && cd share && touch hi && mkdir /data1/share && mount --bind /share /data1/share
# exit
```

4. Enter container `app2` of two pods to check the mount result
```
# k exec -it pod-empty-vm -c app2 -- sh
# mount | grep share
none on /data2/share type virtiofs (rw,relatime)
# ls /data2/share/
hi
# exit
# k exec -it pod-empty-cvm -c app2 -- sh
# mount | grep share
# ls /data2/share/
```

# Expected result

In pod-empty-cvm, container `app2` should have new mount point 'data2/share'.

# Actual result

In pod-empty-cvm, container `app2` dose not have new mount point 'data2/share'.
