### ISSUE TITLE
agent: kata-agent loses container io occasionally

### ISSUE THREAD

**Issue by gaohuatao-1** [kata-containers/kata-containers#9186]
# Get your issue reviewed faster

To help us understand the problem more quickly, please do the following:

1. Run the `kata-collect-data.sh` script, which is installed as part of Kata Containers
   or `kata-containers.collect-data`, which is installed as part of the Kata Containers
   snapcraft package.
   ```sh
   $ sudo kata-collect-data.sh > /tmp/kata.log
   ```
   or
   ```sh
   $ sudo kata-containers.collect-data > /tmp/kata.log
   ```
1. Review the output file (`/tmp/kata.log`) to ensure it doesn't
   contain any private / sensitive information
1. Paste the *entire* contents of the file into this issue as a comment
   (the script generates markdown format output).

The information provided will help us to understand the problem more quickly
so saves time for both of us! :smile:

# Description of problem
We create multi-copy pods through job with yaml as follows. Then we check the container log file, the weird thing is that there is no container logs. That is to say, the last container io msg is lost.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: gtest-container-io
  namespace: default
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 20
  parallelism: 20
  suspend: false
  template:
    metadata:
      annotations:
    spec:
      containers:
      - args:
        - -c
        - sleep 15;str=stdout+`date`;echo $str
        command:
        - /bin/sh
        image: xxxx:v1
        imagePullPolicy: IfNotPresent
        name: ght-exec
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

# Expected result
We can get the complete container io output.
![image](https://github.com/kata-containers/kata-containers/assets/22569211/249d9099-8907-4a43-9feb-0b1d5928edd0)

# Actual result
![image](https://github.com/kata-containers/kata-containers/assets/22569211/dcf2c49d-009e-44e7-9794-3c13798d0d0c)
The 0.log file for container ght-exec is empty.

# Further information
