### ISSUE TITLE
Failed to do mount in kata containers with privileged mode

### ISSUE THREAD

**Issue by kinderyj** [kata-containers/kata-containers#9253]
1. Start a kata containers with --privileged in kubernetes pod
2. kubectl exec -it podname sh
3. mount /dev/sdv /mnt/

got error:
mount: permission denied (are you root?)

pod yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - image: nginx
    name: pod1
    command: ['/bin/sh','-c','sleep 24h'] 
    securityContext:
      privileged: true
      runAsUser: 0
      runAsGroup: 0
```

**Comment by Apokleos** [comment]
Hi, @kinderyj sorry for the trouble! Could you please give us more detailed info of the kata-containers you're using ?

**Comment by kinderyj** [comment]
> Hi, @kinderyj sorry for the trouble! Could you please give us more detailed info of the kata-containers you're using ?

Hi, thanks~ I'm using kata 3.2.0 with dragonball as the vmm.

**Comment by Apokleos** [comment]
In general, due to the security and isolation design of kata containers, executing `mount` inside the container is often restricted. You need to evaluate the risks and choose an appropriate solution based on your specific requirements.

If you have to do so, maybe you can try to add some Linux capabilities:
```yaml
    securityContext:
      capabilities:
        add: ["NET_ADMIN", ...]
```
