### ISSUE TITLE
CC: run guest-pull image tests on non-TEE CI jobs

### ISSUE THREAD

**Issue by wainersm** [kata-containers/kata-containers#9410]
## Context

The [guest-pull image tests](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-guest-pull-image.bats) were merged in PR #8484 , and they are currently executed only in [TEE (SNP, SEV, TDX) jobs](https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/run-kata-coco-tests.yaml).

The [CoCo release v0.9.0](https://github.com/confidential-containers/confidential-containers/issues/200) aim to provide the very first CoCo release out of Kata's main branch. Compared to the previous releases we don't plan to have feature parity, nor full support to TEEs. Instead the dev/test team will focus on putting together features that can be emulated/mocked on non-TEE environments.

Therefore, it will be required to run the guest-pull image tests on non-TEE CI jobs for the 0.9.0 release. 

## Work breakdown

TBD

Cc @ChengyuZhu6

**Comment by wainersm** [comment]
To fill out the "work breakdown" section, I'd like to raise a discussion: what non-TEE job(s) it should be running the guest-pull image tests?

Before going any further, let's remember that the guest-pull image feature depends on nydus-snapshotter installed in environment. Ok?

The [port attestation agent from CCv0 branch to main branch](https://github.com/kata-containers/kata-containers/pull/8870) will have its tests running on the non-TEE [run-k8s-tests-on-aks](https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/run-k8s-tests-on-aks.yaml) for `qemu` hypervisor configuration which execute the kata-qemu "vanilla" tests on k8s.

Suppose that we choose to onboard on the existing non-TEE alike the attestation agent tests. There will be needed to install nydus-snapshotter and that's going to change the behavior of existing tests (I believe the tests will even break). Alternatively we could create a new parameter on the matrix (e.g. 'snapshotter') where only one generated job will be set to run the non-TEE tests. For example,

(from .github/workflows/run-k8s-tests-on-aks.yaml)
```yaml
  run-k8s-tests:
    strategy:
      fail-fast: false
      matrix:
        host_os:
          - ubuntu
        vmm:
          - clh
          - dragonball
          - qemu
          - stratovirt
          - cloud-hypervisor
        instance-type:
          - small
          - normal
        include:
          - host_os: cbl-mariner
            vmm: clh
            instance-type: small
          - host_os: cbl-mariner
            vmm: clh
            instance-type: normal
```

Becomes (notice the new `snapshotter` parameter):

```yaml
  run-k8s-tests:
    strategy:
      fail-fast: false
      matrix:
        host_os:
          - ubuntu
        snapshotter:
          - none
        vmm:
          - clh
          - dragonball
          - qemu
          - stratovirt
          - cloud-hypervisor
        instance-type:
          - small
          - normal
        include:
          - host_os: cbl-mariner
            snapshotter: none
            vmm: clh
            instance-type: small
          - host_os: cbl-mariner
            snapshotter: none
            vmm: clh
            instance-type: normal
         # Here goes the new non-TEE job for the guest-pull tests
          - host_os: ubuntu
            snapshotter: nydus
            vmm: qemu
            instance-type: small
```

The matrix above can get even more complex if we introduce `pull-type` (guest-pull, host-pull) and possible other parameter that will be required for the non-TEE CoCo tests.

Thus, I suggest that we start thinking in moving the non-TEE CoCo jobs out of `.github/workflows/run-k8s-tests-on-aks.yaml`. On suggestion is to move it to `.github/workflows/run-kata-coco-tests.yaml`...
