### ISSUE TITLE
[RFC] Unified framework with CDI for diverse vendor GPUs in Kata

### ISSUE THREAD

**Issue by Apokleos** [kata-containers/kata-containers#9561]
# Issues with Kata using Diverse Vendor GPUs
The diverse usage patterns across different GPU vendors introduce significant compatibility challenges for users employing Kata with GPUs from various manufacturers. This necessitates extensive adaptation efforts, hindering both user experience and Kata's widespread adoption.
Building on the success of Kata's Container Device Interface (CDI) integration with NVIDIA GPUs, we propose a unified and simplified approach to address this challenge.
# Goals：
A unified framework promotes compatibility for diverse vendor GPUs, reducing the need for custom adaptations
# Solution：
1. Introduce a designated path "kata-linux-gpu-drivers" to create soft links for various GPU drivers and point them to this path. Create a soft link from different GPU driver paths to this designated target path. This path is located in /opt/kata/share/kata-linux-gpu-drivers 
2. Introduce kata-ctl cdi subcommands to manage GPU drivers. These subcommands will read files from the designated path, construct file lists based on template files, and generate CDI configuration files.
3. Leverage containerd/CDI to modify OCI spec. This step will integrate CDI configuration into the OCI specification which containerd/cdi is responsible for the conversion work in this section.
4. Utilize sandbox bind mounts to share files with the guest for tasks like kernel loading and service configuration that must be performed within the guest environment. This method will make the *.ko files or services configuraions accessible within the guest environment.
5. Employ VM's prestart hooks to do load kernel modules or perform other must services. These hooks will trigger the loading of necessary kernel modules and other services before creating containers.
6. Leverage Kata's share fs volume capability alongside CDI configuration files.This approach will share host files (binaries, libraries) with Kata containers using CDI configuration files.
# Key issues to address：
**1. How to generate GPU driver configurations ？**
As we all know, not all GPU driver files need to be shared with the container environment. To address this, we provide a customizable template file with limited extensibility which acts as a filter. By comparing entries in this template file, we can effectively filter out unnecessary parts, ensuring that the generated configuration only includes essential content.
We'll use NVIDIA GPU Driver as an example to illustrate. A possible template file for NVIDIA GPU drivers looks like as below:
```yaml
# Copyright (c) 2024 Ant Group
# 
# SPDX-License-Identifier: Apache-2.0
# 
# template.yaml for GPU Driver

libs:
  video:
  - libvdpau_nvidia.so # NVIDIA VDPAU ICD
  - libnvidia-encode.so # Video encoder
  # - libnvidia-opticalflow.so # NVIDIA Opticalflow library
  - libnvcuvid.so # Video decoder
  utility:
  - libnvidia-ml.so # Management library
  - libnvidia-cfg.so # GPU configuration
  - libnvidia-nscq.so # Topology info for NVSwitches and GPUs
  compute:
  - libcuda.so # CUDA driver library
  # - libcudadebugger.so # CUDA Debugger Library
  - libnvidia-opencl.so # NVIDIA OpenCL ICD
  # - libnvidia-gpucomp.so # Shared Compiler Library
  # - libnvidia-ptxjitcompiler.so # PTX-SASS JIT compiler (used by libcuda)
  # - libnvidia-fatbinaryloader.so # fatbin loader (used by libcuda)
  - libnvidia-allocator.so # NVIDIA allocator runtime library
  - libnvidia-compiler.so # NVVM-PTX compiler for OpenCL (used by libnvidia-opencl)
  # - libnvidia-pkcs11.so # Encrypt/Decrypt library
  # - libnvidia-pkcs11-openssl3.so # Encrypt/Decrypt library (OpenSSL 3 support) 
  - libnvidia-nvvm.so # The NVVM Compiler library
  graphics:
  # - libnvidia-egl-wayland.so # EGL wayland platform extension (used by libEGL_nvidia)
  - libnvidia-eglcore.so # EGL core (used by libGLES*[_nvidia] and libEGL_nvidia)
  - libnvidia-glcore.so # OpenGL core (used by libGL or libGLX_nvidia)
  - libnvidia-tls.so # Thread local storage (used by libGL or libGLX_nvidia)
  - libnvidia-glsi.so # OpenGL system interaction (used by libEGL_nvidia)
  - libnvidia-fbc.so # Framebuffer capture
  - libnvidia-ifr.so # OpenGL framebuffer capture
  - libnvidia-rtcore.so # Optix
  - libnvoptix.so # Optix
  graphics_glvnd:
  # - libGLX.so",                      # GLX ICD loader 
  # - libOpenGL.so",                   # OpenGL ICD loader 
  # - libGLdispatch.so",               # OpenGL dispatch (used by libOpenGL, libEGL and libGLES*) 
  - libGLX_nvidia.so # OpenGL/GLX ICD
  - libEGL_nvidia.so # EGL ICD
  - libGLESv2_nvidia.so # OpenGL ES v2 ICD
  - libGLESv1_CM_nvidia.so # OpenGL ES v1 common profile ICD
  - libnvidia-glvkspirv.so # SPIR-V Lib for Vulkan
  - libnvidia-cbl.so # VK_NV_ray_tracing
  graphics_compat:
  - libGL.so # OpenGL/GLX legacy _or_ compatibility wrapper (GLVND)
  - libEGL.so # EGL legacy _or_ ICD loader (GLVND)
  - libGLESv1_CM.so # OpenGL ES v1 common profile legacy _or_ ICD loader (GLVND)
  - libGLESv2.so # OpenGL ES v2 legacy _or_ ICD loader (GLVND)
  ngx:
  - libnvidia-ngx.so # NGX library
  dxcore:
  - libdxcore.so # Core library for dxcore support
bins:
  utility:
  - nvidia-smi                      # System management interface
  - nvidia-debugdump                # GPU coredump utility
  - nvidia-persistenced             # Persistence mode utility
  - nv-fabricmanager                # NVSwitch fabric manager utility
  # - nvidia-modprobe                 # Kernel module loader
  # - nvidia-settings                 # X server settings
  # - nvidia-xconfig                  # X xorg.conf editor
  compute:
  - nvidia-cuda-mps-control         # Multi process service CLI
  - nvidia-cuda-mps-server          # Multi process service server
```
Then based on this template, we need to navigate to the GPU driver directory and perform file search matching. During driver file searching, entries in the template file are matched against the discovered files, and only those that matched are retained, ensuring that the newly generated driver-config.yaml incorporates solely the essential components. 

In this design, we do require such intermediate file named driver-config.yaml, which serves as the input for CDI conversion. Since different scenarios may involve distinct generation methods, the primary approaches currently employed are as follows:

- NVIDIA GPUs on host but not installed: Utilize kata-ctl to gather files from the compiled NVIDIA driver path and construct a driver-config.yaml file by categorizing files based on file type.
- Other Vendor GPUs: Leverage vendor-specific mechanisms to generate a driver-config.yaml file that adheres to the defined specifications.

**2. How to generate CDI configurations ？**
To address this issue, The CDI Specification has been introduced in kata-ctl gpu subcommand to help convert driver specifications into CDI specifications. 
Building upon the solution to the first key issue, we will proceed to convert the GPU Driver config data structure to the corresponding CDI Spec data structure and utilize this conversion as the foundation to generate the expected CDI configuration file.
During the conversion process, we perform corresponding conversions based on the type of each item in the driver config. 
For instance, for library files and executable files, we need to construct a `Mount`, properly configure `containerPath` and `hostPath` information, and set any required environment variables.

```yaml
...
  env:
  - NVIDIA_VISIBLE_DEVICES=void
  - LD_PRELOAD=/usr/lib64/libnvidia-ml.so.535.54.03
  
  - containerPath: /usr/lib64/libnvidia-ml.so.535.54.03
    hostPath: /opt/kata/share/kata-linux-gpu-drivers/libnvidia-ml.so.535.54.03
    type: bind
    options:
    - ro
    - nosuid
    - nodev
    - bind
    
  - containerPath: /usr/bin/nvidia-smi
    hostPath: /opt/kata/share/kata-linux-gpu-drivers/nvidia-smi
    type: bind
    options:
    - ro
    - nosuid
    - nodev
    - bind
...
```

**3. Are there tools available to assist with the conversion of config and cdi?**
Yes, of course. To address this, new subcommands `gpu gen-cfg` and `gpu gen-cdi` will be introduced to the too `kata-ctl` to facilitate the conversion process for GPU drivers. But they're not all.

**4. How to set vfio Device (GPU) assigned to Kata runtime in CDI config ?**
This task requires collaboration between the device-plugin or other components and kata-ctl. The device-plugin or other components should provide the IOMMU Group ID and other relevant information of the allocated GPU devices to the kata-ctl gpu commands. These commands will then be responsible for completing the devices section in the CDI configuration. An example of the devices configuration is as follows:
```yaml
...
devices:
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/75
  name: "0"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/76
  name: "1"
- containerEdits:
    deviceNodes:
    - path: /dev/vfio/75
    - path: /dev/vfio/76
  name: all
...
```

What's your opinions about this RFC, comments please !
