### ISSUE TITLE
Simplify OVMF building / shipping

### ISSUE THREAD

**Issue by fidencio** [kata-containers/kata-containers#9801]
```
  ovmf:
    description: "Firmware, implementation of UEFI for virtual machines."
    url: "https://github.com/tianocore/edk2"
    x86_64:
      description: "Vanilla firmware build"
      version: "edk2-stable202402"
      package: "OvmfPkg/OvmfPkgX64.dsc"
      package_output_dir: "OvmfX64"
    sev:
      description: "AmdSev build needed for SEV measured direct boot."
      version: "edk2-stable202402"
      package: "OvmfPkg/AmdSev/AmdSevX64.dsc"
      package_output_dir: "AmdSev"

```

Both SEV / vanilla OVMF are using exactly the same version, and we could just build one of those with different targets, as done by RHEL when shipping their EDK2 package.

I'd suggest folks take a look at this.

cc @ryansavino @AdithyaKrishnan @wainersm
