### ISSUE TITLE
PVC provisioning fails on SEV and SEV-SNP

### ISSUE THREAD

**Issue by Redent0r** [kata-containers/kata-containers#9846]
PVC provisioning fails on [SEV](https://github.com/kata-containers/kata-containers/actions/runs/9507409550/job/26207681037?pr=9835#step:6:4226) and [SEV-SNP](https://github.com/kata-containers/kata-containers/actions/runs/9507409550/job/26207682154?pr=9835#step:6:4264) with
```
#   Warning  FailedScheduling  89s   default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

**Comment by fidencio** [comment]
I took a closer look at this, and what seems to be happening here is:
* the test uses a PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: policy-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Mi
```
* as the PVC has no `storageClassName` it uses whatever is defined as the default storageClass on the cluster
* on AKS it seems there's a default storageClass, while we don't have anything setting that up for baremetal (TDX / SNP cases) or for the free runners.
* tests fails

There are other tests in the repo which deploy a local PV / PVC that can be used as an example if we want to make this one more generic.

Hope this helps to understand the issue.
