### ISSUE TITLE
Dragonball: Pod will crashloopbackoff when attempting to patch containers

### ISSUE THREAD

**Issue by cl0udee** [kata-containers/kata-containers#9915]
I'm experiencing an issue when dynamically adding containers to a running pod using Kata Containers 3.6 with Dragonball as the VMM, under Kubernetes with containerd.

The key error from `kubectl describe pod` is as follows:

`Error: failed to create containerd task: failed to create shim task: Others("failed to handle message create container\n\nCaused by:\n    0: create\n    1: failed to update_mem_resource\n    2: resize memory\n    3: failed to insert balloon device\n    4: Failed to insert balloon device: BalloonDeviceConfigInfo { balloon_id: \"balloon0\", size_mib: 0, use_shared_irq: None, use_generic_irq: None, f_deflate_on_oom: false, f_reporting: false }\n    5: vmm action error: UpcallServerNotReady"): unknown`

Is there anyone who knows how to solve this issue, please?

**Comment by cl0udee** [comment]
@HerlinCoder Excuse me for the interruption, but I noticed you have an PR related to supporting memory resizing with Dragonball. I guess you might have some valuable insights into my issue. I would greatly appreciate your advice.

**Comment by Apokleos** [comment]
Sorry @cl0udee for the trouble, I think you'd better give us more info about kata configuration and pod yaml in k8s. It can help us to reproduce this issue.

**Comment by cl0udee** [comment]
@Apokleos Thanks for your response and these are additional explanations. It's worth noting that if you wish to patch a new container into a pod, you would need to modify the kube-apiserver, as by default, the apiserver does not support such operations.

vmm-test.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: vmm-test
spec:
  runtimeClassName: kata-dragonball
  containers:
  - name: debug-container1
    image: docker.io/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "999d"]
    resources:
      limits:
        cpu: "500m"
        memory: "104Mi"
      requests:
        cpu: "200m"
        memory: "32Mi"
```
patch.yaml
```
spec:
  containers:
  - name: debug-container2
    image: docker.io/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "999d"]
    resources:
       limits:
         cpu: "500m"
         memory: "200Mi"
```
how to reproduce this issue:
```
kubectl apply -f vmm-test.yaml
kubectl patch pod vmm-test --patch-file patch.yaml
```
